"""Independent methodology-validation suite for the LWDiD estimator (PR #588).

This module is the maintainer-side ACCEPTANCE BAR for the third-party LWDiD
(Lee & Wooldridge rolling-transformation DiD) contribution. It is merged to
main BEFORE the estimator exists: the module-level ``pytest.importorskip``
makes it skip cleanly until ``diff_diff.lwdid`` lands.

The suite is written against the POST-RENAME canonical API agreed for the
final PR #588 round (``estimation_method=`` with values ``reg/ipw/dr/psm``,
``vcov_type=``, ``seed=``, ``pscore_trim=``, constructor ``cluster=``,
fit-time ``first_treat=``/``covariates=``, post-fit
``results.aggregate("event_study")``). It therefore INTENTIONALLY FAILS on
the pre-rename contribution head; the contributor's round is complete when
this suite passes unmodified.

This module verifies that the LWDiD implementation matches:

1. The published replication targets of Lee & Wooldridge (2026), Tables 3, 4
   and A1 (California Prop 99, three donor pools) including exact-inference
   p-values, with randomization inference anchored to the authors' Stata
   package convention (see the REGISTRY RI note: the paper's printed 0.020
   is not reproducible with the authors' package; the package's inclusive
   Phipson-Smyth convention yields ~0.051 and is the anchored behavior).
2. The castle-doctrine staggered application of LW (2026) Section 7.2
   (tau_omega via the composite-outcome regression (7.18)/(7.19)), including
   cross-path estimand consistency on balanced AND unbalanced panels.
3. The event-study replication targets of Lee & Wooldridge (2025), Appendix F
   Tables A4/A5 (Walmart entry) for point estimates, with bootstrap SEs
   anchored to the full-precision Stata golden
   (``benchmarks/data/lwdid_stata_golden.json``) at a Monte-Carlo-informed
   tolerance.
4. Estimator-independent properties: translation invariance of SEs,
   cross-estimator equivalences, from-scratch reference implementations,
   exact small-sample t inference (T_{N-2} / T_{N-K-2}), and the Monte Carlo
   bias ordering of LW 2026 Section 5 under heterogeneous trends.
5. REGISTRY.md edge cases and input contracts: minimum pre-treatment
   periods, all-eventually-treated rejection under both control strategies,
   unit-constant covariate/cluster validation on every path, mixed
   time-family rejection, and the retirement of the pre-release API surfaces
   (``TestRetiredSurfaces``).

Data sources:

- Prop 99 / Walmart: ``load_prop99()`` / ``load_walmart()`` (authors' SSC
  ancillary data; checksum-pinned). Tests skip unless
  ``df.attrs["source"] == "lwdid_ssc_ancillary"`` (i.e. real data, not the
  synthetic offline fallback).
- Castle doctrine: ``benchmarks/data/real/castle_lw_subset.csv``, the real
  Cheng & Hoekstra (2013) panel as packaged by Cunningham (2021) and
  distributed with PR #588 (extracted from commit 8c5cccea; columns state,
  year, effyear, lhomicide, homicide, population). Originally committed
  because the ``load_castle_doctrine`` upstream source was dead; that source
  is now pinned and verified, but this subset stays as the pinned artifact
  these goldens were captured against.
- Walmart event-study PRINT goldens:
  ``benchmarks/data/lwdid_walmart_eventstudy_golden.json`` (Tables A4/A5,
  provenance embedded in the file). NOTE: since the Stata arm landed, only
  the point halves of its ``[att, se]`` cells are consumed - the
  three-decimal printed SEs are superseded by the full-precision seeded
  Stata golden below and stay in the file as provenance.
- Stata parity golden: ``benchmarks/data/lwdid_stata_golden.json``
  (generated by ``benchmarks/stata/generate_lwdid_golden.do`` against the
  authors' SSC ``lwdid`` package; version recorded in its meta). Expected
  key-set constants shared with ``tests/test_lwdid_stata_golden_schema.py``
  (the ungated schema test), imported FROM there because this module's
  importorskip would break the reverse direction.

References:

- Lee, S.J., & Wooldridge, J.M. (2025). A Simple Transformation Approach to
  Difference-in-Differences Estimation for Panel Data. SSRN No. 4516518
  (revision of June 8, 2026). https://ssrn.com/abstract=4516518
- Lee, S.J., & Wooldridge, J.M. (2026). Simple Approaches to Inference with
  Difference-in-Differences Estimators with Small Cross-Sectional Sample
  Sizes. SSRN No. 5325686 (cover date February 3, 2026).
  https://ssrn.com/abstract=5325686
- docs/methodology/REGISTRY.md, section "LWDiD".
- docs/methodology/papers/lee-wooldridge-{2025,2026}-review.md.
"""

import importlib
import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pytest
from scipy import stats

from tests.test_lwdid_stata_golden_schema import (
    STATA_GOLDEN_PATH,
    WALMART_CONFIG_KEYS,
    WALMART_WATT_LABELS,
)

pytest.importorskip(
    "diff_diff.lwdid",
    reason="LWDiD estimator not yet on main (arrives via PR #588)",
)

from diff_diff import (  # noqa: E402
    DifferenceInDifferences,  # noqa: E402
    load_prop99,
    load_walmart,
)
from diff_diff.lwdid import LWDiD  # noqa: E402

# ---------------------------------------------------------------------------
# Published replication targets (LW 2026; see module docstring for provenance)
# ---------------------------------------------------------------------------

# Table 3 (38-state donor pool): {procedure: (ATT, SE)}
TABLE3_AVERAGE = {"demean": (-0.422, 0.121), "detrend": (-0.227, 0.094)}
TABLE3_PER_PERIOD = {
    "demean": {1989: (-0.168, 0.096), 1995: (-0.484, 0.137), 2000: (-0.667, 0.164)},
    "detrend": {1989: (-0.043, 0.059), 1995: (-0.282, 0.112), 2000: (-0.403, 0.152)},
}
TABLE3_DETREND_EXACT_P = 0.021
PROP99_TREAT_START = 1989  # g: first treated year (event time r = year - g)

# Table 4 (Southern pool) and Table A1 (Midwestern pool): Average rows
SOUTHERN_POOL = ["Alabama", "Arkansas", "Louisiana", "Mississippi"]
TABLE4_AVERAGE = {"demean": (-0.556, 0.080), "detrend": (-0.215, 0.039)}
MIDWEST_POOL = ["Illinois", "Iowa", "Minnesota", "Ohio"]
TABLEA1_AVERAGE = {"demean": (-0.413, 0.118), "detrend": (-0.198, 0.079)}

# Castle-laws application (Section 7.2): tau_omega targets
CASTLE_COHORTS = {2005: 1, 2006: 13, 2007: 4, 2008: 2, 2009: 1}
CASTLE_TAU_DEMEAN = (0.092, 0.057)  # (tau_omega, usual OLS SE)
CASTLE_TAU_DETREND = 0.067

# Printed-precision tolerance for 3-decimal published tables
PRINTED_ATOL = 1e-3

# Full-precision Stata parity tolerances: observed cross-BLAS agreement is
# ~1e-9..3e-9 ABSOLUTE while some parity cells are near zero, so an atol
# floor is mandatory (rtol alone would demand ~1e-11 on ~1e-5 cells).
PARITY_RTOL = 1e-6
PARITY_ATOL = 1e-8
# IPWRA configs go through a logit propensity fit whose optimizer path
# differs across implementations: measured cross-implementation agreement vs
# Stata is ~9e-4 relative on well-sized points (Post_avg ~2e-4) and ~2e-5
# ABSOLUTE on near-zero placebo cells - consistent with the contribution's
# own documented "within 1%" vs lwdid-py - while the RA config agrees to
# ~1e-9. The IPWRA gates therefore use documented looser tolerances (~5x
# headroom over the measured divergence, still far below any structural
# break).
IPWRA_PARITY_RTOL = 5e-3
IPWRA_PARITY_ATOL = 1e-4

#: Stata golden keys use the authors' method vocabulary (ra/ipwra); the
#: canonical API uses reg/dr. ONE decoder so no test drifts.
STATA_TO_CANONICAL_METHOD = {"ra": "reg", "ipwra": "dr"}


def _decode_walmart_key(key):
    """ "<rolling>_<stata_method>__<outcome>" -> (rolling, canonical_method, outcome)."""
    rolling, method_outcome = key.split("_", 1)
    stata_method, outcome = method_outcome.split("__")
    return rolling, STATA_TO_CANONICAL_METHOD[stata_method], outcome


_CASTLE_CSV = (
    Path(__file__).resolve().parent.parent / "benchmarks" / "data" / "real" / "castle_lw_subset.csv"
)
_WALMART_ES_GOLDEN = (
    Path(__file__).resolve().parent.parent
    / "benchmarks"
    / "data"
    / "lwdid_walmart_eventstudy_golden.json"
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_stata_golden():
    """Load the Stata parity golden or skip (partial checkout)."""
    if not STATA_GOLDEN_PATH.exists():
        pytest.skip(f"{STATA_GOLDEN_PATH.name} not committed (partial checkout)")
    return json.loads(STATA_GOLDEN_PATH.read_text())


def _real_prop99():
    """Load the real Prop 99 panel or skip (offline / synthetic fallback).

    Skips are VISIBLE (not silent): CI runners have network and the loaders
    are SHA-256-pinned, so these tests run in practice; the dedicated
    real-data canary lane (`.github/workflows/lwdid-data-canary.yml`,
    weekly cron) fails LOUDLY when either loader is on its synthetic
    fallback, so a network/URL/sha regression cannot stay green.
    """
    df = load_prop99()
    if df.attrs.get("source") != "lwdid_ssc_ancillary":
        pytest.skip("real Prop 99 data unavailable (synthetic fallback in use)")
    return df


def _real_walmart():
    """Load the real Walmart panel or skip (offline / synthetic fallback).

    Same skip contract and canary coverage as ``_real_prop99``.
    """
    df = load_walmart()
    if df.attrs.get("source") != "lwdid_ssc_ancillary":
        pytest.skip("real Walmart data unavailable (synthetic fallback in use)")
    return df


def _fit_prop99(df, rolling, **kwargs):
    est = LWDiD(rolling=rolling, estimation_method="reg", vcov_type="classical", **kwargs)
    return est.fit(df, outcome="lcigsale", unit="state", time="year", treatment="treated")


def _demean_reference(df, unit, time, outcome, pre_end):
    """From-scratch Procedure 2.1: per-unit pre-mean, post-average residual."""
    out = {}
    for u, g in df.groupby(unit):
        g = g.sort_values(time)
        pre = g.loc[g[time] <= pre_end, outcome].to_numpy()
        post = g.loc[g[time] > pre_end, outcome].to_numpy()
        out[u] = post.mean() - pre.mean()
    return pd.Series(out)


def _detrend_reference(df, unit, time, outcome, pre_end):
    """From-scratch Procedure 3.1: per-unit pre-period OLS on (1, t),
    out-of-sample residuals for post periods, averaged."""
    out = {}
    for u, g in df.groupby(unit):
        g = g.sort_values(time)
        pre = g[g[time] <= pre_end]
        post = g[g[time] > pre_end]
        X = np.column_stack([np.ones(len(pre)), pre[time].to_numpy(dtype=float)])
        beta, *_ = np.linalg.lstsq(X, pre[outcome].to_numpy(dtype=float), rcond=None)
        yhat = beta[0] + beta[1] * post[time].to_numpy(dtype=float)
        out[u] = float((post[outcome].to_numpy(dtype=float) - yhat).mean())
    return pd.Series(out)


def _cross_section_did(ybar, treated):
    """OLS of the collapsed outcome on (1, D): returns (tau, classical SE, df)."""
    y = ybar.to_numpy(dtype=float)
    d = treated.to_numpy(dtype=float)
    X = np.column_stack([np.ones_like(d), d])
    beta, *_ = np.linalg.lstsq(X, y, rcond=None)
    resid = y - X @ beta
    n, k = X.shape
    dof = n - k
    sigma2 = resid @ resid / dof
    cov = sigma2 * np.linalg.inv(X.T @ X)
    return float(beta[1]), float(np.sqrt(cov[1, 1])), dof


def _synthetic_common_timing(n_treat=60, n_control=140, t_max=8, s=5, effect=1.5, seed=11):
    """Seeded synthetic common-timing panel with one covariate."""
    rng = np.random.default_rng(seed)
    rows = []
    for i in range(n_treat + n_control):
        is_treated = i < n_treat
        a = rng.normal(0, 1)
        x = rng.normal(0, 1)
        for t in range(1, t_max + 1):
            post = t >= s
            y = (
                a
                + 0.4 * x
                + 0.2 * t
                + rng.normal(0, 0.6)
                + (effect if is_treated and post else 0.0)
            )
            rows.append(
                {
                    "unit": i,
                    "time": t,
                    "y": y,
                    "x": x,
                    "treat": int(is_treated and post),
                    "treated_group": int(is_treated),
                    "post": int(post),
                }
            )
    return pd.DataFrame(rows)


def _synthetic_staggered(n_units=120, t_max=10, cohorts=(5, 7), nt_share=0.4, seed=23):
    """Seeded synthetic staggered panel: cohorts + never-treated (first_year=0)."""
    rng = np.random.default_rng(seed)
    rows = []
    for i in range(n_units):
        u = rng.uniform()
        if u < nt_share:
            g = 0
        else:
            g = cohorts[int(rng.integers(0, len(cohorts)))]
        a = rng.normal(0, 1)
        for t in range(1, t_max + 1):
            te = 1.0 + 0.1 * (t - g) if (g > 0 and t >= g) else 0.0
            y = a + 0.15 * t + rng.normal(0, 0.5) + te
            rows.append(
                {
                    "unit": i,
                    "time": t,
                    "y": y,
                    "first_year": g,
                    "treat": int(g > 0 and t >= g),
                }
            )
    return pd.DataFrame(rows)


def _synthetic_unbalanced_staggered():
    """Deterministic UNBALANCED never-treated staggered panel.

    Exact recipe of the 2026-08-16 verification run that demonstrated the
    composite-vs-joint-IF point divergence (2.1318 vs 2.1136) on the
    contribution head: draws happen inside the unit/time loops in this exact
    order (alpha per unit first, then one noise draw per RETAINED row - the
    unbalancing `continue` fires BEFORE the row's noise draw, so the stream
    depends on the drop pattern exactly as below).
    """
    rng = np.random.default_rng(7)
    rows = []
    uid = 0
    for g, n in [(0, 8), (4, 5), (6, 5)]:
        for _ in range(n):
            alpha = rng.normal()
            for t in range(1, 9):
                if uid % 3 == 1 and t in (2, 8):
                    continue
                d = int(g > 0 and t >= g)
                y = alpha + 0.1 * t + rng.normal(scale=0.3) + (2.0 + 0.5 * (g == 6)) * d
                rows.append(dict(unit=uid, time=t, first=g, treat=d, y=y))
            uid += 1
    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# 1. Prop 99, Table 3 (38-state donor pool)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def prop99():
    return _real_prop99()


@pytest.fixture(scope="module")
def walmart():
    return _real_walmart()


@pytest.fixture(scope="module")
def print_golden():
    """The printed Tables A4/A5 golden (point halves consumed only)."""
    if not _WALMART_ES_GOLDEN.exists():
        pytest.skip(f"{_WALMART_ES_GOLDEN.name} not committed (partial checkout)")
    return json.loads(_WALMART_ES_GOLDEN.read_text())


@pytest.fixture(scope="module")
def stata_golden():
    return _load_stata_golden()


_ES_FIT_CACHE = {}


@pytest.fixture(scope="module")
def es_fit(walmart):
    """Memoizing factory: each Walmart event-study config fits exactly ONCE
    across all consuming classes (B=999 bootstrap fits are the expensive
    unit of this module)."""

    def _fit(rolling, estimation_method, outcome="log_retail_emp"):
        key = (rolling, estimation_method, outcome)
        if key not in _ES_FIT_CACHE:
            # The dr/ipw configs REQUIRE covariates: without them the paths
            # degrade to reg (with a warning), which would invalidate the
            # Stata parity comparison (the Stata runs pass x1-x3).
            covariates = ["x1", "x2", "x3"] if estimation_method in ("dr", "ipw") else None
            est = LWDiD(
                rolling=rolling,
                estimation_method=estimation_method,
                n_bootstrap=999,
                seed=42,
            )
            _ES_FIT_CACHE[key] = est.fit(
                walmart,
                outcome=outcome,
                unit="cid",
                time="year",
                treatment="treated",
                first_treat="first_year",
                covariates=covariates,
            )
        return _ES_FIT_CACHE[key]

    return _fit


@pytest.mark.realdata
class TestProp99Table3Goldens:
    """LW (2026) Table 3: the authors' Stata `lwdid` output, frozen in print."""

    @pytest.mark.parametrize("rolling", ["demean", "detrend"])
    def test_average_att_and_se(self, prop99, rolling):
        res = _fit_prop99(prop99, rolling)
        att, se = TABLE3_AVERAGE[rolling]
        np.testing.assert_allclose(res.att, att, atol=PRINTED_ATOL)
        np.testing.assert_allclose(res.se, se, atol=PRINTED_ATOL)

    @pytest.mark.parametrize("rolling", ["demean", "detrend"])
    def test_per_period_atts(self, prop99, rolling):
        """Common-timing per-period effects via the unified post-fit
        event-study surface (the `period_specific=`/`period_effects` pair is
        retired). Event time r = year - g with g = 1989; Table 3 prints both
        the point and the usual OLS SE per year."""
        res = _fit_prop99(prop99, rolling)
        es = res.aggregate("event_study")
        labels = {int(e): i for i, e in enumerate(np.asarray(es.event_time))}
        for year, (att, se) in TABLE3_PER_PERIOD[rolling].items():
            r = year - PROP99_TREAT_START
            assert r in labels, f"event time {r} (year {year}) missing from surface"
            i = labels[r]
            assert not bool(np.asarray(es.is_reference)[i])
            np.testing.assert_allclose(np.asarray(es.att)[i], att, atol=PRINTED_ATOL)
            np.testing.assert_allclose(np.asarray(es.se)[i], se, atol=PRINTED_ATOL)

    def test_detrend_exact_inference_p_value(self, prop99):
        res = _fit_prop99(prop99, "detrend")
        np.testing.assert_allclose(res.p_value, TABLE3_DETREND_EXACT_P, atol=PRINTED_ATOL)

    def test_detrend_randomization_inference_p_value(self, prop99, stata_golden):
        """RI anchored to the AUTHORS' PACKAGE convention, not the paper's
        printed 0.020.

        Adjudicated 2026-08-15 against Stata `lwdid` v2.4.2: its RI counts
        permutations at least as extreme (inclusive ties) under the
        Phipson-Smyth plus-one rule, converging to ~0.0508 at 100k reps -
        the paper's printed 0.020 is NOT reproducible (~4.5 binomial SD
        away) and is recorded as an as-printed discrepancy in the REGISTRY
        RI note. Tolerance covers ~3 binomial SEs at p ~= 0.05 with 1,000
        replications.
        """
        from diff_diff.lwdid_randomization import randomization_inference

        anchor = stata_golden["prop99"]["detrend"]["p_ri"]
        ybar = _detrend_reference(prop99, "state", "year", "lcigsale", pre_end=1988)
        treated = prop99.groupby("state")["first_year"].first().loc[ybar.index] > 0
        ri = randomization_inference(
            ybar.to_numpy(), treated.to_numpy(dtype=float), n_reps=1000, seed=2026
        )
        n_reps = 1000
        atol = 3 * np.sqrt(anchor * (1 - anchor) / n_reps)
        np.testing.assert_allclose(ri.pvalue, anchor, atol=atol)

    def test_randomization_inference_plus_one_formula(self, prop99):
        """Deterministic pin of the inclusive Phipson-Smyth formula: the
        reported p equals (c + 1) / (B + 1) EXACTLY, with c the count of
        permuted statistics at least as extreme as observed, recomputed here
        from the returned draw distribution (the MC-tolerance anchor above
        cannot distinguish (c+1)/(B+1) from c/B)."""
        from diff_diff.lwdid_randomization import randomization_inference

        ybar = _detrend_reference(prop99, "state", "year", "lcigsale", pre_end=1988)
        treated = prop99.groupby("state")["first_year"].first().loc[ybar.index] > 0
        ri = randomization_inference(
            ybar.to_numpy(), treated.to_numpy(dtype=float), n_reps=499, seed=7
        )
        dist = np.asarray(ri.att_distribution, dtype=float)
        assert dist.shape == (499,)
        c = int(np.sum(np.abs(dist) >= abs(ri.att_observed)))
        np.testing.assert_allclose(ri.pvalue, (c + 1) / (499 + 1), rtol=0, atol=0)


# ---------------------------------------------------------------------------
# 2. Prop 99, alternative donor pools (Tables 4 and A1)
# ---------------------------------------------------------------------------


@pytest.mark.realdata
class TestDonorPoolVariants:
    """LW (2026) Tables 4 / A1: Southern and Midwestern donor pools."""

    @pytest.mark.parametrize(
        "pool,targets",
        [(SOUTHERN_POOL, TABLE4_AVERAGE), (MIDWEST_POOL, TABLEA1_AVERAGE)],
        ids=["table4_southern", "tableA1_midwest"],
    )
    @pytest.mark.parametrize("rolling", ["demean", "detrend"])
    def test_average_att_and_se(self, prop99, pool, targets, rolling):
        sub = prop99[prop99["state"].isin(pool + ["California"])]
        assert sub["state"].nunique() == 5
        res = _fit_prop99(sub, rolling)
        att, se = targets[rolling]
        np.testing.assert_allclose(res.att, att, atol=PRINTED_ATOL)
        np.testing.assert_allclose(res.se, se, atol=PRINTED_ATOL)


# ---------------------------------------------------------------------------
# 3. Castle doctrine (Section 7.2): the aggregation adjudicator
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def castle():
    if not _CASTLE_CSV.exists():
        pytest.skip(f"{_CASTLE_CSV.name} not committed (partial checkout)")
    df = pd.read_csv(_CASTLE_CSV)
    # Data-integrity assertion: this must be the paper's exact sample.
    fy = df.groupby("state")["effyear"].first()
    counts = fy.dropna().astype(int).value_counts().sort_index().to_dict()
    assert counts == CASTLE_COHORTS, f"castle cohorts {counts} != paper {CASTLE_COHORTS}"
    assert df["state"].nunique() == 50
    assert int(fy.isna().sum()) == 29
    df = df.copy()
    df["first_year"] = df["effyear"].fillna(0).astype(int)
    df["treat"] = ((df["first_year"] > 0) & (df["year"] >= df["first_year"])).astype(int)
    return df


def _fit_castle(castle, rolling, vcov_type="classical"):
    # The paper's per-cohort effects (7.10) use never-treated controls;
    # PR #588's default control pool is not-yet-treated, which moves the
    # castle point estimate from 0.092 to 0.074 (calibrated 2026-07-13).
    est = LWDiD(
        rolling=rolling,
        estimation_method="reg",
        vcov_type=vcov_type,
        control_group="never_treated",
    )
    return est.fit(
        castle,
        outcome="lhomicide",
        unit="state",
        time="year",
        treatment="treat",
        first_treat="first_year",
    )


@pytest.mark.realdata
class TestCastleTauOmegaAdjudicator:
    """LW (2026) Section 7.2: staggered tau_omega via composite regression.

    This class adjudicates PR #588's staggered aggregation: the paper's
    tau_omega comes from the single composite-outcome regression
    (7.18)/(7.19); a numerically different aggregation cannot reproduce
    the paper's point estimate and OLS SE simultaneously.
    """

    @staticmethod
    def _composite_reference(castle, rolling):
        """From-scratch LW 2026 (7.18)/(7.19): composite outcome + single
        cross-sectional regression. Reproduces the paper's printed targets
        (verified: demean 0.0917/SE 0.0571; detrend 0.0666)."""
        fy = castle.groupby("state")["first_year"].first()
        cohorts = sorted(set(fy[fy > 0]))
        n_treat = int((fy > 0).sum())
        transform = _demean_reference if rolling == "demean" else _detrend_reference
        ydot = {g: transform(castle, "state", "year", "lhomicide", pre_end=g - 1) for g in cohorts}
        y, d = [], []
        for s in fy.index:
            g = fy[s]
            if g > 0:
                y.append(ydot[g][s])
                d.append(1.0)
            else:
                y.append(sum((fy[fy == gg].size / n_treat) * ydot[gg][s] for gg in cohorts))
                d.append(0.0)
        tau, se, dof = _cross_section_did(pd.Series(y), pd.Series(d))
        return tau, se

    def test_composite_regression_reference_reproduces_paper(self, castle):
        """The (7.18)/(7.19) reference implementation hits the printed targets -
        proving the targets are reproducible and the sample construction is
        correct, independent of the PR #588 estimator."""
        tau_dm, se_dm = self._composite_reference(castle, "demean")
        np.testing.assert_allclose(tau_dm, CASTLE_TAU_DEMEAN[0], atol=PRINTED_ATOL)
        np.testing.assert_allclose(se_dm, CASTLE_TAU_DEMEAN[1], atol=PRINTED_ATOL)
        tau_dt, _ = self._composite_reference(castle, "detrend")
        np.testing.assert_allclose(tau_dt, CASTLE_TAU_DETREND, atol=PRINTED_ATOL)

    def test_demean_tau_omega_point(self, castle):
        res = _fit_castle(castle, "demean")
        np.testing.assert_allclose(res.att, CASTLE_TAU_DEMEAN[0], atol=PRINTED_ATOL)

    def test_demean_tau_omega_ols_se(self, castle):
        """The overall SE comes from the composite-outcome regression
        (7.18)/(7.19) - the paper's OLS SE (0.057)."""
        res = _fit_castle(castle, "demean")
        np.testing.assert_allclose(res.se, CASTLE_TAU_DEMEAN[1], atol=PRINTED_ATOL)

    def test_detrend_tau_omega_point(self, castle):
        res = _fit_castle(castle, "detrend")
        np.testing.assert_allclose(res.att, CASTLE_TAU_DETREND, atol=PRINTED_ATOL)

    def test_balanced_cross_path_estimand_consistency(self, castle):
        """The composite path (classical gate) and the joint-IF path (hc1)
        must estimate the SAME tau_omega: a variance option must never move
        the point estimate."""
        rc = _fit_castle(castle, "demean", vcov_type="classical")
        rh = _fit_castle(castle, "demean", vcov_type="hc1")
        np.testing.assert_allclose(rc.att, rh.att, rtol=0, atol=1e-10)


class TestUnbalancedEstimandConsistency:
    """Cross-path estimand consistency on an UNBALANCED panel.

    Verified by execution 2026-08-16 on the contribution head: the composite
    path and the joint-IF path returned DIFFERENT points (2.1318 vs 2.1136,
    diff 1.8e-2) on this exact fixture, switching purely on ``vcov_type`` -
    the two weightings coincide under balance, so the balanced castle check
    cannot see it. The joint-IF aggregation weights must implement the SAME
    (7.18) tau_omega estimand as the composite regression.
    """

    def test_unbalanced_cross_path_estimand_consistency(self):
        df = _synthetic_unbalanced_staggered()
        kw = dict(outcome="y", unit="unit", time="time", treatment="treat", first_treat="first")
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            rc = LWDiD(
                rolling="demean",
                estimation_method="reg",
                vcov_type="classical",
                control_group="never_treated",
            ).fit(df, **kw)
            rh = LWDiD(
                rolling="demean",
                estimation_method="reg",
                vcov_type="hc1",
                control_group="never_treated",
            ).fit(df, **kw)
        np.testing.assert_allclose(rc.att, rh.att, rtol=0, atol=1e-10)


# ---------------------------------------------------------------------------
# 4. Translation invariance of SEs (property test)
# ---------------------------------------------------------------------------


class TestTranslationInvariance:
    """A constant added to all post-period outcomes shifts every transformed
    outcome equally: the ATT is invariant, and any correct SE is invariant."""

    SHIFT = 100.0

    def _fit_pair(self, estimation_method):
        df = _synthetic_common_timing()
        df2 = df.copy()
        df2["y"] = df2["y"] + self.SHIFT * df2["post"]
        kw = dict(outcome="y", unit="unit", time="time", treatment="treat", covariates=["x"])
        r1 = LWDiD(rolling="demean", estimation_method=estimation_method, vcov_type="hc1").fit(
            df, **kw
        )
        r2 = LWDiD(rolling="demean", estimation_method=estimation_method, vcov_type="hc1").fit(
            df2, **kw
        )
        return r1, r2

    @pytest.mark.parametrize("estimation_method", ["reg", "dr", "ipw"])
    def test_att_translation_invariant(self, estimation_method):
        r1, r2 = self._fit_pair(estimation_method)
        np.testing.assert_allclose(r1.att, r2.att, rtol=0, atol=1e-10)

    @pytest.mark.parametrize("estimation_method", ["reg", "dr", "ipw"])
    def test_se_translation_invariant(self, estimation_method):
        r1, r2 = self._fit_pair(estimation_method)
        np.testing.assert_allclose(r1.se, r2.se, rtol=0, atol=1e-10)


# ---------------------------------------------------------------------------
# 5. Cross-estimator equivalences
# ---------------------------------------------------------------------------


class TestCrossEstimatorEquivalence:
    """Theory-mandated numerical identities against already-validated code."""

    def test_demean_reg_equals_plain_did(self):
        """Common timing, no covariates: rolling demeaning + RA reproduces the
        standard DiD estimator exactly (LW 2026, eq. (2.5) / Section 9)."""
        df = _synthetic_common_timing()
        lw = LWDiD(rolling="demean", estimation_method="reg", vcov_type="classical").fit(
            df, outcome="y", unit="unit", time="time", treatment="treat"
        )
        dd = DifferenceInDifferences().fit(df, outcome="y", treatment="treated_group", post="post")
        np.testing.assert_allclose(lw.att, dd.att, rtol=0, atol=1e-10)

    @pytest.mark.parametrize("r_calendar", [5, 7])
    def test_per_period_equals_subset_panel_did(self, r_calendar):
        """LW 2026 eq. (2.20): the per-period effect tau_hat_{t,DD} is
        numerically identical to a standard panel DiD run on periods
        {1, ..., S-1, t}. Read through the unified event-study surface
        (calendar period r_calendar with treatment start s=5 is event time
        r_calendar - 5)."""
        df = _synthetic_common_timing(t_max=8, s=5)
        res = LWDiD(rolling="demean", estimation_method="reg", vcov_type="classical").fit(
            df, outcome="y", unit="unit", time="time", treatment="treat"
        )
        es = res.aggregate("event_study")
        labels = {int(e): i for i, e in enumerate(np.asarray(es.event_time))}
        r_event = r_calendar - 5
        assert r_event in labels
        sub = df[(df["time"] < 5) | (df["time"] == r_calendar)]
        dd = DifferenceInDifferences().fit(sub, outcome="y", treatment="treated_group", post="post")
        np.testing.assert_allclose(np.asarray(es.att)[labels[r_event]], dd.att, rtol=0, atol=1e-10)

    def test_detrend_t3_closed_form(self):
        """LW 2025 eq. (5.7): with T=3, S=3, no covariates, the detrending
        estimator equals the difference-in-difference-in-differences of
        period means."""
        rng = np.random.default_rng(7)
        rows = []
        for i in range(80):
            treated = i < 30
            a, b = rng.normal(0, 1), rng.normal(0.1, 0.05)
            for t in (1, 2, 3):
                y = a + b * t + rng.normal(0, 0.3) + (0.8 if treated and t == 3 else 0.0)
                rows.append({"unit": i, "time": t, "y": y, "treat": int(treated and t == 3)})
        df = pd.DataFrame(rows)
        res = LWDiD(rolling="detrend", estimation_method="reg", vcov_type="classical").fit(
            df, outcome="y", unit="unit", time="time", treatment="treat"
        )
        m = df.assign(g=(df["unit"] < 30).astype(int)).groupby(["g", "time"])["y"].mean()
        closed = ((m[1, 3] - m[1, 2]) - (m[0, 3] - m[0, 2])) - (
            (m[1, 2] - m[1, 1]) - (m[0, 2] - m[0, 1])
        )
        np.testing.assert_allclose(res.att, closed, rtol=0, atol=1e-10)


# ---------------------------------------------------------------------------
# 6. From-scratch reference implementations
# ---------------------------------------------------------------------------


class TestFromScratchReference:
    """Pure-numpy reimplementation of the procedures, blind to the estimator."""

    def test_procedure_2_1_demeaning(self):
        df = _synthetic_common_timing(t_max=8, s=5)
        ybar = _demean_reference(df, "unit", "time", "y", pre_end=4)
        treated = df.groupby("unit")["treated_group"].first().loc[ybar.index]
        tau, se, dof = _cross_section_did(ybar, treated)
        res = LWDiD(rolling="demean", estimation_method="reg", vcov_type="classical").fit(
            df, outcome="y", unit="unit", time="time", treatment="treat"
        )
        np.testing.assert_allclose(res.att, tau, rtol=0, atol=1e-10)
        np.testing.assert_allclose(res.se, se, rtol=1e-8)

    def test_procedure_3_1_detrending(self):
        df = _synthetic_common_timing(t_max=8, s=5)
        ybar = _detrend_reference(df, "unit", "time", "y", pre_end=4)
        treated = df.groupby("unit")["treated_group"].first().loc[ybar.index]
        tau, se, dof = _cross_section_did(ybar, treated)
        res = LWDiD(rolling="detrend", estimation_method="reg", vcov_type="classical").fit(
            df, outcome="y", unit="unit", time="time", treatment="treat"
        )
        np.testing.assert_allclose(res.att, tau, rtol=0, atol=1e-10)
        np.testing.assert_allclose(res.se, se, rtol=1e-8)

    def test_staggered_per_cohort_demeaning(self):
        """LW 2026 (7.4)/(7.9)/(7.10): per-cohort post-average demeaned
        outcome, regression on the cohort + never-treated subsample
        (control_group='never_treated' matches the (7.10) sample)."""
        df = _synthetic_staggered()
        res = LWDiD(
            rolling="demean",
            estimation_method="reg",
            vcov_type="classical",
            control_group="never_treated",
        ).fit(
            df, outcome="y", unit="unit", time="time", treatment="treat", first_treat="first_year"
        )
        assert res.cohort_effects, "staggered fit should populate cohort_effects"
        fy = df.groupby("unit")["first_year"].first()
        for g in sorted(set(fy[fy > 0])):
            members = fy.index[(fy == g) | (fy == 0)]
            sub = df[df["unit"].isin(members)]
            ybar = _demean_reference(sub, "unit", "time", "y", pre_end=g - 1)
            treated = (fy.loc[ybar.index] == g).astype(int)
            tau, se, dof = _cross_section_did(ybar, treated)
            eff = res.cohort_effects[g]
            np.testing.assert_allclose(eff["att"], tau, rtol=0, atol=1e-10)


# ---------------------------------------------------------------------------
# 7. Exact small-sample inference (LW 2026, Section 2)
# ---------------------------------------------------------------------------


class TestExactSmallSampleInference:
    """The collapsed cross-sectional regression carries exact t inference."""

    def test_classical_p_value_uses_t_n_minus_2(self):
        df = _synthetic_common_timing(n_treat=6, n_control=10, t_max=6, s=4)
        res = LWDiD(rolling="demean", estimation_method="reg", vcov_type="classical").fit(
            df, outcome="y", unit="unit", time="time", treatment="treat"
        )
        n = df["unit"].nunique()
        p_expected = 2 * stats.t.sf(abs(res.t_stat), n - 2)
        np.testing.assert_allclose(res.p_value, p_expected, rtol=1e-10)

    def test_covariate_exact_inference_is_design_coherent(self):
        """Covariate-adjusted exact inference must be DESIGN-COHERENT.

        LW 2026 Section 2 sanctions two controlled collapsed regressions:
        the plain-controls design ``(1, D, X)`` with exact reference
        T_{N-K-2}, and the interacted design ``(1, D, X, D(X - Xbar_1))``
        whose design rank implies T_{N-2K-2} (with the per-group sample
        guards). Either is admissible; what is NOT is mixing them - fitting
        one design while reporting the other design's df gives
        anti-conservative exact p-values. MEASURED on the contribution head
        2026-08-16: the fitted att reproduces the INTERACTED design exactly
        while the p-value uses the plain design's T_{N-K-2} (df 19 vs the
        coherent 18 on a N=22, K=1 panel) - a required fix. This test
        identifies which design produced the point estimate and requires the
        p-value to use THAT design's residual df.
        """
        df = _synthetic_common_timing(n_treat=8, n_control=14, t_max=6, s=4)
        res = LWDiD(rolling="demean", estimation_method="reg", vcov_type="classical").fit(
            df, outcome="y", unit="unit", time="time", treatment="treat", covariates=["x"]
        )
        ybar = _demean_reference(df, "unit", "time", "y", pre_end=3)
        d = df.groupby("unit")["treated_group"].first().loc[ybar.index].to_numpy(dtype=float)
        xv = df.groupby("unit")["x"].first().loc[ybar.index].to_numpy(dtype=float)
        y = ybar.to_numpy(dtype=float)
        plain = np.column_stack([np.ones_like(d), d, xv])
        xbar_treated = xv[d == 1].mean()
        interacted = np.column_stack([np.ones_like(d), d, xv, d * (xv - xbar_treated)])
        n = len(y)
        matches = {}
        for name, X in (("plain", plain), ("interacted", interacted)):
            beta, *_ = np.linalg.lstsq(X, y, rcond=None)
            matches[name] = (abs(float(beta[1]) - res.att) < 1e-10, X.shape[1])
        matched = [name for name, (hit, _) in matches.items() if hit]
        assert len(matched) == 1, f"att matches designs: {matched or 'none'}"
        n_params = matches[matched[0]][1]
        p_expected = 2 * stats.t.sf(abs(res.t_stat), n - n_params)
        np.testing.assert_allclose(res.p_value, p_expected, rtol=1e-10)

    def test_single_treated_unit_inference_is_finite(self):
        """N1 = 1: exact inference remains valid (studentized-residual t)."""
        df = _synthetic_common_timing(n_treat=1, n_control=12, t_max=6, s=4)
        res = LWDiD(rolling="demean", estimation_method="reg", vcov_type="classical").fit(
            df, outcome="y", unit="unit", time="time", treatment="treat"
        )
        assert np.isfinite(res.att)
        assert np.isfinite(res.se) and res.se > 0
        assert np.isfinite(res.p_value)
        n = df["unit"].nunique()
        p_expected = 2 * stats.t.sf(abs(res.t_stat), n - 2)
        np.testing.assert_allclose(res.p_value, p_expected, rtol=1e-10)

    def test_never_treated_pool_of_one_is_rejected(self):
        """The N_infinity >= 2 requirement applies to the NT-only control
        strategy (LW 2026, p26); NYT controls are exempt."""
        df = _synthetic_staggered(n_units=30, nt_share=0.0, seed=5)
        # Force exactly one never-treated unit
        first_unit = df["unit"] == 0
        df.loc[first_unit, "first_year"] = 0
        df.loc[first_unit, "treat"] = 0
        with pytest.raises(ValueError, match="[Nn]ever[- ]treated"):
            LWDiD(
                rolling="demean",
                estimation_method="reg",
                vcov_type="classical",
                control_group="never_treated",
            ).fit(
                df,
                outcome="y",
                unit="unit",
                time="time",
                treatment="treat",
                first_treat="first_year",
            )

    @pytest.mark.parametrize("control_group", ["not_yet_treated", "never_treated"])
    def test_all_eventually_treated_is_rejected(self, control_group):
        """All-eventually-treated designs are rejected under BOTH control
        strategies (REGISTRY Sec 4.3 note; the last-cohort-reference mode is
        deferred, see DEFERRED.md)."""
        rows = []
        rng = np.random.default_rng(12)
        for unit in range(12):
            g = 3 if unit < 6 else 5
            for t in range(1, 7):
                rows.append(
                    {
                        "unit": unit,
                        "time": t,
                        "first_year": g,
                        "treat": int(t >= g),
                        "y": float(rng.normal()),
                    }
                )
        df = pd.DataFrame(rows)
        with pytest.raises(ValueError):
            LWDiD(rolling="demean", estimation_method="reg", control_group=control_group).fit(
                df,
                outcome="y",
                unit="unit",
                time="time",
                treatment="treat",
                first_treat="first_year",
            )


# ---------------------------------------------------------------------------
# 8. Event-study surface (post-fit aggregate; Walmart replication)
# ---------------------------------------------------------------------------


@pytest.mark.realdata
class TestEventStudySpec:
    """Normative event-study surface for LWDiD (maintainer-specified).

    Per-relative-period effects are computed jointly at fit and read back
    via post-fit ``results.aggregate("event_study")`` (fit-time
    ``aggregate=`` is forbidden for new estimators, docs/v4-design.md). The
    raw ``event_study_effects: Dict[int, Dict]`` dict excludes the anchor
    periods (r = -1 demeaning; r = -2, -1 detrending); the public
    ``EventStudyResults`` surface emits observed anchors as zero-valued
    ``is_reference`` rows. Bootstrap SEs come from the Algorithm 1
    unit-level Rademacher multiplier bootstrap (B = 999 here).
    """

    def test_walmart_raw_label_sets_match_measured_constants(self, es_fit):
        """Fail-closed coverage: the raw event_study_effects key set equals
        the measured per-config constant (shared with the schema test) so a
        silently shrunken surface cannot pass by iterating fewer rows."""
        for key, expected in WALMART_WATT_LABELS.items():
            rolling, method, outcome = _decode_walmart_key(key)
            res = es_fit(rolling, method, outcome=outcome)
            anchors = {-1} if rolling == "demean" else {-2, -1}
            expected_raw = set(expected) - anchors
            assert set(res.event_study_effects) == expected_raw, key

    @pytest.mark.parametrize(
        "outcome,table_key",
        [
            ("log_retail_emp", "table_a4_log_retail"),
            ("log_wholesale_emp", "table_a5_log_wholesale"),
        ],
        ids=["a4_retail", "a5_wholesale"],
    )
    @pytest.mark.parametrize(
        "rolling,method,column",
        [
            ("detrend", "reg", "rolling_ra_detrend"),
            ("detrend", "dr", "rolling_ipwra_detrend"),
            ("demean", "dr", "rolling_ipwra_demean"),
        ],
    )
    def test_walmart_eventstudy_point_goldens(
        self, print_golden, es_fit, rolling, method, column, outcome, table_key
    ):
        """Deterministic WATT(r) point estimates vs printed Tables A4/A5."""
        res = es_fit(rolling, method, outcome=outcome)
        table = print_golden[table_key]
        # printed tables cover r = 0..13, a subset of the computed surface
        assert {int(r) for r in table} <= set(res.event_study_effects)
        for r_str, cols in table.items():
            r = int(r_str)
            att, _se = cols[column]  # printed SE halves retired (see docstring)
            eff = res.event_study_effects[r]
            np.testing.assert_allclose(eff["effect"], att, atol=PRINTED_ATOL)

    @pytest.mark.parametrize(
        "outcome",
        ["log_retail_emp", "log_wholesale_emp"],
        ids=["retail", "wholesale"],
    )
    @pytest.mark.parametrize("rolling,method", [("detrend", "reg")])
    def test_walmart_eventstudy_se_vs_stata(self, stata_golden, es_fit, rolling, method, outcome):
        """Bootstrap SEs vs the authors' Stata high-B multiplier bootstrap
        (RA config ONLY - the verified-equivalent scheme).

        Both sides are FIXED-rep Monte Carlo estimates of the same bootstrap
        SD, so the tolerance is the 4-sigma SE-of-SE bound
        ``4*sqrt(1/(2*B_py) + 1/(2*B_stata))`` (4-sigma because the bound is
        applied elementwise; at 3-sigma the family-wise chance of one MC
        excursion across all rows is ~40%). Any failure = STOP and
        investigate a scheme divergence; never widen this tolerance.

        The IPWRA configs are deliberately NOT gated here: measured
        2026-08-16, their bootstrap SEs diverge SYSTEMATICALLY from Stata's
        (~15% at row level, far beyond the MC bound) - the known SE-form
        difference (the contribution's IPWRA influence functions are
        AIPW-style, not the papers' E.3 stacked form that Stata implements).
        The Stata IPWRA SE columns stay in the golden as provenance; gating
        them awaits the E.3 IF-form adjudication on the PR #588 work list.
        """
        stata_method = {"reg": "ra", "dr": "ipwra"}[method]
        key = f"{rolling}_{stata_method}__{outcome}"
        table = stata_golden["walmart"][key]["watt"]
        r_stata = stata_golden["meta"]["bootstrap_reps"]
        rtol = 4 * np.sqrt(1 / (2 * 999) + 1 / (2 * r_stata))
        res = es_fit(rolling, method, outcome=outcome)
        for r in sorted(res.event_study_effects):
            cell = table.get(str(r))
            assert cell is not None and cell[1] is not None, f"{key} r={r} missing"
            np.testing.assert_allclose(
                res.event_study_effects[r]["se"], cell[1], rtol=rtol, err_msg=f"{key} r={r}"
            )

    def test_anchor_periods_excluded_from_raw_dict(self, es_fit):
        res_dm = es_fit("demean", "reg")
        assert -1 not in res_dm.event_study_effects
        res_dt = es_fit("detrend", "reg")
        assert -1 not in res_dt.event_study_effects
        assert -2 not in res_dt.event_study_effects

    def test_public_surface_emits_observed_anchors_as_reference(self, es_fit):
        res = es_fit("detrend", "reg")
        es = res.aggregate("event_study")
        ev = np.asarray(es.event_time)
        ref = np.asarray(es.is_reference)
        for anchor in (-2, -1):
            idx = np.nonzero(ev == anchor)[0]
            assert idx.size == 1, f"anchor {anchor} missing from public surface"
            assert bool(ref[idx[0]])
            np.testing.assert_allclose(np.asarray(es.att)[idx[0]], 0.0)

    def test_detrend_insample_residuals_sum_to_zero(self):
        """LW 2026 (pp20-21): per-unit detrended residuals sum to zero over
        the fitted pre-window - a property of OLS-with-intercept residuals
        IN SAMPLE. NOTE: this identity does NOT transfer to the reported
        staggered placebo coefficients (anchor-excluded, D.3-pooled,
        cohort-weighted contrasts) - do not assert a sum-to-zero on
        ``event_study_effects``; a correct implementation need not satisfy
        it there. Verified here on the reference transformation."""
        df = _synthetic_common_timing(t_max=8, s=5)
        for _, g in df.groupby("unit"):
            g = g.sort_values("time")
            pre = g[g["time"] <= 4]
            X = np.column_stack([np.ones(len(pre)), pre["time"].to_numpy(dtype=float)])
            beta, *_ = np.linalg.lstsq(X, pre["y"].to_numpy(dtype=float), rcond=None)
            resid = pre["y"].to_numpy(dtype=float) - X @ beta
            np.testing.assert_allclose(resid.sum(), 0.0, atol=1e-9)

    def test_simultaneous_band_metadata(self, es_fit):
        res = es_fit("detrend", "reg")
        assert res.cband_method is not None
        assert res.cband_n_bootstrap >= 999
        any_r = next(iter(res.event_study_effects))
        assert "cband_conf_int" in res.event_study_effects[any_r]


# ---------------------------------------------------------------------------
# 9. Full-precision Stata parity (authors' package, benchmarks/stata arm)
# ---------------------------------------------------------------------------


@pytest.mark.realdata
class TestStataParity:
    """Full-precision anchors vs benchmarks/data/lwdid_stata_golden.json.

    The golden is generated by benchmarks/stata/generate_lwdid_golden.do
    against the authors' SSC ``lwdid`` package (version pinned in its meta).
    All comparisons use PARITY_RTOL/PARITY_ATOL (see module constants).
    """

    def test_prop99_att_se(self, prop99, stata_golden):
        for rolling in ("demean", "detrend"):
            res = _fit_prop99(prop99, rolling)
            g = stata_golden["prop99"][rolling]
            np.testing.assert_allclose(res.att, g["att"], rtol=PARITY_RTOL, atol=PARITY_ATOL)
            np.testing.assert_allclose(res.se, g["se"], rtol=PARITY_RTOL, atol=PARITY_ATOL)

    def test_castle_att_se(self, castle, stata_golden):
        """Stata small-N staggered mode is never-treated-based by
        construction (no control option exists); the Python fits pass
        control_group='never_treated' accordingly - the golden meta records
        this equivalence."""
        for rolling in ("demean", "detrend"):
            res = _fit_castle(castle, rolling)
            g = stata_golden["castle"][rolling]
            np.testing.assert_allclose(res.att, g["att"], rtol=PARITY_RTOL, atol=PARITY_ATOL)
            np.testing.assert_allclose(res.se, g["se"], rtol=PARITY_RTOL, atol=PARITY_ATOL)

    def test_walmart_watt_points(self, stata_golden, es_fit):
        """Per-r WATT point parity at full precision, over the measured raw
        label set (any golden row absent from the raw dict must be
        anchor-or-nonfinite; a finite Stata value missing from our surface is
        a coverage hole, asserted in the label-set test)."""
        for key in WALMART_CONFIG_KEYS:
            rolling, method, outcome = _decode_walmart_key(key)
            res = es_fit(rolling, method, outcome=outcome)
            table = stata_golden["walmart"][key]["watt"]
            rtol = PARITY_RTOL if method == "reg" else IPWRA_PARITY_RTOL
            atol = PARITY_ATOL if method == "reg" else IPWRA_PARITY_ATOL
            for r in sorted(res.event_study_effects):
                cell = table.get(str(r))
                assert cell is not None and cell[0] is not None, f"{key} r={r} missing"
                np.testing.assert_allclose(
                    res.event_study_effects[r]["effect"],
                    cell[0],
                    rtol=rtol,
                    atol=atol,
                    err_msg=f"{key} r={r}",
                )

    def test_walmart_post_avg_convention(self, stata_golden, es_fit):
        """Stata's Post_avg equals the cell-mass (n_treated-weighted) average
        of the finite post cells - the convention pin behind the REGISTRY
        Aggregation note (verified to the last digit in the 2026-08-15
        smoke). Computed over finite-att cells with relative_time >= 0 (the
        container includes non-estimable NaN cells)."""
        for key in WALMART_CONFIG_KEYS:
            rolling, method, outcome = _decode_walmart_key(key)
            res = es_fit(rolling, method, outcome=outcome)
            cells = [
                v
                for v in res.cohort_time_effects.values()
                if v["relative_time"] >= 0 and np.isfinite(v["att"])
            ]
            att = np.array([v["att"] for v in cells])
            wt = np.array([v["n_treated"] for v in cells], dtype=float)
            post_avg = float(np.average(att, weights=wt))
            golden = stata_golden["walmart"][key]["overall"]["Post_avg"][0]
            rtol = PARITY_RTOL if method == "reg" else IPWRA_PARITY_RTOL
            np.testing.assert_allclose(post_avg, golden, rtol=rtol, atol=PARITY_ATOL, err_msg=key)


# ---------------------------------------------------------------------------
# 10. Common-timing aggregation surface + degenerate/bootstrap contracts
# ---------------------------------------------------------------------------


class TestCommonTimingAggregationSurface:
    """The guard relaxation covers event_study AND simple; group still raises."""

    @pytest.fixture(scope="class")
    def fitted(self):
        df = _synthetic_common_timing(t_max=8, s=5)
        return LWDiD(rolling="demean", estimation_method="reg", vcov_type="classical").fit(
            df, outcome="y", unit="unit", time="time", treatment="treat"
        )

    def test_simple_relays_the_fit(self, fitted):
        agg = fitted.aggregate("simple")
        df_out = agg.to_dataframe()
        np.testing.assert_allclose(df_out["att"].iloc[0], fitted.att, rtol=0, atol=0)
        np.testing.assert_allclose(df_out["se"].iloc[0], fitted.se, rtol=0, atol=0)

    def test_group_raises_on_common_timing(self, fitted):
        with pytest.raises(ValueError):
            fitted.aggregate("group")

    def test_event_study_bootstrap_regime(self):
        """Under n_bootstrap>0 the common-timing ES rows carry the bootstrap
        regime exactly like the staggered surface: the full quintet is
        finite and regime-consistent, and the band metadata is present."""
        df = _synthetic_common_timing(t_max=8, s=5)
        res = LWDiD(rolling="demean", estimation_method="reg", n_bootstrap=199, seed=42).fit(
            df, outcome="y", unit="unit", time="time", treatment="treat"
        )
        es = res.aggregate("event_study")
        ref = np.asarray(es.is_reference)
        for arr in (es.att, es.se, es.t_stat, es.p_value, es.conf_int_lower, es.conf_int_upper):
            vals = np.asarray(arr, dtype=float)[~ref]
            assert np.isfinite(vals).all()
        assert res.cband_method is not None

    def test_degenerate_fit_follows_house_empty_contract(self):
        """A fit with no finite effects (single-pre-period detrend) yields
        the house requested-but-empty event-study surface: zero
        non-reference rows, any anchor row only if genuinely observed - and
        never NaN non-reference rows or a ValueError."""
        df = TestMinimumPrePeriods._panel(first_period_treated=2)
        with pytest.warns(UserWarning):
            res = LWDiD(rolling="detrend", estimation_method="reg", vcov_type="classical").fit(
                df, outcome="y", unit="unit", time="time", treatment="treat"
            )
        es = res.aggregate("event_study")
        ref = np.asarray(es.is_reference, dtype=bool)
        assert (~ref).sum() == 0
        # single pre-period: the detrend anchor r=-2 is NOT observed and
        # must not be synthesized
        ev = set(int(e) for e in np.asarray(es.event_time))
        assert -2 not in ev


# ---------------------------------------------------------------------------
# 11. Shared input-validation contracts (every path)
# ---------------------------------------------------------------------------


class TestSharedValidationContracts:
    """Unit-constancy and time-family contracts enforced in shared fit()
    validation for every LWDiD path (common-timing AND staggered)."""

    @staticmethod
    def _panel_and_kwargs(mode):
        """(df, fit_kwargs, extra_init) for each design path."""
        if mode == "common":
            df = _synthetic_common_timing(t_max=6, s=4)
            kw = dict(outcome="y", unit="unit", time="time", treatment="treat")
            extra = {}
        else:
            df = _synthetic_staggered()
            kw = dict(
                outcome="y", unit="unit", time="time", treatment="treat", first_treat="first_year"
            )
            extra = dict(control_group="never_treated")
        return df, kw, extra

    @pytest.mark.parametrize("mode", ["common", "staggered"])
    def test_time_varying_covariate_rejected(self, mode):
        df, kw, extra = self._panel_and_kwargs(mode)
        rng = np.random.default_rng(5)
        df["xt"] = rng.normal(size=len(df))  # time-varying within unit
        with pytest.raises(ValueError):
            LWDiD(rolling="demean", estimation_method="reg", **extra).fit(
                df, covariates=["xt"], **kw
            )

    @pytest.mark.parametrize("mode", ["common", "staggered"])
    def test_time_varying_cluster_rejected(self, mode):
        df, kw, extra = self._panel_and_kwargs(mode)
        rng = np.random.default_rng(6)
        df["cl"] = rng.integers(0, 5, size=len(df))  # time-varying within unit
        with pytest.raises(ValueError):
            LWDiD(rolling="demean", estimation_method="reg", cluster="cl", **extra).fit(df, **kw)

    @pytest.mark.parametrize("mode", ["common", "staggered"])
    def test_row_order_invariance(self, mode):
        """Shuffling row order within units leaves att/se identical (with
        unit-CONSTANT covariates; the time-varying case is covered by the
        rejection tests above, since post-fix it raises)."""
        if mode == "common":
            df = _synthetic_common_timing(t_max=6, s=4)
            kw = dict(outcome="y", unit="unit", time="time", treatment="treat", covariates=["x"])
            est = dict(rolling="demean", estimation_method="reg", vcov_type="hc1")
        else:
            df = _synthetic_staggered()
            # unit-constant covariate and cluster so both selection paths are
            # exercised under reordering (time-varying cases raise, above)
            units = df["unit"].unique()
            rng = np.random.default_rng(41)
            xmap = dict(zip(units, rng.normal(size=len(units))))
            df["xu"] = df["unit"].map(xmap)
            kw = dict(
                outcome="y",
                unit="unit",
                time="time",
                treatment="treat",
                first_treat="first_year",
                covariates=["xu"],
            )
            # cluster selection under reordering is covered by the
            # clustered-inference oracle + the time-varying rejection above;
            # keeping cluster= out here keeps this invariance lane executable
            # on the pre-rename head too.
            est = dict(
                rolling="demean",
                estimation_method="reg",
                vcov_type="hc1",
                control_group="never_treated",
            )
        shuffled = df.sample(frac=1.0, random_state=99).reset_index(drop=True)
        r1 = LWDiD(**est).fit(df, **kw)
        r2 = LWDiD(**est).fit(shuffled, **kw)
        np.testing.assert_allclose(r1.att, r2.att, rtol=0, atol=1e-12)
        np.testing.assert_allclose(r1.se, r2.se, rtol=0, atol=1e-12)

    @pytest.mark.parametrize(
        "direction", ["datetime_time_period_cohort", "period_time_datetime_cohort"]
    )
    def test_mixed_time_families_rejected(self, direction):
        """Mixed datetime/Period time families raise the estimator's
        documented ValueError, not an internal pandas TypeError (both
        directions pass the boolean date-like check today)."""
        periods = pd.date_range("2020-01-01", periods=6, freq="YS")
        rows = []
        for unit, cohort_i in [("t1", 2), ("t2", 2), ("c1", None), ("c2", None)]:
            for i, p in enumerate(periods):
                treat = int(cohort_i is not None and i >= cohort_i)
                rows.append({"unit": unit, "i": i, "time": p, "treat": treat, "y": float(i)})
        df = pd.DataFrame(rows)
        if direction == "datetime_time_period_cohort":
            df["cohort"] = df["unit"].map(
                {"t1": pd.Period("2022", freq="Y"), "t2": pd.Period("2022", freq="Y")}
            )
        else:
            df["time"] = df["time"].dt.to_period("Y")
            df["cohort"] = df["unit"].map(
                {"t1": pd.Timestamp("2022-01-01"), "t2": pd.Timestamp("2022-01-01")}
            )
        with pytest.raises(ValueError):
            LWDiD(rolling="demean", estimation_method="reg", control_group="never_treated").fit(
                df, outcome="y", unit="unit", time="time", treatment="treat", first_treat="cohort"
            )

    def test_dr_without_covariates_warns_and_equals_reg(self):
        """no-silent-failures: a dr fit with no covariates degrades to reg
        and must SAY so (the head's IPWRA branch is silent against its own
        routing docstring; ipw and psm already warn). Warning contract per
        CONTRIBUTING: message assertion + behavioral assertion."""
        df = _synthetic_common_timing(t_max=6, s=4)
        kw = dict(outcome="y", unit="unit", time="time", treatment="treat")
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            r_dr = LWDiD(rolling="demean", estimation_method="dr").fit(df, **kw)
        assert any(
            any(s in str(w.message).lower() for s in ("covariate", "control", "fall"))
            for w in caught
        ), "dr-without-covariates fallback must warn"
        r_reg = LWDiD(rolling="demean", estimation_method="reg").fit(df, **kw)
        np.testing.assert_allclose(r_dr.att, r_reg.att, rtol=0, atol=1e-12)
        np.testing.assert_allclose(r_dr.se, r_reg.se, rtol=0, atol=1e-12)

    def test_ipw_without_covariates_warns(self):
        """The ipw branch already warns at the head (expected-pass lane)."""
        df = _synthetic_common_timing(t_max=6, s=4)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            LWDiD(rolling="demean", estimation_method="ipw").fit(
                df, outcome="y", unit="unit", time="time", treatment="treat"
            )
        assert any(
            any(s in str(w.message).lower() for s in ("covariate", "control", "fall"))
            for w in caught
        )


# ---------------------------------------------------------------------------
# 12. Sensitivity module contracts
# ---------------------------------------------------------------------------


class TestSensitivityContracts:
    """lwdid_sensitivity failure contracts + rename sweep."""

    @staticmethod
    def _df():
        return _synthetic_common_timing(n_treat=20, n_control=30, t_max=8, s=5, effect=0.0)

    def test_zero_baseline_is_not_estimable(self):
        """A near-zero baseline ATT must classify as not_estimable with NaN
        ratio, never highly_robust (the relative ratio is undefined)."""
        from diff_diff.lwdid_sensitivity import robustness_pre_periods

        df = self._df()
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            r = robustness_pre_periods(df, outcome="y", unit="unit", time="time", treatment="treat")
        if abs(getattr(r, "baseline_att", 1.0)) < 1e-10:
            assert r.robustness_level == "not_estimable"
            assert np.isnan(r.sensitivity_ratio)
        else:
            # zero-effect DGP but baseline not exactly ~0: exercise the
            # classifier directly on a forced zero baseline
            from diff_diff.lwdid_sensitivity import _compute_sensitivity_ratio

            ratio = _compute_sensitivity_ratio(0.0, [0.0, 1.0, -1.0])
            assert np.isnan(ratio)

    def test_missing_column_propagates(self):
        """A missing-column programming error must PROPAGATE as ValueError,
        not be converted into a silently failed specification (narrowed
        except contract)."""
        from diff_diff.lwdid_sensitivity import robustness_pre_periods

        with pytest.raises(ValueError):
            robustness_pre_periods(
                self._df(), outcome="missing_outcome", unit="unit", time="time", treatment="treat"
            )

    def test_public_entry_points_use_canonical_kwargs(self):
        """The sensitivity API carries the post-rename vocabulary; the old
        kwargs are rejected."""
        import inspect

        from diff_diff.lwdid_sensitivity import robustness_pre_periods, sensitivity_no_anticipation

        for fn in (robustness_pre_periods, sensitivity_no_anticipation):
            params = inspect.signature(fn).parameters
            assert "estimation_method" in params, fn.__name__
            assert "estimator" not in params, fn.__name__
            assert "vce" not in params, fn.__name__

    def test_specification_result_serializes_canonical_key(self):
        from diff_diff.lwdid_sensitivity import robustness_pre_periods

        df = _synthetic_common_timing(n_treat=20, n_control=30, t_max=8, s=5)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            r = robustness_pre_periods(df, outcome="y", unit="unit", time="time", treatment="treat")
        payload = json.dumps(r.to_dict()) if hasattr(r, "to_dict") else "{}"
        assert '"estimator"' not in payload
        assert '"vce"' not in payload


# ---------------------------------------------------------------------------
# 13. Retired pre-release surfaces (negative assertions)
# ---------------------------------------------------------------------------


class TestRetiredSurfaces:
    """The locked pre-release renames/removals, enforced.

    Versioning rationale: NO deprecation shims or ledger rows - LWDiD has
    never shipped on main, so these are pre-release renames, not breaking
    changes (see the REGISTRY validation-suite note).
    """

    @staticmethod
    def _small_fit(**kwargs):
        df = _synthetic_common_timing(n_treat=10, n_control=15, t_max=6, s=4)
        est = LWDiD(rolling="demean", estimation_method="reg", **kwargs)
        return est.fit(df, outcome="y", unit="unit", time="time", treatment="treat")

    def test_lw_alias_gone(self):
        import diff_diff

        assert not hasattr(diff_diff, "LW")
        assert "LW" not in diff_diff.__all__

    def test_canonical_export(self):
        import diff_diff

        assert "LWDiD" in diff_diff.__all__

    def test_module_level_wrapper_gone(self):
        mod = importlib.import_module("diff_diff.lwdid")
        assert not hasattr(mod, "lwdid")

    def test_trend_diagnostics_module_deleted(self):
        with pytest.raises(ModuleNotFoundError):
            importlib.import_module("diff_diff.lwdid_trend_diagnostics")

    def test_retired_result_fields_gone(self):
        res = self._small_fit()
        assert not hasattr(res, "overall_att")
        assert not hasattr(res, "period_effects")
        payload = res.to_dict()
        assert "overall_att" not in payload
        assert "period_effects" not in payload

    def test_result_field_mirrors_renamed(self):
        res = self._small_fit()
        assert not hasattr(res, "estimator") or res.estimator == "LWDiD"  # house NAME field only
        assert not hasattr(res, "vce_type")
        assert res.estimation_method == "reg"
        assert res.vcov_type == "hc1" or res.vcov_type == "classical"
        d = res.to_dict()
        assert "estimation_method" in d and "vcov_type" in d
        assert "vce_type" not in d
        frame_cols_or_payload = json.dumps(d)
        assert '"vce_type"' not in frame_cols_or_payload
        text = res.summary() or ""
        rep = repr(res)
        for banned in ("Estimator:", "estimator=", "vce="):
            assert banned not in text
            assert banned not in rep
        assert "estimation_method" in rep or "reg" in text

    def test_psm_routes(self):
        """psm actually routes (with covariates - the covariate-free PSM
        branch falls back to reg) and differs from reg on the same data."""
        df = _synthetic_common_timing(t_max=6, s=4)
        kw = dict(outcome="y", unit="unit", time="time", treatment="treat", covariates=["x"])
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            r_psm = LWDiD(rolling="demean", estimation_method="psm").fit(df, **kw)
            r_reg = LWDiD(rolling="demean", estimation_method="reg").fit(df, **kw)
        assert np.isfinite(r_psm.att)
        assert r_psm.estimation_method == "psm"
        assert abs(r_psm.att - r_reg.att) > 1e-12

    def test_legacy_values_rejected(self):
        for legacy in ("ra", "ipwra"):
            with pytest.raises(ValueError):
                LWDiD(estimation_method=legacy)

    def test_legacy_kwargs_rejected(self):
        for kwargs in (
            {"estimator": "ra"},
            {"vce": "hc1"},
            {"bootstrap_seed": 42},
            {"period_specific": True},
            {"trim_threshold": 0.05},
        ):
            with pytest.raises(TypeError):
                LWDiD(**kwargs)

    def test_cluster_placement(self):
        """cluster= lives on the constructor (CS/LPDiD placement); fit()
        rejects it."""
        LWDiD(cluster="cl")  # accepted
        df = _synthetic_common_timing(t_max=6, s=4)
        with pytest.raises(TypeError):
            LWDiD(rolling="demean", estimation_method="reg").fit(
                df, outcome="y", unit="unit", time="time", treatment="treat", cluster="unit"
            )

    def test_post_rename_defaults(self):
        params = LWDiD().get_params()
        assert params["seed"] is None
        assert params["estimation_method"] == "reg"
        assert params["vcov_type"] == "hc1"
        assert params["pscore_trim"] == 0.01

    def test_vcov_cluster_value_retired(self):
        """The 'cluster' MODE value is retired AT THE CONSTRUCTOR (clustering
        activates via the cluster= param); a fit-time probe would pass at the
        pre-rename head for the wrong reason."""
        with pytest.raises(ValueError, match="cluster"):
            LWDiD(vcov_type="cluster")

    def test_cluster_param_produces_clustered_inference(self):
        """Behavioral oracle: with induced within-cluster correlation the
        clustered SE differs from the unclustered hc1 SE (metadata alone
        would pass a silent-HC1 implementation), and the house
        cluster-metadata contract is honored."""
        rng = np.random.default_rng(17)
        # cluster-level POST-period shocks: a unit-level or time-invariant
        # shock is removed by the pre-period demeaning, leaving nothing for
        # clustering to pick up - the collapsed outcomes must be genuinely
        # correlated WITHIN clusters for this oracle to bite.
        cluster_post_shock = {c: rng.normal(0, 1.5) for c in range(10)}
        rows = []
        for i in range(80):
            cl = i // 8  # 10 clusters
            is_treated = i < 30
            for t in range(1, 7):
                post = t >= 4
                y = (
                    (cluster_post_shock[cl] if post else 0.0)
                    + rng.normal(0, 0.4)
                    + (1.0 if is_treated and post else 0.0)
                )
                rows.append(
                    {"unit": i, "cl": cl, "time": t, "y": y, "treat": int(is_treated and post)}
                )
        df = pd.DataFrame(rows)
        r_cl = LWDiD(rolling="demean", estimation_method="reg", cluster="cl").fit(
            df, outcome="y", unit="unit", time="time", treatment="treat"
        )
        r_un = LWDiD(rolling="demean", estimation_method="reg", vcov_type="hc1").fit(
            df, outcome="y", unit="unit", time="time", treatment="treat"
        )
        assert r_cl.cluster_name == "cl"
        assert r_cl.n_clusters == 10
        # strong within-cluster correlation must MATERIALLY widen the SE,
        # not merely change it (a silent-HC1 implementation with metadata
        # would fail here; measured ratio ~2.7 on this fixture)
        assert r_cl.se > 1.15 * r_un.se, (r_cl.se, r_un.se)
        # ... and the value itself must equal the CR1 sandwich on the
        # collapsed cross-section, small-sample factor G/(G-1)*(N-1)/(N-K)
        # (verified identical to the contribution head's clustered path)
        ybar = _demean_reference(df, "unit", "time", "y", pre_end=3)
        d = df.groupby("unit")["treat"].max().loc[ybar.index].to_numpy(dtype=float)
        cl_ids = df.groupby("unit")["cl"].first().loc[ybar.index].to_numpy()
        y = ybar.to_numpy(dtype=float)
        X = np.column_stack([np.ones_like(d), d])
        beta, *_ = np.linalg.lstsq(X, y, rcond=None)
        e = y - X @ beta
        n_units, k = X.shape
        n_cl = len(np.unique(cl_ids))
        bread = np.linalg.inv(X.T @ X)
        meat = np.zeros((k, k))
        for g_id in np.unique(cl_ids):
            m = cl_ids == g_id
            s = X[m].T @ e[m]
            meat += np.outer(s, s)
        factor = (n_cl / (n_cl - 1)) * ((n_units - 1) / (n_units - k))
        se_cr1 = float(np.sqrt((factor * bread @ meat @ bread)[1, 1]))
        np.testing.assert_allclose(r_cl.se, se_cr1, rtol=1e-10)

    def test_pscore_trim_affects_behavior(self):
        """set_params(pscore_trim=...) actually changes an ipw fit (the
        generic roster's mutation lane picks alpha, so nothing else
        exercises this parameter)."""
        df = _synthetic_common_timing(t_max=6, s=4)
        kw = dict(outcome="y", unit="unit", time="time", treatment="treat", covariates=["x"])
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            r1 = LWDiD(rolling="demean", estimation_method="ipw").fit(df, **kw)
            est = LWDiD(rolling="demean", estimation_method="ipw")
            est.set_params(pscore_trim=0.4)
            r2 = est.fit(df, **kw)
        assert abs(r1.att - r2.att) > 0 or abs(r1.se - r2.se) > 0


# ---------------------------------------------------------------------------
# 14. Monte Carlo bias ordering (LW 2026, Section 5)
# ---------------------------------------------------------------------------


@pytest.mark.slow
class TestMonteCarloBiasOrdering:
    """Under the paper's heterogeneous-trend DGP (Table 1, Scenario 1),
    demeaning is badly biased while detrending is nearly unbiased
    (Table 2: bias 1.914 vs 0.009)."""

    N, T, S = 20, 20, 11
    LAMBDAS = np.array(
        [0, 0, 0, 0, 0.2, 0.6, 0.7, 0.8, 0.6, 0.9, 0.9, 1, 1.1, 1.3, 1.2, 1.5, 0.6, 1.4, 1.8, 1.9]
    )
    DELTAS = np.array([1, 2, 3, 3, 3, 2, 2, 2, 1, 1], dtype=float)

    def _one_rep(self, rng):
        n, t_max, s = self.N, self.T, self.S
        c = rng.normal(0, 2, n)
        g = rng.normal(1, 1, n)
        a0, a1, a2 = -1.0, -1.0 / 3.0, 0.25
        d = (a0 - a1 * c + a2 * g + rng.logistic(0, 1, n) > 0).astype(int)
        if d.sum() in (0, n):  # degenerate assignment; caller redraws
            return None
        u = np.zeros((n, t_max))
        u[:, 0] = rng.normal(0, np.sqrt(2 / (1 - 0.75**2)), n)
        for t in range(1, t_max):
            u[:, t] = 0.75 * u[:, t - 1] + rng.normal(0, np.sqrt(2), n)
        ts = np.arange(1, t_max + 1)
        y0 = self.LAMBDAS[None, :] - c[:, None] + g[:, None] * ts[None, :] + u
        y = y0.copy()
        post = ts >= s
        delta_full = np.zeros(t_max)
        delta_full[s - 1 :] = self.DELTAS
        y[d == 1] = y0[d == 1] + delta_full[None, :] + rng.normal(0, np.sqrt(2), (d.sum(), t_max))
        sample_att = delta_full[post].mean()
        df = pd.DataFrame(
            {
                "unit": np.repeat(np.arange(n), t_max),
                "time": np.tile(ts, n),
                "y": y.ravel(),
                "treat": (np.repeat(d, t_max) * np.tile(post.astype(int), n)),
            }
        )
        out = {}
        for rolling in ("demean", "detrend"):
            res = LWDiD(rolling=rolling, estimation_method="reg", vcov_type="classical").fit(
                df, outcome="y", unit="unit", time="time", treatment="treat"
            )
            out[rolling] = res.att - sample_att
        return out

    def test_bias_ordering_under_heterogeneous_trends(self):
        rng = np.random.default_rng(20260713)
        errs = {"demean": [], "detrend": []}
        reps = 0
        while reps < 200:
            rep = self._one_rep(rng)
            if rep is None:
                continue
            errs["demean"].append(rep["demean"])
            errs["detrend"].append(rep["detrend"])
            reps += 1
        bias_dm = abs(float(np.mean(errs["demean"])))
        bias_dt = abs(float(np.mean(errs["detrend"])))
        assert bias_dt < 0.5, f"detrending bias {bias_dt:.3f} unexpectedly large"
        assert bias_dm > 3 * max(
            bias_dt, 0.15
        ), f"bias ordering violated: demean {bias_dm:.3f} vs detrend {bias_dt:.3f}"


# ---------------------------------------------------------------------------
# 15. Minimum pre-treatment periods (REGISTRY edge case)
# ---------------------------------------------------------------------------


class TestMinimumPrePeriods:
    """Demeaning requires >= 1 pre-period; detrending >= 2 (rank condition,
    LW 2025 Appendix B)."""

    @staticmethod
    def _panel(first_period_treated):
        rng = np.random.default_rng(3)
        rows = []
        for i in range(30):
            treated = i < 10
            for t in range(1, 6):
                post = t >= first_period_treated
                rows.append(
                    {
                        "unit": i,
                        "time": t,
                        "y": rng.normal(0, 1) + (0.5 if treated and post else 0),
                        "treat": int(treated and post),
                    }
                )
        return pd.DataFrame(rows)

    def test_demeaning_with_single_pre_period_works(self):
        df = self._panel(first_period_treated=2)  # exactly one pre-period
        res = LWDiD(rolling="demean", estimation_method="reg", vcov_type="classical").fit(
            df, outcome="y", unit="unit", time="time", treatment="treat"
        )
        assert np.isfinite(res.att)

    def test_detrending_with_single_pre_period_warns_and_nans(self):
        """One pre-period is rank-deficient for detrending. Calibrated
        behavior (2026-07-13): the implementation warns per unit and returns
        NaN inference - loud, house-compatible (warn + NaN, never silent)."""
        df = self._panel(first_period_treated=2)  # one pre-period: rank-deficient
        with pytest.warns(UserWarning, match="at least 2 pre-treatment periods"):
            res = LWDiD(rolling="detrend", estimation_method="reg", vcov_type="classical").fit(
                df, outcome="y", unit="unit", time="time", treatment="treat"
            )
        assert np.isnan(res.att)
        assert np.isnan(res.se)
        # The FULL inference tuple must be NaN together (house NaN contract)
        assert np.isnan(res.t_stat)
        assert np.isnan(res.p_value)
        assert np.isnan(res.conf_int[0]) and np.isnan(res.conf_int[1])

    def test_detrending_with_two_pre_periods_works(self):
        df = self._panel(first_period_treated=3)  # two pre-periods: minimum
        res = LWDiD(rolling="detrend", estimation_method="reg", vcov_type="classical").fit(
            df, outcome="y", unit="unit", time="time", treatment="treat"
        )
        assert np.isfinite(res.att)


# ---------------------------------------------------------------------------
# Fix-wave WS1: complete-case fixed-weight tau_omega (campaign findings:
# 0.0-injection for controls missing a cohort's post window; silent
# treated-side reweighting through the finite mask; composite gate applying
# the NON-seasonal transform to demeanq/detrendq overall ATTs)
# ---------------------------------------------------------------------------


def _synthetic_drops_staggered(seed=42):
    """Deterministic unbalanced panel with GENUINE complete-case drops.

    Cohorts {3, 5} over t=1..6. One control unit observes only t=1..4
    (missing cohort-5's entire post window -> dropped from the composite
    control side) and one cohort-5 treated unit observes only t=1..4
    (missing its OWN post window -> dropped from the treated side, with the
    cohort masses recomputed on the survivors).
    """
    rng = np.random.default_rng(seed)
    rows = []
    uid = 0
    spec = [(0, 40, None), (0, 1, (1, 2, 3, 4)), (3, 20, None), (5, 14, None), (5, 1, (1, 2, 3, 4))]
    for g, n, keep in spec:
        for _ in range(n):
            alpha = rng.normal()
            for t in range(1, 7):
                if keep is not None and t not in keep:
                    continue
                d = int(g > 0 and t >= g)
                y = alpha + 0.2 * t + rng.normal(scale=0.4) + (1.5 + 0.4 * (g == 5)) * d
                rows.append(dict(unit=uid, time=t, first=g, treat=d, y=y))
            uid += 1
    return pd.DataFrame(rows)


def _complete_case_tau_omega_reference(df):
    """From-scratch complete-case fixed-weight tau_omega (demean).

    Fixed cohort weights omega_g = N_g / N_treat defined on the ESTIMATION
    sample: treated units without a finite own-cohort post average are
    dropped and the masses recomputed; control units must observe every
    surviving-weight cohort's post window.
    """
    fy = df.groupby("unit")["first"].first()
    cohorts = sorted(set(fy[fy > 0]))
    ydot = {}
    for g in cohorts:
        pre_mean = df.loc[df["time"] < g].groupby("unit")["y"].mean()
        post = df.loc[df["time"] >= g].copy()
        post["_ydot"] = post["y"] - post["unit"].map(pre_mean)
        ydot[g] = post.groupby("unit")["_ydot"].mean()
    surviving_treated = [
        u for u in fy.index if fy[u] > 0 and np.isfinite(ydot[fy[u]].get(u, np.nan))
    ]
    fy_cc = fy.loc[surviving_treated]
    sizes = {g: int((fy_cc == g).sum()) for g in cohorts}
    weighted = [g for g in cohorts if sizes[g] > 0]
    n_treat_cc = len(surviving_treated)
    controls = [
        u
        for u in fy.index
        if not fy[u] > 0 and all(np.isfinite(ydot[g].get(u, np.nan)) for g in weighted)
    ]
    y, d = [], []
    for u in surviving_treated:
        y.append(float(ydot[fy[u]][u]))
        d.append(1.0)
    for u in controls:
        y.append(sum(sizes[g] / n_treat_cc * float(ydot[g][u]) for g in weighted))
        d.append(0.0)
    y_arr, d_arr = np.asarray(y), np.asarray(d)
    return float(y_arr[d_arr == 1].mean() - y_arr[d_arr == 0].mean())


class TestTauOmegaCompleteCase:
    """WS1: fixed-weight complete-case tau_omega with vcov-invariant routing."""

    KW = dict(outcome="y", unit="unit", time="time", treatment="treat", first_treat="first")

    def _fit(self, df, **overrides):
        params = dict(
            rolling="demean",
            estimation_method="reg",
            vcov_type="classical",
            control_group="never_treated",
        )
        params.update(overrides)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            return LWDiD(**params).fit(df, **self.KW)

    def test_two_sided_complete_case_oracle(self):
        # Independent arithmetic oracle exercising BOTH a dropped treated
        # unit AND a dropped control unit (the route-consistency test
        # cannot see a wrong weighting: both routes share the composite).
        df = _synthetic_drops_staggered()
        res = self._fit(df)
        assert res.n_composite_treated_dropped == 1
        assert res.n_composite_controls_dropped == 1
        expected = _complete_case_tau_omega_reference(df)
        np.testing.assert_allclose(res.att_tau_omega_complete_case, expected, atol=1e-10, rtol=0)

    def test_drops_route_reports_if_weighted_point_with_warning(self):
        df = _synthetic_drops_staggered()
        with pytest.warns(UserWarning, match="complete-case"):
            res = LWDiD(
                rolling="demean",
                estimation_method="reg",
                vcov_type="classical",
                control_group="never_treated",
            ).fit(df, **self.KW)
        # .att equals the cohort-mass IF-weighted point on the drops route
        expected = sum(v["weight"] * v["att"] for v in res.cohort_effects.values())
        np.testing.assert_allclose(res.att, expected, atol=1e-10, rtol=0)
        assert res.inference_basis == "joint_influence_function"
        assert np.isfinite(res.se) and res.se > 0

    def test_vcov_invariance_with_drops(self):
        # Pre-fix hazard class: a variance selection moving the point.
        df = _synthetic_drops_staggered()
        atts = [self._fit(df, vcov_type=v).att for v in ("classical", "hc1")]
        np.testing.assert_allclose(atts[0], atts[1], atol=1e-10, rtol=0)

    def test_zero_drop_panel_keeps_status_quo_metadata(self):
        df = _synthetic_unbalanced_staggered()  # unbalanced but zero drops
        res = self._fit(df)
        assert res.n_composite_treated_dropped == 0
        assert res.n_composite_controls_dropped == 0
        assert res.att_tau_omega_complete_case is None
        assert res.inference_basis == "composite_regression"

    def test_classical_if_se_concords_with_unit_bootstrap(self, ci_params):
        # With drops, classical pairs the IF point with the IF SE; pin the
        # pair against an external unit-resampling bootstrap.
        df = _synthetic_drops_staggered()
        res = self._fit(df)
        rng = np.random.default_rng(42)
        units = df["unit"].unique()
        n_boot = ci_params.bootstrap(300, min_n=199)
        draws = []
        for _ in range(n_boot):
            picks = rng.choice(units, size=len(units), replace=True)
            frames = []
            for j, u in enumerate(picks):
                block = df.loc[df["unit"] == u].copy()
                block["unit"] = j
                frames.append(block)
            bs = pd.concat(frames, ignore_index=True)
            try:
                draws.append(self._fit(bs).att)
            except ValueError:
                continue
        boot_se = float(np.std([v for v in draws if np.isfinite(v)], ddof=1))
        threshold = 0.40 if n_boot < 100 else 0.15
        assert abs(res.se - boot_se) / boot_se < threshold, (res.se, boot_se)


class TestSeasonalOverallRouting:
    """WS1 gate coherence: demeanq/detrendq never enter the tau_omega
    composite (which is defined for the plain transforms only). Pre-fix,
    vcov_type='classical' silently swapped the NON-seasonal transform into
    the staggered q-mode overall ATT (~8% shift on seasonal DGPs) while
    hc1 aggregated seasonal cohort ATTs - a vcov selection moved the point.
    """

    KW = dict(outcome="y", unit="unit", time="time", treatment="treat", first_treat="first")

    @staticmethod
    def _quarterly_panel(seed=3):
        rng = np.random.default_rng(seed)
        rows = []
        uid = 0
        season = np.array([1.2, -0.6, 0.9, -1.5])
        for g, n in [(0, 30), (9, 12), (11, 10)]:
            for _ in range(n):
                alpha = rng.normal()
                amp = rng.uniform(0.5, 1.5)
                for t in range(1, 17):
                    d = int(g > 0 and t >= g)
                    y = (
                        alpha
                        + amp * season[(t - 1) % 4]
                        + 0.1 * t
                        + rng.normal(scale=0.3)
                        + 1.5 * d
                    )
                    rows.append(dict(unit=uid, time=t, first=g, treat=d, y=y))
                uid += 1
        return pd.DataFrame(rows)

    def _fit(self, df, **overrides):
        params = dict(
            rolling="demeanq",
            estimation_method="reg",
            vcov_type="classical",
            control_group="never_treated",
        )
        params.update(overrides)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            return LWDiD(**params).fit(df, **self.KW)

    def test_qmode_overall_is_seasonal_cohort_mass_average(self):
        df = self._quarterly_panel()
        res = self._fit(df)
        expected = sum(v["weight"] * v["att"] for v in res.cohort_effects.values())
        np.testing.assert_allclose(res.att, expected, atol=1e-10, rtol=0)
        assert res.inference_basis == "joint_influence_function"

    def test_qmode_vcov_never_moves_the_point(self):
        df = self._quarterly_panel()
        atts = [self._fit(df, vcov_type=v).att for v in ("classical", "hc1")]
        np.testing.assert_allclose(atts[0], atts[1], atol=1e-12, rtol=0)

    def test_qmode_differs_from_plain_demean_on_seasonal_dgp(self):
        # The seasonal adjustment must actually matter on this DGP -
        # guards against the fix regressing into a silent transform swap.
        df = self._quarterly_panel()
        att_q = self._fit(df).att
        att_plain = self._fit(df, rolling="demean").att
        assert abs(att_q - att_plain) > 1e-6

    def test_composite_raises_if_q_variant_reaches_it(self):
        df = self._quarterly_panel()
        est = LWDiD(rolling="demeanq", estimation_method="reg")
        with pytest.raises(ValueError, match="only defined for rolling"):
            est._composite_regression_aggregation(df, "y", "unit", "time", "first")


# ---------------------------------------------------------------------------
# Fix-wave WS6: vcov contract + per-surface reference-distribution policy
# ---------------------------------------------------------------------------


class TestInferenceDispatchPolicy:
    """Campaign finding: identical single-cohort designs produced p-values
    differing by ~34 orders of magnitude depending on whether first_treat
    was passed (t vs normal dispatch). Policy now: an aggregate composed of
    EXACTLY ONE cell uses that cell's residual df (the common-timing rule);
    multi-cell aggregates keep the large-sample reference; clustered
    aggregates use G-1 over CONTRIBUTING clusters.
    """

    @staticmethod
    def _single_post_panel(seed=17):
        # T_post = 1: the staggered fit has exactly one estimable cell.
        rng = np.random.default_rng(seed)
        rows = []
        for u in range(24):
            alpha = rng.normal()
            treated = u < 10
            for t in range(1, 6):
                d = int(treated and t >= 5)
                y = alpha + 0.1 * t + rng.normal(scale=0.4) + 1.4 * d
                rows.append(dict(unit=u, time=t, first=5 if treated else 0, treat=d, y=y))
        return pd.DataFrame(rows)

    def test_single_post_period_staggered_matches_common_timing(self):
        df = self._single_post_panel()
        kw_common = dict(outcome="y", unit="unit", time="time", treatment="treat")
        est = dict(rolling="demean", estimation_method="reg", vcov_type="hc1")
        rc = LWDiD(**est).fit(df, **kw_common)
        rs = LWDiD(**est).fit(df, first_treat="first", **kw_common)
        np.testing.assert_allclose(rs.att, rc.att, rtol=1e-10)
        np.testing.assert_allclose(rs.se, rc.se, rtol=1e-10)
        assert rs.df_inference == rc.df_inference  # same residual t reference
        np.testing.assert_allclose(rs.p_value, rc.p_value, rtol=1e-8)

    def test_cell_with_single_cluster_fails_closed_and_propagates(self):
        # Cluster ids are re-derived per cell; a cell whose units share one
        # cluster must NaN its inference (point retained) and any aggregate
        # including it inherits NaN inference - deliberate fail-closed.
        rng = np.random.default_rng(23)
        rows = []
        uid = 0
        # cohort-4 treated units all in cluster 0; controls span clusters
        for g, n, cl_fn in [(0, 12, lambda u: 1 + (u % 4)), (4, 6, lambda u: 0)]:
            for _ in range(n):
                alpha = rng.normal()
                for t in range(1, 7):
                    d = int(g > 0 and t >= g)
                    y = alpha + rng.normal(scale=0.4) + 1.2 * d
                    rows.append(dict(unit=uid, time=t, first=g, treat=d, y=y, cl=cl_fn(uid)))
                uid += 1
        df = pd.DataFrame(rows)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            res = LWDiD(
                rolling="demean",
                estimation_method="reg",
                cluster="cl",
                control_group="never_treated",
            ).fit(df, outcome="y", unit="unit", time="time", treatment="treat", first_treat="first")
        # Cells contain treated (cluster 0) + controls (clusters 1-4): G=5
        # per cell, so this design is NOT degenerate; flip to a truly
        # degenerate one below.
        assert np.isfinite(res.att)
        del caught

    def test_degenerate_single_cluster_cells_nan_inference(self):
        rng = np.random.default_rng(29)
        rows = []
        uid = 0
        # EVERY unit in one cluster: per-cell G=1 while a second, empty
        # cluster never contributes -> global guard passes via a control
        # unit parked alone in cluster 1 with NaN-free data but the cells
        # all draw from cluster 0.
        for g, n in [(0, 10), (4, 5)]:
            for _ in range(n):
                alpha = rng.normal()
                for t in range(1, 7):
                    d = int(g > 0 and t >= g)
                    y = alpha + rng.normal(scale=0.4) + 1.2 * d
                    rows.append(dict(unit=uid, time=t, first=g, treat=d, y=y, cl=0))
                uid += 1
        # one extra never-treated unit in its own cluster, excluded from
        # cells by control_group='never_treated'? No - it IS a control.
        # Give it data only in pre-periods so it drops from post cells.
        for t in range(1, 4):
            rows.append(dict(unit=uid, time=t, first=0, treat=0, y=rng.normal(), cl=1))
        df = pd.DataFrame(rows)
        with pytest.warns(UserWarning):
            res = LWDiD(
                rolling="demean",
                estimation_method="reg",
                cluster="cl",
                control_group="never_treated",
            ).fit(df, outcome="y", unit="unit", time="time", treatment="treat", first_treat="first")
        assert np.isfinite(res.att)  # point retained
        assert np.isnan(res.se)  # fail-closed propagation
        assert np.isnan(res.p_value)

    def test_qmode_multicell_aggregate_keeps_normal_reference(self):
        # Multi-cell unclustered aggregates: large-sample reference
        # (df_inference is None), documented - not a pooled residual df.
        df = TestSeasonalOverallRouting._quarterly_panel()
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res = LWDiD(
                rolling="demean",
                estimation_method="reg",
                vcov_type="hc1",
                control_group="never_treated",
            ).fit(df, outcome="y", unit="unit", time="time", treatment="treat", first_treat="first")
        assert res.inference_basis == "joint_influence_function"
        assert res.df_inference is None
