"""R-parity tests for ``LPDiD`` (Dube, Girardi, Jorda & Taylor 2025), absorbing.

Pins our ``LPDiD`` against goldens generated by
``benchmarks/R/generate_lpdid_golden.R`` from the method authors' own reference
recipes (the ``danielegirardi/lpdid`` ``fixest::feols`` event-study / reweight /
premean / pooled specifications) with an ``alexCardazzi/lpdid`` cross-check gate.
The paper specifies no SE formula, so validation is against the reference
software, not the paper. Point estimates and cluster-robust SEs match to ~1e-12
on the reference platform; the tests assert ATT ``abs=1e-6`` / SE ``abs=1e-7`` for
cross-platform robustness (matching the ``didimputation`` parity precedent).

Two paths get special handling, both documented in ``docs/methodology/REGISTRY.md``
``## LPDiD`` Deviations:

* **Regression adjustment (RA) standard error** (``ra_cov``): the canonical RA SE
  is Stata ``teffects ra ... atet vce(cluster)`` only - no R package computes it
  (``alexCardazzi`` uses direct covariate inclusion, not RA). We therefore anchor
  the RA *point* estimate against R (full-interaction == ``teffects`` point) and
  pin the library influence-function SE as a documented regression guard
  (``RA_SE_PIN``); its calibration is validated out-of-band by the ungated
  ``benchmarks/python/coverage_lpdid_ra.py`` Monte-Carlo coverage study.
* **no_composition** is intentionally not a parity variant: the library fixes the
  realized sample across all post horizons (paper Section 3.6), more faithful than
  any R package's per-horizon version, so it has no external anchor. It is
  validated by the pure-Python tests in ``tests/test_lpdid.py``.

Regenerate the goldens with::

    Rscript benchmarks/R/generate_lpdid_golden.R
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from diff_diff import SurveyDesign
from diff_diff.lpdid import LPDiD

_DATA = Path(__file__).parent.parent / "benchmarks" / "data"
GOLDEN_PATH = _DATA / "lpdid_golden.json"
PANEL_PATH = _DATA / "lpdid_test_panel.csv"
_R_FIXTURE_AVAILABLE = GOLDEN_PATH.is_file() and PANEL_PATH.is_file()

# Phase C2: non-absorbing R-parity (a separate panel + golden so the absorbing
# fixtures above stay byte-identical). Both non-absorbing modes are anchored on an
# INDEPENDENT fixest::feols reconstruction of the paper's Eq. 12 (first_entry) and
# Eq. 13 (effect_stabilization) clean-sample restrictions; alexCardazzi's
# nonabsorbing_lag is recorded in the golden meta as a divergent reference, NOT a
# parity gate (it clamps off-switches + uses a non-paper boundary/window convention).
NA_GOLDEN_PATH = _DATA / "lpdid_nonabsorbing_golden.json"
NA_PANEL_PATH = _DATA / "lpdid_nonabsorbing_panel.csv"
_NONABSORB_FIXTURE_AVAILABLE = NA_GOLDEN_PATH.is_file() and NA_PANEL_PATH.is_file()

# Phase D2: complex-survey R-parity. The merged D1 survey path (pweight + stratified-PSU
# Binder TSL sandwich, fit(survey_design=...)) is pinned against survey::svyglm goldens on
# a dedicated staggered-absorbing survey panel (separate seed -> the absorbing/non-absorbing
# fixtures above stay byte-identical). Each clean LP-DiD horizon uses a fresh svydesign over
# that horizon's sample; the clean-sample construction is independently alexCardazzi-cross-
# checked in the generator, and svyglm supplies the survey variance. Goldens record
# c(estimate, SE, df, n_psu) per horizon / pooled row.
SURVEY_GOLDEN_PATH = _DATA / "lpdid_survey_golden.json"
SURVEY_PANEL_PATH = _DATA / "lpdid_survey_panel.csv"
_SURVEY_FIXTURE_AVAILABLE = SURVEY_GOLDEN_PATH.is_file() and SURVEY_PANEL_PATH.is_file()

# Library regression-adjustment influence-function SE per horizon (reweight=True,
# covariates=["x"]). NOT R-parity: the canonical RA SE is Stata teffects only, with
# no runnable R analogue (see module docstring / REGISTRY ## LPDiD Deviation 2).
# Pinned regression guard. If the committed panel changes, refresh these from the
# library: fit LPDiD(pre_window=3, post_window=4, reweight=True, cluster="unit") on
# lpdid_test_panel.csv with covariates=["x"], then read event_study["se"] (RA_SE_PIN)
# and results.se / the pooled "pre" row se (POOLED_RA_SE_PIN).
RA_SE_PIN = {
    -3: 0.4329626086028361,
    -2: 0.4359293779913195,
    0: 0.45516589747218855,
    1: 0.4452290481291023,
    2: 0.4617939686659572,
    3: 0.39295354484873873,
    4: 0.39398602601018545,
}
# Headline (pooled) RA influence-function SE, same convention as RA_SE_PIN.
POOLED_RA_SE_PIN = {"post": 0.35917407532121975, "pre": 0.3785290141761256}

# Non-absorbing reweighted (effect_stabilization) SE per horizon. NOT feols-parity:
# the reweighted POINT matches the independent feols recipe to ~1e-13, but the
# weighted-cluster SE has a small feols convention difference (~5e-5), so the library
# value is pinned as a regression guard (the variance-weighted SEs ARE feols-parity).
# Refresh from the library if the committed non-absorbing panel changes: fit
# LPDiD(pre_window=3, post_window=4, reweight=True, cluster="unit",
# non_absorbing="effect_stabilization", stabilization_window=3) on
# lpdid_nonabsorbing_panel.csv and read event_study["se"].
RW_SE_PIN = {
    -3: 0.0645474561163424,
    -2: 0.04782093937871335,
    0: 0.07250480396311137,
    1: 0.06781253723720812,
    2: 0.08001875551196519,
    3: 0.07730466850470008,
    4: 0.09296215631711323,
}


@pytest.fixture(scope="module")
def golden() -> dict:
    if not _R_FIXTURE_AVAILABLE:
        pytest.skip(
            "R LPDiD parity fixture not present. Run "
            "`Rscript benchmarks/R/generate_lpdid_golden.R` to regenerate "
            "`benchmarks/data/lpdid_golden.json`."
        )
    with GOLDEN_PATH.open("r") as f:
        return json.loads(f.read())


@pytest.fixture(scope="module")
def panel() -> pd.DataFrame:
    if not _R_FIXTURE_AVAILABLE:
        pytest.skip("R LPDiD parity fixture not present.")
    return pd.read_csv(PANEL_PATH)


@pytest.fixture(scope="module")
def na_golden() -> dict:
    if not _NONABSORB_FIXTURE_AVAILABLE:
        pytest.skip(
            "Non-absorbing R parity fixture not present. Run "
            "`Rscript benchmarks/R/generate_lpdid_golden.R`."
        )
    with NA_GOLDEN_PATH.open("r") as f:
        return json.loads(f.read())


@pytest.fixture(scope="module")
def na_panel() -> pd.DataFrame:
    if not _NONABSORB_FIXTURE_AVAILABLE:
        pytest.skip("Non-absorbing R parity fixture not present.")
    return pd.read_csv(NA_PANEL_PATH)


@pytest.fixture(scope="module")
def survey_golden() -> dict:
    if not _SURVEY_FIXTURE_AVAILABLE:
        pytest.skip(
            "Survey LPDiD parity fixture not present. Run "
            "`Rscript benchmarks/R/generate_lpdid_survey_golden.R`."
        )
    with SURVEY_GOLDEN_PATH.open("r") as f:
        return json.loads(f.read())


@pytest.fixture(scope="module")
def survey_panel() -> pd.DataFrame:
    if not _SURVEY_FIXTURE_AVAILABLE:
        pytest.skip("Survey LPDiD parity fixture not present.")
    return pd.read_csv(SURVEY_PANEL_PATH)


def _es_map(res) -> dict:
    return {
        int(r.horizon): (float(r.coefficient), float(r.se)) for r in res.event_study.itertuples()
    }


def _num(v) -> float:
    """Coerce a golden cell (number, JSON null, or a stray ``"NA"`` string) to float;
    any non-numeric value becomes NaN so the missing-value branch fires instead of a
    ``TypeError`` from calling ``np.isfinite`` on a non-number."""
    try:
        return float(v)
    except (TypeError, ValueError):
        return float("nan")


def _assert_es(ours: dict, golden_es: dict, *, check_se: bool = True) -> None:
    """Every golden horizon must be present and finite in ours, no silent skips."""
    assert golden_es, "golden variant has no horizons"
    for hk, gv in golden_es.items():
        h = int(hk)
        assert h in ours, f"missing horizon {h}"
        o_att, o_se = ours[h]
        g_att = _num(gv[0])
        if not np.isfinite(g_att):
            # NaN-consistency: a missing golden horizon requires BOTH our att and se NaN
            # (the library's all-inference-fields-NaN-together contract), not just att.
            assert not np.isfinite(o_att) and not np.isfinite(
                o_se
            ), f"h={h}: golden att NA but ours not fully NaN (att={o_att}, se={o_se})"
            continue
        assert np.isfinite(o_att), f"h={h}: non-finite att"
        assert o_att == pytest.approx(g_att, abs=1e-6), f"att h={h}"
        if check_se:
            g_se = _num(gv[1])
            if not np.isfinite(g_se):
                assert not np.isfinite(o_se), f"h={h}: golden se NA but ours finite"
            else:
                assert np.isfinite(o_se), f"h={h}: non-finite se"
                assert o_se == pytest.approx(g_se, abs=1e-7), f"se h={h}"


def _window(golden: dict):
    return golden["meta"]["pre_window"], golden["meta"]["post_window"]


def test_assert_es_tolerates_missing_golden_horizons() -> None:
    """A missing golden cell (JSON null, stray 'NA' string, or NaN) is handled as an
    empty-result horizon - consistent when ours is also NaN, a failure when ours is
    finite - never a TypeError."""
    for na in (None, "NA", float("nan")):
        _assert_es(
            {0: (1.0, 0.1), 1: (float("nan"), float("nan"))},
            {"0": [1.0, 0.1], "1": [na, na]},
        )
        # ours finite where golden is NA -> inconsistent, must fail
        with pytest.raises(AssertionError):
            _assert_es({1: (5.0, 0.1)}, {"1": [na, na]})
        # NaN-consistency: att NaN but se still finite must also fail (both must be NaN)
        with pytest.raises(AssertionError):
            _assert_es({1: (float("nan"), 0.1)}, {"1": [na, na]})


class TestLPDiDParityR:
    """Pin ``LPDiD`` against the authors' reference recipes + alexCardazzi cross-check."""

    def test_vw_event_study(self, golden: dict, panel: pd.DataFrame) -> None:
        pre, post = _window(golden)
        res = LPDiD(pre_window=pre, post_window=post, reweight=False, cluster="unit").fit(
            panel, outcome="y", unit="unit", time="time", treatment="treat"
        )
        _assert_es(_es_map(res), golden["vw_es"])

    def test_ew_reweight_event_study(self, golden: dict, panel: pd.DataFrame) -> None:
        pre, post = _window(golden)
        res = LPDiD(pre_window=pre, post_window=post, reweight=True, cluster="unit").fit(
            panel, outcome="y", unit="unit", time="time", treatment="treat"
        )
        _assert_es(_es_map(res), golden["ew_es"])

    def test_pmd_event_study(self, golden: dict, panel: pd.DataFrame) -> None:
        pre, post = _window(golden)
        res = LPDiD(pre_window=pre, post_window=post, reweight=False, pmd=2, cluster="unit").fit(
            panel, outcome="y", unit="unit", time="time", treatment="treat"
        )
        _assert_es(_es_map(res), golden["pmd_es"])

    def test_direct_covariate_event_study(self, golden: dict, panel: pd.DataFrame) -> None:
        pre, post = _window(golden)
        # Direct inclusion (reweight=False + covariates) must emit the Appendix B.2.2
        # homogeneity warning (REGISTRY ## LPDiD Deviation 3).
        with pytest.warns(UserWarning, match="direct inclusion"):
            res = LPDiD(pre_window=pre, post_window=post, reweight=False, cluster="unit").fit(
                panel, covariates=["x"], outcome="y", unit="unit", time="time", treatment="treat"
            )
        _assert_es(_es_map(res), golden["direct_es"])

    def test_pooled(self, golden: dict, panel: pd.DataFrame) -> None:
        pre, post = _window(golden)
        res = LPDiD(pre_window=pre, post_window=post, reweight=False, cluster="unit").fit(
            panel, outcome="y", unit="unit", time="time", treatment="treat"
        )
        g_post = golden["pooled"]["post"]
        assert np.isfinite(res.att) and np.isfinite(res.se)
        assert res.att == pytest.approx(g_post[0], abs=1e-6)
        assert res.se == pytest.approx(g_post[1], abs=1e-7)
        # pre pooled row
        pre_row = res.pooled.loc[res.pooled["window"] == "pre"]
        assert len(pre_row) == 1
        g_pre = golden["pooled"]["pre"]
        assert float(pre_row["coefficient"].iloc[0]) == pytest.approx(g_pre[0], abs=1e-6)
        assert float(pre_row["se"].iloc[0]) == pytest.approx(g_pre[1], abs=1e-7)

    def test_ra_covariate_point(self, golden: dict, panel: pd.DataFrame) -> None:
        """RA point estimate == authors' teffects/full-interaction point (R-anchored)."""
        pre, post = _window(golden)
        res = LPDiD(pre_window=pre, post_window=post, reweight=True, cluster="unit").fit(
            panel, covariates=["x"], outcome="y", unit="unit", time="time", treatment="treat"
        )
        _assert_es(_es_map(res), golden["ra_cov"], check_se=False)

    def test_ra_covariate_se_regression_pin(self, panel: pd.DataFrame) -> None:
        """RA influence-function SE pinned (no runnable R reference; see RA_SE_PIN).

        Calibration validated separately by benchmarks/python/coverage_lpdid_ra.py.
        """
        res = LPDiD(pre_window=3, post_window=4, reweight=True, cluster="unit").fit(
            panel, covariates=["x"], outcome="y", unit="unit", time="time", treatment="treat"
        )
        es = {int(r.horizon): float(r.se) for r in res.event_study.itertuples()}
        for h, pinned in RA_SE_PIN.items():
            assert h in es, f"missing horizon {h}"
            assert np.isfinite(es[h]) and es[h] > 0, f"h={h}: RA SE not finite/positive"
            assert es[h] == pytest.approx(pinned, abs=1e-6), f"RA SE pin drift at h={h}"
        # Headline (pooled) RA SE is the same convention - pin it too so pooled RA
        # inference drift is also caught (not just the event-study horizons).
        assert np.isfinite(res.se) and res.se > 0
        assert res.se == pytest.approx(
            POOLED_RA_SE_PIN["post"], abs=1e-6
        ), "pooled-post RA SE drift"
        pre_se = float(res.pooled.loc[res.pooled["window"] == "pre", "se"].iloc[0])
        assert pre_se == pytest.approx(POOLED_RA_SE_PIN["pre"], abs=1e-6), "pooled-pre RA SE drift"


class TestLPDiDNonAbsorbingParityR:
    """Pin the C1 non-absorbing modes against the independent feols Eq. 12/13 recipes.

    The variance-weighted variants match the feols golden on point AND SE; the
    reweighted point matches feols while its SE is a pinned regression guard
    (documented weighted-cluster convention difference). alexCardazzi's
    ``nonabsorbing_lag`` is recorded in the golden meta as a divergent reference only.
    """

    def _meta(self, na_golden: dict):
        m = na_golden["meta"]
        return int(m["L"]), int(m["pre_window"]), int(m["post_window"])

    def test_first_entry_event_study(self, na_golden: dict, na_panel: pd.DataFrame) -> None:
        L, pre, post = self._meta(na_golden)
        res = LPDiD(
            pre_window=pre, post_window=post, cluster="unit", non_absorbing="first_entry"
        ).fit(na_panel, outcome="y", unit="unit", time="time", treatment="treat", only_event=True)
        _assert_es(_es_map(res), na_golden["first_entry"])  # point + SE (feols-parity)

    def test_effect_stabilization_event_study(
        self, na_golden: dict, na_panel: pd.DataFrame
    ) -> None:
        L, pre, post = self._meta(na_golden)
        res = LPDiD(
            pre_window=pre,
            post_window=post,
            cluster="unit",
            non_absorbing="effect_stabilization",
            stabilization_window=L,
        ).fit(na_panel, outcome="y", unit="unit", time="time", treatment="treat", only_event=True)
        _assert_es(_es_map(res), na_golden["effect_stab"])  # point + SE (feols-parity)

    def test_effect_stabilization_reweighted_point(
        self, na_golden: dict, na_panel: pd.DataFrame
    ) -> None:
        """Reweighted (equally-weighted) effect_stabilization POINT == feols recipe.

        The reweighted SE is pinned separately (RW_SE_PIN) - it has a small
        weighted-cluster convention difference vs feols, not feols-parity.
        """
        L, pre, post = self._meta(na_golden)
        res = LPDiD(
            pre_window=pre,
            post_window=post,
            reweight=True,
            cluster="unit",
            non_absorbing="effect_stabilization",
            stabilization_window=L,
        ).fit(na_panel, outcome="y", unit="unit", time="time", treatment="treat", only_event=True)
        _assert_es(_es_map(res), na_golden["effect_stab_rw"], check_se=False)
        # Reweighted SE: pinned regression guard (documented feols convention diff).
        es = {int(r.horizon): float(r.se) for r in res.event_study.itertuples()}
        for h, pinned in RW_SE_PIN.items():
            assert h in es, f"missing horizon {h}"
            assert np.isfinite(es[h]) and es[h] > 0, f"h={h}: reweighted SE not finite/positive"
            assert es[h] == pytest.approx(pinned, abs=1e-6), f"reweighted SE pin drift at h={h}"

    def test_alex_recorded_as_divergent_reference(self, na_golden: dict) -> None:
        """alexCardazzi nonabsorbing_lag is recorded (meta), NOT a parity gate: it
        diverges from the paper-faithful Eq.13 even on this panel."""
        alex = na_golden["alex_nonabsorbing_lag"]
        assert "error" not in alex, f"alex reference failed to generate: {alex}"
        es = na_golden["effect_stab"]
        # At least one post horizon differs materially (off-switch clamp / boundary),
        # which is exactly why alex is documented, not gated.
        diffs = [
            abs(_num(alex[k][0]) - _num(es[k][0]))
            for k in es
            if int(k) >= 0
            and k in alex
            and np.isfinite(_num(es[k][0]))
            and np.isfinite(_num(alex[k][0]))
        ]
        assert diffs and max(diffs) > 1e-3, "expected a documented alex divergence on post horizons"
        # The divergence is NOT only off-switch handling: it persists on the monotone
        # (no-off-switch) sub-panel, recorded as committed evidence in meta.
        mono = _num(na_golden["meta"]["alex_monotone_post_divergence"])
        assert mono > 1e-3, f"expected alex to diverge from Eq.13 on the monotone slice, got {mono}"


class TestLPDiDSurveyParityR:
    """Pin the merged D1 survey path against ``survey::svyglm`` goldens (Phase D2).

    Three structurally-distinct survey variance paths are R-validated end-to-end
    through ``LPDiD.fit(survey_design=...)``:

    * **VW** — full stratified-PSU design with FPC vs ``svyglm(ids=~psu, strata,
      fpc, weights)``; reported ``n_clusters`` == n_PSU == 14, df == n_PSU - n_strata
      == 10 (constant here).
    * **inject** — weights-only, the unit injected as PSU, vs ``svyglm(ids=~unit,
      weights)``; ``n_clusters`` == n_units == 140, df == n_PSU - 1 == 139.
    * **covariate** — direct covariate inclusion vs ``svyglm(Dy ~ tr + x +
      factor(time), ...)`` (emits the Appendix B.2.2 homogeneity warning).

    Each clean LP-DiD horizon uses a FRESH ``svydesign`` over that horizon's sample,
    matching the library's per-sample ``survey_design.resolve(sample)``. The
    clean-sample construction is independently alexCardazzi-cross-checked inside the
    generator (the UNWEIGHTED VW event study matches to <1e-8); ``svyglm`` supplies the
    survey variance, so it is the reference (no separate survey package gate needed).

    Goldens (``c(estimate, SE, df, n_psu)`` per horizon / pooled row) are generated by::

        Rscript benchmarks/R/generate_lpdid_survey_golden.R

    There is no per-horizon ``df`` field in the result schema: ``event_study`` /
    ``pooled`` rows expose ``n_clusters`` (= realized n_PSU), and df is reconstructed
    with the design-specific formula (``n_clusters - n_strata`` with strata, else
    ``n_clusters - 1``). Pure-numpy survey path -> backend-agnostic.
    """

    @staticmethod
    def _fit(panel: pd.DataFrame, sd: SurveyDesign, **kw):
        # The expected per-sample survey warnings (pweight normalization, PSU/cluster
        # reconciliation) are not under test here; silence them so the parity signal is
        # clean. The covariate variant asserts its homogeneity warning explicitly.
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            return LPDiD(pre_window=3, post_window=4, reweight=False, cluster="unit").fit(
                panel,
                outcome="y",
                unit="unit",
                time="time",
                treatment="treat",
                survey_design=sd,
                **kw,
            )

    @staticmethod
    def _assert_es(res, golden_es: dict, *, strata: bool) -> None:
        """Point (``abs=1e-6``) + SE (``rtol=1e-5``/``abs=1e-7``) + n_PSU + df exact, per
        horizon. df is reconstructed from the per-horizon ``n_clusters`` (= realized
        n_PSU) with the design-specific formula."""
        rows = {int(r.horizon): r for r in res.event_study.itertuples()}
        n_strata = int(res.n_strata)
        assert golden_es, "golden variant has no horizons"
        for hk, gv in golden_es.items():
            h = int(hk)
            g_est, g_se, g_df, g_npsu = (_num(gv[i]) for i in range(4))
            assert h in rows, f"missing horizon {h}"
            row = rows[h]
            assert np.isfinite(float(row.coefficient)), f"h={h}: non-finite att"
            assert float(row.coefficient) == pytest.approx(g_est, abs=1e-6), f"att h={h}"
            assert float(row.se) == pytest.approx(g_se, rel=1e-5, abs=1e-7), f"se h={h}"
            assert int(row.n_clusters) == int(g_npsu), f"n_psu h={h}"
            df_recon = int(row.n_clusters) - (n_strata if strata else 1)
            assert df_recon == int(g_df), f"df h={h}: recon {df_recon} != golden {int(g_df)}"

    @staticmethod
    def _assert_pooled(res, golden_pooled: dict, *, strata: bool) -> None:
        n_strata = int(res.n_strata)
        g_post = golden_pooled["post"]
        # post == the headline pooled estimate
        assert np.isfinite(res.att) and np.isfinite(res.se)
        assert float(res.att) == pytest.approx(_num(g_post[0]), abs=1e-6), "pooled-post att"
        assert float(res.se) == pytest.approx(_num(g_post[1]), rel=1e-5, abs=1e-7), "pooled-post se"
        post_row = res.pooled.loc[res.pooled["window"] == "post"].iloc[0]
        # the pooled-post DataFrame row's own coefficient/se (not only the res.att/res.se
        # headline that mirrors them) so a pooled-row schema regression cannot slip past
        assert float(post_row["coefficient"]) == pytest.approx(
            _num(g_post[0]), abs=1e-6
        ), "pooled-post row att"
        assert float(post_row["se"]) == pytest.approx(
            _num(g_post[1]), rel=1e-5, abs=1e-7
        ), "pooled-post row se"
        assert int(post_row["n_clusters"]) == int(_num(g_post[3])), "pooled-post n_psu"
        df_recon = int(post_row["n_clusters"]) - (n_strata if strata else 1)
        assert df_recon == int(_num(g_post[2])), "pooled-post df"
        # pre pooled row: point/SE AND n_psu/df (the df reconstruction has teeth for the
        # inject variant where n_strata == 0)
        g_pre = golden_pooled["pre"]
        pre_row = res.pooled.loc[res.pooled["window"] == "pre"].iloc[0]
        assert float(pre_row["coefficient"]) == pytest.approx(
            _num(g_pre[0]), abs=1e-6
        ), "pooled-pre att"
        assert float(pre_row["se"]) == pytest.approx(
            _num(g_pre[1]), rel=1e-5, abs=1e-7
        ), "pooled-pre se"
        assert int(pre_row["n_clusters"]) == int(_num(g_pre[3])), "pooled-pre n_psu"
        df_recon_pre = int(pre_row["n_clusters"]) - (n_strata if strata else 1)
        assert df_recon_pre == int(_num(g_pre[2])), "pooled-pre df"

    def test_vw_event_study_and_pooled(
        self, survey_golden: dict, survey_panel: pd.DataFrame
    ) -> None:
        """Full stratified-PSU + FPC design vs svyglm; df == n_PSU - n_strata == 10."""
        sd = SurveyDesign(weights="weight", strata="stratum", psu="psu", fpc="fpc")
        res = self._fit(survey_panel, sd)
        # panel-level survey metadata
        assert int(res.n_strata) == int(survey_golden["meta"]["n_strata"])  # 4
        assert int(res.n_psu) == int(survey_golden["meta"]["n_psu_total"])  # 14
        assert int(res.survey_metadata.df_survey) == int(
            survey_golden["meta"]["n_psu_total"]
        ) - int(
            survey_golden["meta"]["n_strata"]
        )  # 10
        self._assert_es(res, survey_golden["survey_vw_es"], strata=True)
        self._assert_pooled(res, survey_golden["survey_vw_pooled"], strata=True)

    def test_inject_weights_only_event_study_and_pooled(
        self, survey_golden: dict, survey_panel: pd.DataFrame
    ) -> None:
        """Weights-only design injects the unit as PSU vs svyglm(ids=~unit); the
        ``_inject_cluster_as_psu`` rebind is exercised end-to-end. df == n_PSU - 1."""
        sd = SurveyDesign(weights="weight")
        res = self._fit(survey_panel, sd)
        assert int(res.n_strata) == 0  # weights-only -> the n_clusters-1 df branch
        self._assert_es(res, survey_golden["survey_inject_es"], strata=False)
        self._assert_pooled(res, survey_golden["survey_inject_pooled"], strata=False)

    def test_covariate_direct_event_study_and_pooled(
        self, survey_golden: dict, survey_panel: pd.DataFrame
    ) -> None:
        """Direct covariate inclusion (reweight=False + covariates) vs svyglm with x;
        the covariate-present full-rank kept-column survey sandwich is R-validated. The
        Appendix B.2.2 homogeneity warning (REGISTRY ## LPDiD Deviation 3) is asserted."""
        sd = SurveyDesign(weights="weight", strata="stratum", psu="psu", fpc="fpc")
        with pytest.warns(UserWarning, match="direct inclusion"):
            res = LPDiD(pre_window=3, post_window=4, reweight=False, cluster="unit").fit(
                survey_panel,
                covariates=["x"],
                outcome="y",
                unit="unit",
                time="time",
                treatment="treat",
                survey_design=sd,
            )
        self._assert_es(res, survey_golden["survey_cov_es"], strata=True)
        self._assert_pooled(res, survey_golden["survey_cov_pooled"], strata=True)

    def test_fpc_shrinks_se(self, survey_golden: dict, survey_panel: pd.DataFrame) -> None:
        """A finite FPC shrinks the SE vs no-FPC, and the no-FPC path also matches svyglm.
        Both SEs are independently pinned to svyglm, so this checks the FPC mechanism
        end-to-end through the library, not just the golden."""
        sd_fpc = SurveyDesign(weights="weight", strata="stratum", psu="psu", fpc="fpc")
        sd_nofpc = SurveyDesign(weights="weight", strata="stratum", psu="psu")
        res_fpc = self._fit(survey_panel, sd_fpc)
        res_nofpc = self._fit(survey_panel, sd_nofpc)
        # the no-FPC path is itself svyglm-validated
        self._assert_es(res_nofpc, survey_golden["survey_vw_nofpc_es"], strata=True)
        se_fpc = {
            int(r.horizon): float(r.se)
            for r in res_fpc.event_study.itertuples()
            if np.isfinite(r.se)
        }
        se_nofpc = {
            int(r.horizon): float(r.se)
            for r in res_nofpc.event_study.itertuples()
            if np.isfinite(r.se)
        }
        assert se_fpc and se_fpc.keys() == se_nofpc.keys()
        for h in se_fpc:
            assert (
                se_fpc[h] < se_nofpc[h]
            ), f"FPC should shrink the SE at h={h}: {se_fpc[h]} !< {se_nofpc[h]}"

    def test_weighting_moves_point(self, survey_panel: pd.DataFrame) -> None:
        """The survey-weighted headline point differs from the unweighted VW point, so
        the probability weights demonstrably flow into the WLS estimate (not ignored)."""
        sd = SurveyDesign(weights="weight", strata="stratum", psu="psu", fpc="fpc")
        res_survey = self._fit(survey_panel, sd)
        res_unweighted = LPDiD(pre_window=3, post_window=4, reweight=False, cluster="unit").fit(
            survey_panel, outcome="y", unit="unit", time="time", treatment="treat"
        )
        assert abs(float(res_survey.att) - float(res_unweighted.att)) > 1e-3
