"""R-parity tests for ``LPDiD`` (Dube, Girardi, Jorda & Taylor 2025), absorbing.

Pins our ``LPDiD`` against goldens generated by
``benchmarks/R/generate_lpdid_golden.R`` from the method authors' own reference
recipes (the ``danielegirardi/lpdid`` ``fixest::feols`` event-study / reweight /
premean / pooled specifications) with an ``alexCardazzi/lpdid`` cross-check gate.
The paper specifies no SE formula, so validation is against the reference
software, not the paper. Point estimates and cluster-robust SEs match to ~1e-12
on the reference platform; the tests assert ATT ``abs=1e-6`` / SE ``abs=1e-7`` for
cross-platform robustness (matching the ``didimputation`` parity precedent).

Two paths get special handling, both documented in ``docs/methodology/REGISTRY.md``
``## LPDiD`` Deviations:

* **Regression adjustment (RA) standard error** (``ra_cov``): the canonical RA SE
  is Stata ``teffects ra ... atet vce(cluster)`` only - no R package computes it
  (``alexCardazzi`` uses direct covariate inclusion, not RA). We therefore anchor
  the RA *point* estimate against R (full-interaction == ``teffects`` point) and
  pin the library influence-function SE as a documented regression guard
  (``RA_SE_PIN``); its calibration is validated out-of-band by the ungated
  ``benchmarks/python/coverage_lpdid_ra.py`` Monte-Carlo coverage study.
* **no_composition** is intentionally not a parity variant: the library fixes the
  realized sample across all post horizons (paper Section 3.6), more faithful than
  any R package's per-horizon version, so it has no external anchor. It is
  validated by the pure-Python tests in ``tests/test_lpdid.py``.

Regenerate the goldens with::

    Rscript benchmarks/R/generate_lpdid_golden.R
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from diff_diff.lpdid import LPDiD

_DATA = Path(__file__).parent.parent / "benchmarks" / "data"
GOLDEN_PATH = _DATA / "lpdid_golden.json"
PANEL_PATH = _DATA / "lpdid_test_panel.csv"
_R_FIXTURE_AVAILABLE = GOLDEN_PATH.is_file() and PANEL_PATH.is_file()

# Library regression-adjustment influence-function SE per horizon (reweight=True,
# covariates=["x"]). NOT R-parity: the canonical RA SE is Stata teffects only, with
# no runnable R analogue (see module docstring / REGISTRY ## LPDiD Deviation 2).
# Pinned regression guard. If the committed panel changes, refresh these from the
# library: fit LPDiD(pre_window=3, post_window=4, reweight=True, cluster="unit") on
# lpdid_test_panel.csv with covariates=["x"], then read event_study["se"] (RA_SE_PIN)
# and results.se / the pooled "pre" row se (POOLED_RA_SE_PIN).
RA_SE_PIN = {
    -3: 0.4329626086028361,
    -2: 0.4359293779913195,
    0: 0.45516589747218855,
    1: 0.4452290481291023,
    2: 0.4617939686659572,
    3: 0.39295354484873873,
    4: 0.39398602601018545,
}
# Headline (pooled) RA influence-function SE, same convention as RA_SE_PIN.
POOLED_RA_SE_PIN = {"post": 0.35917407532121975, "pre": 0.3785290141761256}


@pytest.fixture(scope="module")
def golden() -> dict:
    if not _R_FIXTURE_AVAILABLE:
        pytest.skip(
            "R LPDiD parity fixture not present. Run "
            "`Rscript benchmarks/R/generate_lpdid_golden.R` to regenerate "
            "`benchmarks/data/lpdid_golden.json`."
        )
    with GOLDEN_PATH.open("r") as f:
        return json.loads(f.read())


@pytest.fixture(scope="module")
def panel() -> pd.DataFrame:
    if not _R_FIXTURE_AVAILABLE:
        pytest.skip("R LPDiD parity fixture not present.")
    return pd.read_csv(PANEL_PATH)


def _es_map(res) -> dict:
    return {
        int(r.horizon): (float(r.coefficient), float(r.se)) for r in res.event_study.itertuples()
    }


def _num(v) -> float:
    """Coerce a golden cell (number, JSON null, or a stray ``"NA"`` string) to float;
    any non-numeric value becomes NaN so the missing-value branch fires instead of a
    ``TypeError`` from calling ``np.isfinite`` on a non-number."""
    try:
        return float(v)
    except (TypeError, ValueError):
        return float("nan")


def _assert_es(ours: dict, golden_es: dict, *, check_se: bool = True) -> None:
    """Every golden horizon must be present and finite in ours, no silent skips."""
    assert golden_es, "golden variant has no horizons"
    for hk, gv in golden_es.items():
        h = int(hk)
        assert h in ours, f"missing horizon {h}"
        o_att, o_se = ours[h]
        g_att = _num(gv[0])
        if not np.isfinite(g_att):
            # NaN-consistency: a missing golden horizon requires BOTH our att and se NaN
            # (the library's all-inference-fields-NaN-together contract), not just att.
            assert not np.isfinite(o_att) and not np.isfinite(
                o_se
            ), f"h={h}: golden att NA but ours not fully NaN (att={o_att}, se={o_se})"
            continue
        assert np.isfinite(o_att), f"h={h}: non-finite att"
        assert o_att == pytest.approx(g_att, abs=1e-6), f"att h={h}"
        if check_se:
            g_se = _num(gv[1])
            if not np.isfinite(g_se):
                assert not np.isfinite(o_se), f"h={h}: golden se NA but ours finite"
            else:
                assert np.isfinite(o_se), f"h={h}: non-finite se"
                assert o_se == pytest.approx(g_se, abs=1e-7), f"se h={h}"


def _window(golden: dict):
    return golden["meta"]["pre_window"], golden["meta"]["post_window"]


def test_assert_es_tolerates_missing_golden_horizons() -> None:
    """A missing golden cell (JSON null, stray 'NA' string, or NaN) is handled as an
    empty-result horizon - consistent when ours is also NaN, a failure when ours is
    finite - never a TypeError."""
    for na in (None, "NA", float("nan")):
        _assert_es(
            {0: (1.0, 0.1), 1: (float("nan"), float("nan"))},
            {"0": [1.0, 0.1], "1": [na, na]},
        )
        # ours finite where golden is NA -> inconsistent, must fail
        with pytest.raises(AssertionError):
            _assert_es({1: (5.0, 0.1)}, {"1": [na, na]})
        # NaN-consistency: att NaN but se still finite must also fail (both must be NaN)
        with pytest.raises(AssertionError):
            _assert_es({1: (float("nan"), 0.1)}, {"1": [na, na]})


class TestLPDiDParityR:
    """Pin ``LPDiD`` against the authors' reference recipes + alexCardazzi cross-check."""

    def test_vw_event_study(self, golden: dict, panel: pd.DataFrame) -> None:
        pre, post = _window(golden)
        res = LPDiD(pre_window=pre, post_window=post, reweight=False, cluster="unit").fit(
            panel, outcome="y", unit="unit", time="time", treatment="treat"
        )
        _assert_es(_es_map(res), golden["vw_es"])

    def test_ew_reweight_event_study(self, golden: dict, panel: pd.DataFrame) -> None:
        pre, post = _window(golden)
        res = LPDiD(pre_window=pre, post_window=post, reweight=True, cluster="unit").fit(
            panel, outcome="y", unit="unit", time="time", treatment="treat"
        )
        _assert_es(_es_map(res), golden["ew_es"])

    def test_pmd_event_study(self, golden: dict, panel: pd.DataFrame) -> None:
        pre, post = _window(golden)
        res = LPDiD(pre_window=pre, post_window=post, reweight=False, pmd=2, cluster="unit").fit(
            panel, outcome="y", unit="unit", time="time", treatment="treat"
        )
        _assert_es(_es_map(res), golden["pmd_es"])

    def test_direct_covariate_event_study(self, golden: dict, panel: pd.DataFrame) -> None:
        pre, post = _window(golden)
        # Direct inclusion (reweight=False + covariates) must emit the Appendix B.2.2
        # homogeneity warning (REGISTRY ## LPDiD Deviation 3).
        with pytest.warns(UserWarning, match="direct inclusion"):
            res = LPDiD(pre_window=pre, post_window=post, reweight=False, cluster="unit").fit(
                panel, covariates=["x"], outcome="y", unit="unit", time="time", treatment="treat"
            )
        _assert_es(_es_map(res), golden["direct_es"])

    def test_pooled(self, golden: dict, panel: pd.DataFrame) -> None:
        pre, post = _window(golden)
        res = LPDiD(pre_window=pre, post_window=post, reweight=False, cluster="unit").fit(
            panel, outcome="y", unit="unit", time="time", treatment="treat"
        )
        g_post = golden["pooled"]["post"]
        assert np.isfinite(res.att) and np.isfinite(res.se)
        assert res.att == pytest.approx(g_post[0], abs=1e-6)
        assert res.se == pytest.approx(g_post[1], abs=1e-7)
        # pre pooled row
        pre_row = res.pooled.loc[res.pooled["window"] == "pre"]
        assert len(pre_row) == 1
        g_pre = golden["pooled"]["pre"]
        assert float(pre_row["coefficient"].iloc[0]) == pytest.approx(g_pre[0], abs=1e-6)
        assert float(pre_row["se"].iloc[0]) == pytest.approx(g_pre[1], abs=1e-7)

    def test_ra_covariate_point(self, golden: dict, panel: pd.DataFrame) -> None:
        """RA point estimate == authors' teffects/full-interaction point (R-anchored)."""
        pre, post = _window(golden)
        res = LPDiD(pre_window=pre, post_window=post, reweight=True, cluster="unit").fit(
            panel, covariates=["x"], outcome="y", unit="unit", time="time", treatment="treat"
        )
        _assert_es(_es_map(res), golden["ra_cov"], check_se=False)

    def test_ra_covariate_se_regression_pin(self, panel: pd.DataFrame) -> None:
        """RA influence-function SE pinned (no runnable R reference; see RA_SE_PIN).

        Calibration validated separately by benchmarks/python/coverage_lpdid_ra.py.
        """
        res = LPDiD(pre_window=3, post_window=4, reweight=True, cluster="unit").fit(
            panel, covariates=["x"], outcome="y", unit="unit", time="time", treatment="treat"
        )
        es = {int(r.horizon): float(r.se) for r in res.event_study.itertuples()}
        for h, pinned in RA_SE_PIN.items():
            assert h in es, f"missing horizon {h}"
            assert np.isfinite(es[h]) and es[h] > 0, f"h={h}: RA SE not finite/positive"
            assert es[h] == pytest.approx(pinned, abs=1e-6), f"RA SE pin drift at h={h}"
        # Headline (pooled) RA SE is the same convention - pin it too so pooled RA
        # inference drift is also caught (not just the event-study horizons).
        assert np.isfinite(res.se) and res.se > 0
        assert res.se == pytest.approx(
            POOLED_RA_SE_PIN["post"], abs=1e-6
        ), "pooled-post RA SE drift"
        pre_se = float(res.pooled.loc[res.pooled["window"] == "pre", "se"].iloc[0])
        assert pre_se == pytest.approx(POOLED_RA_SE_PIN["pre"], abs=1e-6), "pooled-pre RA SE drift"
