"""Tests for RDDensityTest (diff_diff/rddensity.py) - the CJM 2020
manipulation test, parity-targeting R rddensity 3.0.

Golden parity: benchmarks/data/rddensity_golden.json, generated by
``Rscript benchmarks/R/generate_rddensity_golden.R`` against CRAN
rddensity 3.0 (tarball sha256 pinned in the generator and asserted from the
JSON metadata here). Synthetic DGP samples are embedded in the JSON (R RNG
streams are not reproducible from numpy); the senate/headstart configs read
the vendored CSVs.

R-free lanes: paper anchors (the CJM 2020 Table 1 Head Start application),
methodology identities (generator-level reflection identity, joint-vs-
separate rescaling under the rank EDF, jackknife window-vs-literal lock),
validation/error contracts, and API contracts.
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from diff_diff import RDDensityTest, RDDensityTestResult
from diff_diff.rddensity import (
    _KERNEL_POLY_01,
    _embed_plus,
    _moment_g,
    _moment_s,
    _poly_eval,
    _psi_matrix,
    _rddensity_fv,
    _restricted_plugin_variance,
)

GOLDEN_PATH = Path(__file__).resolve().parents[1] / "benchmarks" / "data" / "rddensity_golden.json"
SENATE_PATH = Path(__file__).resolve().parents[1] / "benchmarks" / "data" / "rdrobust_senate.csv"
HEADSTART_PATH = (
    Path(__file__).resolve().parents[1] / "benchmarks" / "data" / "rddensity_headstart.csv"
)

# The golden pipeline chains the bandwidth selector (two pilot fits at
# orders p and p+2), the window trim, and the order-q estimation - float
# noise accumulates across the chain, so the global parity bar is 1e-8
# (eight significant digits; the rdplot/rdrobust 1e-9 precedent applies to
# single un-chained fits).
RTOL = 1e-8

# Conditioning-limited configs (each stays as a correct-at-its-conditioning
# anchor; 1e-9 parity is mathematically unattainable there):
# - dgp_normal/p7: the selector's pilot fit runs at order p+2=9 (Gram
#   condition ~1e15), so the SELECTED bandwidth is only reproducible to
#   ~1e-5 relative across BLAS implementations, and that drift propagates
#   to every downstream quantity.
# - the nUniqueMin=0 floor configs on the tied fixtures: with the unique-
#   value floor disabled the selector runs on a tiny tied window whose
#   pilot quantities carry ~1e-8 relative float noise (floors_0_0 and
#   floors_50_0 are numerically the same selector run where the nLocalMin
#   gate does not bind).
RTOL_OVERRIDES = {
    ("dgp_normal", "p7"): 2e-3,
    ("dgp_masspoints", "floors_0_0"): 1e-7,
    ("dgp_masspoints", "floors_50_0"): 1e-7,
    ("dgp_masspoints_small", "floors_0_0"): 1e-7,
    ("dgp_masspoints_small", "floors_50_0"): 1e-7,
}


@pytest.fixture(scope="module")
def golden():
    if not GOLDEN_PATH.exists():
        pytest.skip(
            "rddensity golden file not found; regenerate with "
            "`Rscript benchmarks/R/generate_rddensity_golden.R` "
            "(requires CRAN rddensity 3.0)."
        )
    with open(GOLDEN_PATH) as fh:
        return json.load(fh)


def _num(value):
    """jsonlite writes NA as the string 'NA' (and NaN as null)."""
    if value is None or value == "NA":
        return np.nan
    return float(value)


def _estimator_from_args(args) -> RDDensityTest:
    """Rebuild RDDensityTest(...) from the golden config's R-args echo."""
    h = args.get("h")
    if isinstance(h, list):
        h = tuple(h)
    return RDDensityTest(
        cutoff=args["c"],
        p=args["p"],
        q=None if args["q"] == 0 else args["q"],
        fitselect=args["fitselect"],
        kernel=args["kernel"],
        vcov_type=args["vce"],
        h=h,
        bwselect=args["bwselect"],
        masspoints="adjust" if args["massPoints"] else "off",
        regularize=args["regularize"],
        n_local_min=args.get("nLocalMin"),
        n_unique_min=args.get("nUniqueMin"),
        report_all=args["all"],
    )


def _fit_quiet(est: RDDensityTest, x: np.ndarray) -> RDDensityTestResult:
    df = pd.DataFrame({"x": x})
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return est.fit(df, running="x")


def _section_x(golden, section: str) -> np.ndarray:
    entry = golden[section]
    if "x" in entry:
        return np.asarray(entry["x"], dtype=float)
    csv = Path(__file__).resolve().parents[1] / entry["csv"]
    if not csv.exists():
        pytest.skip(f"vendored data file {entry['csv']} not found")
    col = pd.read_csv(csv)[entry["column"]]
    return col.dropna().to_numpy(dtype=float)


def _iter_configs(golden):
    for section, entry in golden.items():
        if section == "metadata":
            continue
        for name, cfg in entry["configs"].items():
            yield section, name, cfg


# --------------------------------------------------------------------------- #
# Golden parity
# --------------------------------------------------------------------------- #


class TestGoldenMetadata:
    def test_version_pin(self, golden):
        assert golden["metadata"]["package"] == "rddensity"
        assert golden["metadata"]["version"] == "3.0"
        assert golden["metadata"]["tarball_sha256"] == (
            "a9c45ab0f6b86ead4d91084db16513d4156b7f59b0472510b63deb5dee6f305d"
        )


class TestGoldenParity:
    def test_all_configs(self, golden):
        checked = 0
        for section, name, cfg in _iter_configs(golden):
            x = _section_x(golden, section)
            res = _fit_quiet(_estimator_from_args(cfg["args"]), x)
            label = f"{section}/{name}"
            rtol = RTOL_OVERRIDES.get((section, name), RTOL)

            # point estimates + selected-vce SEs (robust/RBC block)
            np.testing.assert_allclose(
                res.f_left, _num(cfg["hat"]["left"]), rtol=rtol, err_msg=f"{label}: f_left"
            )
            np.testing.assert_allclose(
                res.f_right, _num(cfg["hat"]["right"]), rtol=rtol, err_msg=f"{label}: f_right"
            )
            np.testing.assert_allclose(
                res.f_diff,
                _num(cfg["hat"]["diff"]),
                rtol=rtol,
                atol=1e-9,  # f_diff is a difference of two O(0.3-0.7)
                # densities; cancellation costs digits of relative precision,
                # and tied-data configs with disabled floors (tiny windows)
                # carry ~1e-10 absolute float noise per side
                err_msg=f"{label}: f_diff",
            )
            sd_block = cfg["sd_asy"] if cfg["args"]["vce"] == "plugin" else cfg["sd_jk"]
            t_key, p_key = (
                ("t_asy", "p_asy") if cfg["args"]["vce"] == "plugin" else ("t_jk", "p_jk")
            )
            np.testing.assert_allclose(
                res.se_left, _num(sd_block["left"]), rtol=rtol, err_msg=f"{label}: se_left"
            )
            np.testing.assert_allclose(
                res.se_right, _num(sd_block["right"]), rtol=rtol, err_msg=f"{label}: se_right"
            )
            np.testing.assert_allclose(
                res.se_diff, _num(sd_block["diff"]), rtol=rtol, err_msg=f"{label}: se_diff"
            )
            np.testing.assert_allclose(
                res.t_stat,
                _num(cfg["test"][t_key]),
                rtol=rtol,
                atol=1e-8,  # inherits f_diff's cancellation (t = diff/sd,
                # with sd ~ 0.01-0.1 amplifying the absolute noise)
                err_msg=f"{label}: t_stat",
            )
            np.testing.assert_allclose(
                res.p_value,
                _num(cfg["test"][p_key]),
                rtol=rtol,
                atol=1e-8,  # p inherits t_stat's cancellation-noise floor
                # (dp = phi(t) * dt <= dt), plus ~1e-11 libm-vs-pnorm
                # tail differences
                err_msg=f"{label}: p_value",
            )

            # conventional block (all=TRUE configs) - every populated field
            if cfg["args"]["all"]:
                np.testing.assert_allclose(
                    res.f_left_conventional,
                    _num(cfg["hat_p"]["left"]),
                    rtol=rtol,
                    err_msg=f"{label}: f_left_conventional",
                )
                np.testing.assert_allclose(
                    res.f_right_conventional,
                    _num(cfg["hat_p"]["right"]),
                    rtol=rtol,
                    err_msg=f"{label}: f_right_conventional",
                )
                np.testing.assert_allclose(
                    res.f_diff_conventional,
                    _num(cfg["hat_p"]["diff"]),
                    rtol=rtol,
                    atol=1e-9,  # same cancellation floor as f_diff
                    err_msg=f"{label}: f_diff_conventional",
                )
                sd_p = cfg["sd_asy_p"] if cfg["args"]["vce"] == "plugin" else cfg["sd_jk_p"]
                np.testing.assert_allclose(
                    res.se_left_conventional,
                    _num(sd_p["left"]),
                    rtol=rtol,
                    err_msg=f"{label}: se_left_conventional",
                )
                np.testing.assert_allclose(
                    res.se_right_conventional,
                    _num(sd_p["right"]),
                    rtol=rtol,
                    err_msg=f"{label}: se_right_conventional",
                )
                np.testing.assert_allclose(
                    res.se_diff_conventional,
                    _num(sd_p["diff"]),
                    rtol=rtol,
                    err_msg=f"{label}: se_diff_conventional",
                )
                np.testing.assert_allclose(
                    res.t_stat_conventional,
                    _num(cfg["test_p"][t_key]),
                    rtol=rtol,
                    atol=1e-8,  # same cancellation floor as t_stat
                    err_msg=f"{label}: t_stat_conventional",
                )
                np.testing.assert_allclose(
                    res.p_value_conventional,
                    _num(cfg["test_p"][p_key]),
                    rtol=rtol,
                    atol=1e-8,  # same |dp| <= |dt| floor as p_value
                    err_msg=f"{label}: p_value_conventional",
                )

            # sample counts + bandwidths
            assert res.n == cfg["N"]["full"], f"{label}: n"
            assert res.n_left == cfg["N"]["left"], f"{label}: n_left"
            assert res.n_right == cfg["N"]["right"], f"{label}: n_right"
            assert res.n_eff_left == cfg["N"]["eff_left"], f"{label}: n_eff_left"
            assert res.n_eff_right == cfg["N"]["eff_right"], f"{label}: n_eff_right"
            np.testing.assert_allclose(
                res.h_left, _num(cfg["h"]["left"]), rtol=rtol, err_msg=f"{label}: h_left"
            )
            np.testing.assert_allclose(
                res.h_right, _num(cfg["h"]["right"]), rtol=rtol, err_msg=f"{label}: h_right"
            )
            assert res.bandwidth_method == (
                "manual" if cfg["bwselectl"] == "mannual" else "estimated"
            ), f"{label}: bandwidth_method (R spells its manual mode 'mannual')"
            assert res.masspoints_adjusted == bool(
                cfg["masspoints_flag"]
            ), f"{label}: masspoints_adjusted"

            # the standalone rdbwdensity h-table (data-driven configs)
            if "bw_table" in cfg:
                assert res.bandwidths is not None, f"{label}: bandwidths"
                np.testing.assert_allclose(
                    res.bandwidths["bw"].to_numpy(),
                    [_num(v) for v in cfg["bw_table"]["bw"]],
                    rtol=rtol,
                    err_msg=f"{label}: bw_table.bw",
                )
                np.testing.assert_allclose(
                    res.bandwidths["variance"].to_numpy(),
                    [_num(v) for v in cfg["bw_table"]["variance"]],
                    rtol=rtol,
                    err_msg=f"{label}: bw_table.variance",
                )
                np.testing.assert_allclose(
                    res.bandwidths["bias_sq"].to_numpy(),
                    [_num(v) for v in cfg["bw_table"]["biassq"]],
                    rtol=max(rtol, 1e-7),  # the squared bias comes from the
                    # order-(p+2) PILOT fit, whose float noise is ~1e-8
                    # relative on tied data; h itself dampens it below 1e-9
                    # (h ~ B^(-2/(2p+1))) and is compared at full precision
                    atol=1e-16,  # bias^2 terms cross zero at machine scale
                    err_msg=f"{label}: bw_table.bias_sq",
                )
            else:
                assert res.bandwidths is None, f"{label}: bandwidths not None on manual h"
            checked += 1
        # the documented 47-config matrix ran in full, nothing silently
        # dropped (bump this count when the generator gains configs).
        # Completing this loop is also the companion assertion to the
        # repeated-values design-guard test: every config fit without
        # tripping the unique-support precondition, and parity against the
        # finite golden values above proves finiteness
        assert checked == 47


# --------------------------------------------------------------------------- #
# Paper anchors (CJM 2020 Table 1, Head Start)
# --------------------------------------------------------------------------- #


@pytest.fixture(scope="module")
def headstart():
    if not HEADSTART_PATH.exists():
        pytest.skip("vendored Head Start CSV not found")
    return pd.read_csv(HEADSTART_PATH)["povrate60"].dropna().to_numpy(dtype=float)


@pytest.fixture(scope="module")
def fitted():
    rng = np.random.default_rng(73)
    return _fit_quiet(RDDensityTest(), rng.normal(size=1500))


class TestPaperAnchors:
    """CJM 2020 Table 1 (Head Start, cutoff 59.1984). R rddensity 3.0
    reproduces the published p=1/p=2 rows at display precision; the p=3 rows
    drifted across package versions (published h_left=32.487 vs 3.0's
    22.135 on the 'each' row) - the anchors below therefore pin the p=1/p=2
    PUBLISHED values and, for p=3, the R-3.0-verified behavior (drift
    documented here and in the PR body)."""

    def test_sample_counts(self, headstart):
        assert int(np.sum(headstart < 59.1984)) == 2504
        assert int(np.sum(headstart >= 59.1984)) == 300

    @pytest.mark.parametrize(
        "p, bwselect, t_published, p_published",
        [
            (1, "each", 0.024, 0.981),
            (2, "each", -1.146, 0.252),
            (1, "diff", -1.355, 0.175),
            (2, "diff", -0.515, 0.607),
        ],
    )
    def test_published_rows(self, headstart, p, bwselect, t_published, p_published):
        res = _fit_quiet(RDDensityTest(cutoff=59.1984, p=p, bwselect=bwselect), headstart)
        assert res.t_stat == pytest.approx(t_published, abs=2e-3)
        assert res.p_value == pytest.approx(p_published, abs=2e-3)

    def test_p3_r30_drift_documented(self, headstart):
        # published Table 1: each -> h_l=32.487, T=-1.083; rddensity 3.0
        # gives h_l~22.135, T~-0.760 (bandwidth-selector drift across
        # versions). We pin the R-3.0 behavior our port targets.
        res = _fit_quiet(RDDensityTest(cutoff=59.1984, p=3, bwselect="each"), headstart)
        assert res.h_left == pytest.approx(22.135, abs=5e-3)
        assert res.t_stat == pytest.approx(-0.7598, abs=2e-3)
        assert abs(res.h_left - 32.487) > 5  # the published value is NOT reproduced


# --------------------------------------------------------------------------- #
# Methodology (R-free)
# --------------------------------------------------------------------------- #


def _moment_g_minus(p: int, kernel: str) -> np.ndarray:
    """Test-local minus-side Gamma over (-1, 0) with the minus basis,
    computed by direct closed-form integration (no production `_minus`
    helper exists - R builds every minus-side matrix by Psi-conjugation)."""
    # substitute u -> -u: Gamma_minus[i, j] over (-1,0) equals the (0,1)
    # integral of the reflected integrand; integrate directly instead via
    # the identity-free route: G^-[i,j] = int_{-1}^0 k(-y)... To stay
    # independent of the reflection identity under test, integrate the
    # minus-side double integral numerically at high resolution.
    from scipy import integrate as _si

    kpoly = _KERNEL_POLY_01[kernel]

    def k(u):
        return _poly_eval(kpoly, abs(u))

    out = np.empty((p + 1, p + 1))
    for i in range(p + 1):
        for j in range(p + 1):

            def inner(y, _i=i, _j=j):
                lo, _ = _si.quad(lambda u: u ** (_i + 1) * k(u), -1.0, y, epsabs=1e-13)
                hi, _ = _si.quad(lambda u: u**_i * k(u), y, 0.0, epsabs=1e-13)
                return k(y) * (y**_j * lo + y ** (_j + 1) * hi)

            val, _ = _si.quad(inner, -1.0, 0.0, epsabs=1e-12, limit=200)
            out[i, j] = val
    return out


class TestMethodology:
    @pytest.mark.parametrize("kernel", ["triangular", "epanechnikov", "uniform"])
    @pytest.mark.parametrize("p", [1, 2, 3, 4, 5, 6, 7])
    def test_reflection_identity_generators(self, p, kernel):
        """SA proof 7.17: Gamma_minus = Psi Gamma_plus Psi + the two
        rank-one corrections (generator-level check of our closed-form
        integrators; INDEPENDENT of the variance path, which - matching R
        and SA Lemma 13 - uses the uncorrected Psi Gamma_plus Psi)."""
        if p > 4 and kernel != "triangular":
            pytest.skip("high-order quadrature reference kept to one kernel")
        g_plus = _embed_plus(_moment_g(p, kernel), p)
        s_plus = _embed_plus(_moment_s(p, kernel), p)
        psi = _psi_matrix(p)
        e0 = np.zeros(p + 2)
        e0[0] = 1.0
        e1m = np.zeros(p + 2)
        e1m[1] = 1.0
        # SA 7.17: Gamma_- = Psi Gamma_+ Psi + S_- e1- e0' S_- + S_- e0 e1-' S_-
        s_minus = psi @ s_plus @ psi
        expected = (
            psi @ g_plus @ psi
            + s_minus @ np.outer(e1m, e0) @ s_minus
            + s_minus @ np.outer(e0, e1m) @ s_minus
        )
        # reference minus-side Gamma via independent quadrature, embedded
        g_minus_raw = _moment_g_minus(p, kernel)
        g_minus = np.zeros((p + 2, p + 2))
        g_minus[0, 0] = g_minus_raw[0, 0]
        g_minus[0, 1] = g_minus_raw[0, 1]
        g_minus[1, 0] = g_minus_raw[1, 0]
        g_minus[1, 1] = g_minus_raw[1, 1]
        if p > 1:
            g_minus[0, 3:] = g_minus_raw[0, 2:]
            g_minus[3:, 0] = g_minus_raw[2:, 0]
            g_minus[1, 3:] = g_minus_raw[1, 2:]
            g_minus[3:, 1] = g_minus_raw[2:, 1]
            g_minus[3:, 3:] = g_minus_raw[2:, 2:]
        np.testing.assert_allclose(g_minus, expected, atol=5e-9)

    def test_joint_vs_separate_rescaling(self):
        """Under the rank EDF (0:(N-1))/(N-1), a separate per-side fit (the
        side's own EDF on a plain one-sided basis) equals the joint fit's
        side times (N-1)/(n_side - 1) - EXACTLY, because the interleaved
        joint basis is block-diagonal across sides and regression is linear
        in the regressand. The CJM paper's n/n_side factors instead apply to
        the paper's (1/n)*sum EDF, which neither R nor this port implements
        (the distinction is documented in the result docstring)."""
        rng = np.random.default_rng(7)
        x = np.sort(rng.normal(size=600))
        n = len(x)
        n_left = int(np.sum(x < 0))
        hl, hr = 0.6, 0.7
        q = 3
        y = np.arange(n) / (n - 1)
        w = (x >= -hl) & (x <= hr)
        xw, yw = x[w], y[w]
        n_lh = int(np.sum(xw < 0))
        joint = _rddensity_fv(
            yw,
            xw,
            n,
            n_lh,
            len(xw) - n_lh,
            hl,
            hr,
            q,
            1,
            "triangular",
            "unrestricted",
            "jackknife",
            False,
        )

        # separate left fit: the left subsample's own rank EDF on a plain
        # one-sided polynomial basis with the same kernel window
        left_sample = x[x < 0]
        y_sep = np.arange(n_left) / (n_left - 1)
        in_win = left_sample >= -hl
        u = left_sample[in_win] / hl
        design = np.column_stack([u**k for k in range(q + 1)])
        wts = (1.0 + u) / hl
        dw = design * wts[:, None]
        beta = np.linalg.solve(dw.T @ design, dw.T @ y_sep[in_win])
        f_sep_left = beta[1] / hl  # slope coefficient, unscaled

        factor = (n - 1) / (n_left - 1)
        assert f_sep_left == pytest.approx(joint[0, 0] * factor, rel=1e-12)
        # and the paper's n/n_left factor demonstrably differs
        assert f_sep_left != pytest.approx(joint[0, 0] * n / n_left, rel=1e-6)

    def test_affine_equivariance(self):
        rng = np.random.default_rng(11)
        x = rng.normal(size=1500)
        df1 = pd.DataFrame({"x": x})
        df2 = pd.DataFrame({"x": 3.5 * x + 10.0})
        r1 = _fit_quiet(RDDensityTest(cutoff=0.0), x)
        r2 = _fit_quiet(RDDensityTest(cutoff=10.0), 3.5 * x + 10.0)
        assert r1.t_stat == pytest.approx(r2.t_stat, rel=1e-9)
        # p = 2*Phi(-|t|) inherits the t-stat's relative error amplified by
        # 2*|t|*phi(|t|)/p (~5.9x at this seed's |t|~2.26), so its tolerance
        # must sit above the t-stat's or BLAS-kernel rounding differences
        # across CI runners can trip it (run #3384: rel diff 1.15e-9 on
        # ubuntu py3.14 only).
        assert r1.p_value == pytest.approx(r2.p_value, rel=1e-8)
        # densities scale by 1/s
        assert r1.f_left == pytest.approx(r2.f_left * 3.5, rel=1e-9)
        assert df1 is not df2

    def test_masspoint_idempotence_on_tie_free_data(self):
        rng = np.random.default_rng(13)
        x = rng.normal(size=800)
        r_adjust = _fit_quiet(RDDensityTest(masspoints="adjust"), x)
        r_off = _fit_quiet(RDDensityTest(masspoints="off"), x)
        assert r_adjust.f_diff == r_off.f_diff
        assert r_adjust.se_diff == r_off.se_diff
        assert r_adjust.t_stat == r_off.t_stat
        assert not r_adjust.masspoints_adjusted

    def test_side_of_only_repeated_values_raises(self):
        # the CJM review checklist's second required mass-point case: one
        # side is a single repeated value -> the unique-support design
        # guard fires deterministically (R returns finite garbage here)
        x = np.concatenate(
            [np.full(400, -1.0), np.abs(np.random.default_rng(5).normal(size=600)) + 0.001]
        )
        with pytest.raises(ValueError, match="unique running-variable value"):
            _fit_quiet(RDDensityTest(h=1.5, masspoints="off"), x)

    def test_jackknife_window_vs_literal(self):
        """Our (and R's) jackknife builds the leave-one-out projection from
        WINDOW rows only; the SA Section 5.2 literal U_hat double sum keeps
        every observation eligible as the non-localized pair member. Lock
        that (a) the two constructions genuinely differ on a fixture where
        the window excludes data, and (b) ours is the windowed one (goldens
        pin the R match)."""
        rng = np.random.default_rng(17)
        x = np.sort(rng.normal(size=80))
        n = len(x)
        h = 0.5
        q = 2
        y = np.arange(n) / (n - 1)
        w = (x >= -h) & (x <= h)
        xw, yw = x[w], y[w]
        n_lh = int(np.sum(xw < 0))
        fv = _rddensity_fv(
            yw,
            xw,
            n,
            n_lh,
            len(xw) - n_lh,
            h,
            h,
            q,
            1,
            "triangular",
            "unrestricted",
            "jackknife",
            False,
        )
        v_windowed = fv[2, 1]

        # brute-force SA-literal U_hat construction on the same fit
        left = xw < 0
        xp = np.zeros((len(xw), 2 * q + 2))
        hp = np.empty(2 * q + 2)
        for j in range(1, 2 * q + 3):
            if j % 2 == 1:
                power = (j - 1) // 2
                xp[left, j - 1] = (xw[left] / h) ** power
                hp[j - 1] = h**power
            else:
                power = (j - 2) // 2
                xp[~left, j - 1] = (xw[~left] / h) ** power
                hp[j - 1] = h**power
        kw = np.where(left, (1 + xw / h) / h, (1 - xw / h) / h)
        xpw = xp * kw[:, None]
        s_inv = np.linalg.inv(xpw.T @ xp)
        beta_scaled = s_inv @ (xpw.T @ yw)  # scaled-basis coefficients
        # literal: for window obs i, U_1(x_i)-style row over ALL n obs j
        resid = yw - xp @ beta_scaled
        l_literal = np.zeros_like(xpw)
        for i_w, xi in enumerate(xw):
            # sum over every sample obs j != i of the localized term of
            # U_hat: r_p(x_k)(1(x_j <= x_k) - fit_k) K(x_k) evaluated with
            # x_k = window rows, i.e. out-of-window j still contribute
            # through their indicators
            indicator = (x <= xi).sum() - 1  # j != i, x sorted
            l_literal[i_w] = xpw[i_w] * (indicator / (n - 1) - (yw[i_w] - resid[i_w]))
        v_lit_mat = np.diag(1 / hp) @ s_inv @ (l_literal.T @ l_literal) @ s_inv @ np.diag(1 / hp)
        v_literal = v_lit_mat[2, 2] + v_lit_mat[3, 3] - 2 * v_lit_mat[2, 3]
        # the two constructions differ (the deviation is real, documented)
        assert abs(v_windowed - v_literal) / abs(v_windowed) > 1e-6

    def test_restricted_h0_symmetric(self):
        rng = np.random.default_rng(19)
        half = np.abs(rng.normal(size=1000))
        x = np.concatenate([-half, np.abs(rng.normal(size=1000))])
        res = _fit_quiet(RDDensityTest(fitselect="restricted", h=1.0), x)
        assert abs(res.f_diff) < 0.15  # symmetric by construction
        # sum ~ 2x each side
        assert res.f_left + res.f_right == pytest.approx(2 * (res.f_left + res.f_right) / 2)
        assert res.p_value > 0.01

    def test_q_default_resolution(self):
        rng = np.random.default_rng(23)
        x = rng.normal(size=1200)
        r_default = _fit_quiet(RDDensityTest(), x)
        r_explicit = _fit_quiet(RDDensityTest(q=3), x)
        assert r_default.q == 3
        assert r_default.f_diff == r_explicit.f_diff
        assert r_default.t_stat == r_explicit.t_stat

    def test_q_equals_p_is_conventional(self):
        rng = np.random.default_rng(29)
        x = rng.normal(size=1200)
        r_qp = _fit_quiet(RDDensityTest(q=2, h=0.8), x)
        r_all = _fit_quiet(RDDensityTest(h=0.8, report_all=True), x)
        assert r_qp.f_diff == pytest.approx(r_all.f_diff_conventional, rel=1e-12)
        assert r_qp.t_stat == pytest.approx(r_all.t_stat_conventional, rel=1e-12)

    def test_floors_move_bandwidth_in_binding_direction(self):
        rng = np.random.default_rng(31)
        x = rng.normal(size=400)
        r_small = _fit_quiet(RDDensityTest(n_local_min=0, n_unique_min=0), x)
        r_large = _fit_quiet(RDDensityTest(n_local_min=150, n_unique_min=150), x)
        assert r_large.h_left >= r_small.h_left
        assert r_large.h_right >= r_small.h_right
        assert r_large.h_left > r_small.h_left or r_large.h_right > r_small.h_right


# --------------------------------------------------------------------------- #
# Validation, errors, warnings
# --------------------------------------------------------------------------- #


class TestValidationAndErrors:
    @pytest.mark.parametrize(
        "kwargs, match",
        [
            ({"p": 0}, "p must be"),
            ({"p": 8}, "p must be"),
            ({"p": 2.5}, "p must be"),
            ({"q": 1, "p": 2}, "q cannot be smaller"),
            ({"fitselect": "nope"}, "fitselect"),
            ({"kernel": "gaussian"}, "kernel"),
            ({"vcov_type": "hc0"}, "vcov_type"),
            ({"h": -1.0}, "positive"),
            ({"h": (0.5, -1.0)}, "positive"),
            ({"h": (1.0, 2.0, 3.0)}, "length-2"),
            ({"bwselect": "mserd"}, "bwselect"),
            ({"fitselect": "restricted", "bwselect": "each"}, "not available"),
            ({"fitselect": "restricted", "h": (0.5, 0.7)}, "equal"),
            ({"masspoints": "on"}, "masspoints"),
            ({"regularize": 1}, "regularize"),
            ({"n_local_min": -2}, "ceil"),
            ({"n_local_min": np.inf}, "finite"),
            ({"n_local_min": True}, "real number"),
            ({"report_all": "yes"}, "report_all"),
        ],
    )
    def test_constructor_rejects(self, kwargs, match):
        with pytest.raises(ValueError, match=match):
            RDDensityTest(**kwargs)

    def test_floor_ceiling_matches_r(self):
        # R accepts any numeric with ceiling(v) >= 0: -0.5 resolves to 0
        rng = np.random.default_rng(37)
        x = rng.normal(size=500)
        r_neg = _fit_quiet(RDDensityTest(n_local_min=-0.5, n_unique_min=-0.5), x)
        r_zero = _fit_quiet(RDDensityTest(n_local_min=0, n_unique_min=0), x)
        assert r_neg.n_local_min == 0
        assert r_neg.h_left == r_zero.h_left

    def test_missing_column(self):
        with pytest.raises(ValueError, match="not found"):
            RDDensityTest().fit(pd.DataFrame({"a": [1.0, 2.0]}), running="x")

    def test_cutoff_outside_range(self):
        x = np.linspace(1.0, 2.0, 100)
        with pytest.raises(ValueError, match="within the range"):
            _fit_quiet(RDDensityTest(cutoff=0.0), x)

    def test_all_one_side_raises_via_range_check(self):
        x = np.linspace(1.0, 2.0, 100)
        with pytest.raises(ValueError, match="within the range"):
            _fit_quiet(RDDensityTest(cutoff=0.5), x)

    def test_empty_and_all_nan_raise(self):
        df = pd.DataFrame({"x": [np.nan, np.nan, np.nan]})
        with pytest.raises(ValueError, match="No complete observations"):
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                RDDensityTest().fit(df, running="x")

    def test_one_observation_side_raises(self):
        # dedicated fixture: cutoff inside the range, left side n=1
        rng = np.random.default_rng(41)
        x = np.concatenate([[-0.5], np.abs(rng.normal(size=24)) + 0.01])
        with pytest.raises(ValueError, match="at least 2 observations"):
            _fit_quiet(RDDensityTest(cutoff=0.0), x)

    def test_nonnumeric_and_inf_dropped_with_warning(self):
        rng = np.random.default_rng(43)
        vals = list(rng.normal(size=200)) + [np.inf, -np.inf, "bad", None]
        df = pd.DataFrame({"x": pd.Series(vals, dtype=object)})
        with pytest.warns(UserWarning, match="Dropped 4 observation"):
            with warnings.catch_warnings():
                warnings.simplefilter("always")
                res = RDDensityTest(h=1.0).fit(df, running="x")
        assert res.n == 200

    def test_degenerate_bandwidth_guard(self, monkeypatch):
        import diff_diff.rddensity as mod

        rng = np.random.default_rng(47)
        x = rng.normal(size=300)

        for bad in (0.0, np.nan, np.inf):

            def fake_bw(*args, _bad=bad, **kwargs):
                hn = np.full((4, 3), 1.0)
                hn[:, 0] = _bad
                return hn

            monkeypatch.setattr(mod, "_rdbwdensity", fake_bw)
            with pytest.raises(ValueError, match="degenerate .* bandwidth"):
                _fit_quiet(RDDensityTest(), x)

    def test_restricted_plugin_variance_degenerate_injection(self):
        # f_l = 0 exactly makes the density-weighted combined Gram singular
        with pytest.warns(UserWarning, match="degenerate"):
            out = _restricted_plugin_variance(0.0, 0.3, 2, "triangular", 1000, 0.5)
        assert all(np.isnan(v) for v in out)

    def test_negative_density_warns(self):
        # solvable-but-degenerate data yields a finite negative left density
        # (R reports it silently; we warn and keep R-parity values). The
        # fixture is deterministic: a sparse left side receding from the
        # cutoff drives the boundary EDF slope negative under jackknife,
        # whose PSD variance stays valid - inference remains finite.
        rng = np.random.default_rng(7)
        x = np.concatenate([-2.0 + 0.3 * rng.random(40), 0.05 + 1.5 * rng.random(300)])
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            res = RDDensityTest(p=1, h=2.0, vcov_type="jackknife").fit(
                pd.DataFrame({"x": x}), running="x"
            )
        assert res.f_left < 0  # the fixture must actually go negative
        assert any("density is negative" in str(w.message).lower() for w in caught)
        # jackknife variance is PSD-valid here: R-parity finite inference
        assert np.isfinite(res.se_diff) and np.isfinite(res.p_value)

    def test_partial_invalid_plugin_variance_degrades_jointly(self):
        # a small negative side density makes the LEFT plug-in variance
        # contribution negative while the raw composed diff variance stays
        # positive; R reports finite (understated) sd_diff there - the port
        # degrades the composed SE and the test inference to NaN with it
        rng = np.random.default_rng(0)
        x = np.concatenate([-(0.3 + 1.6 * rng.random(40) ** 0.4), 0.02 + 1.9 * rng.random(300)])
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            res = RDDensityTest(p=1, h=2.0, vcov_type="plugin").fit(
                pd.DataFrame({"x": x}), running="x"
            )
        assert res.f_left < 0
        assert np.isnan(res.se_left)
        assert np.isfinite(res.se_right)
        for field in (res.se_diff, res.t_stat, res.p_value):
            assert np.isnan(field)
        messages = [str(w.message).lower() for w in caught]
        assert any("variance estimate" in m for m in messages)
        assert any("density is negative" in m for m in messages)

    def test_conventional_inference_data_driven_bandwidth_warns(self):
        # CJM 2020 Section 4: the conventional order-p test over-rejects at
        # the MSE-optimal bandwidth. R reports the numbers silently; the
        # port keeps the R-parity values (golden-pinned) but warns whenever
        # conventional inference meets a DATA-DRIVEN bandwidth
        rng = np.random.default_rng(79)
        df = pd.DataFrame({"x": rng.normal(size=1200)})
        # q == p: the headline itself is the conventional fit
        with pytest.warns(UserWarning, match="over-rejects"):
            res_qp = RDDensityTest(p=2, q=2).fit(df, running="x")
        assert np.isfinite(res_qp.p_value)  # R-parity values stand
        # report_all: the conventional block at the selected bandwidth
        with pytest.warns(UserWarning, match="over-rejects"):
            res_all = RDDensityTest(report_all=True).fit(df, running="x")
        assert np.isfinite(res_all.p_value_conventional)
        # manual h: undersmoothing is the caller's responsibility - silent
        for est in (
            RDDensityTest(p=2, q=2, h=0.8),
            RDDensityTest(report_all=True, h=0.8),
        ):
            with warnings.catch_warnings(record=True) as caught:
                warnings.simplefilter("always")
                est.fit(df, running="x")
            assert not any("over-reject" in str(w.message) for w in caught)

    @pytest.mark.parametrize("kernel", ["triangular", "epanechnikov"])
    @pytest.mark.parametrize("vce", ["jackknife", "plugin"])
    def test_boundary_zero_weight_rank_deficiency_fails_loud(self, kernel, vce):
        # points sitting EXACTLY at the bandwidth boundary get kernel weight
        # 0 under triangular/epanechnikov (and the regularization range
        # clamp hits |x| = h exactly), so a side with order+1 unique values
        # but one of them at the boundary is rank deficient - R's
        # solve(tol=0) returns finite garbage; the weight-aware
        # unique-support guard raises instead
        left_vals = np.array([-1.0, -0.5, -0.3, -0.1])
        right_vals = np.array([0.1, 0.35, 0.6, 1.0])
        x = np.concatenate([np.repeat(left_vals, 10), np.repeat(right_vals, 10)])
        df = pd.DataFrame({"x": x})
        # default p=2 -> the robust fit runs at order q=3, needing 4
        # positive-weight unique values per side; the boundary point leaves 3
        with pytest.raises(ValueError, match="unique running-variable value"):
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                RDDensityTest(h=1.0, kernel=kernel, vcov_type=vce, masspoints="off").fit(
                    df, running="x"
                )
        # the uniform kernel keeps positive weight at the boundary: the same
        # design is genuinely full rank and must still fit
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res = RDDensityTest(h=1.0, kernel="uniform", vcov_type=vce, masspoints="off").fit(
                df, running="x"
            )
        assert np.isfinite(res.f_diff)

    def test_nan_selector_variance_fails_loud(self):
        # a negative pilot density NaNs the plug-in selector variance for
        # the left row; R's cleanup then errors opaquely (NA in an `if`),
        # and the NaN->0 bandwidth cleanup plus regularization floors would
        # otherwise rescue the row into a positive bandwidth whose MSE
        # objective is undefined - the port raises descriptively instead of
        # reporting finite inference from it
        rng = np.random.default_rng(0)
        x = np.concatenate([-(0.3 + 1.6 * rng.random(40) ** 0.4), 0.02 + 1.9 * rng.random(300)])
        df = pd.DataFrame({"x": x})
        for bwselect in ("each", "comb"):
            with pytest.raises(ValueError, match="pilot variance"):
                with warnings.catch_warnings():
                    warnings.simplefilter("ignore")
                    RDDensityTest(p=2, vcov_type="plugin", bwselect=bwselect).fit(df, running="x")

    def test_single_invalid_marginal_degrades_both_blocks(self):
        # inject an invalid LEFT marginal variance only (right and the raw
        # composed diff/sum stay valid) into both the robust and the
        # conventional block: the composed inference must degrade in each
        from unittest import mock

        rng = np.random.default_rng(73)
        x = rng.normal(size=800)
        import diff_diff.rddensity as mod

        real_fv = mod._rddensity_fv

        def wreck_left(*args, **kwargs):
            out = real_fv(*args, **kwargs)
            out[0, 1] = -1.0  # left jackknife marginal invalid
            return out

        with mock.patch.object(mod, "_rddensity_fv", wreck_left):
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                res = RDDensityTest(h=0.8, report_all=True).fit(pd.DataFrame({"x": x}), running="x")
        for block in ("", "_conventional"):
            assert np.isnan(getattr(res, f"se_left{block}"))
            assert np.isfinite(getattr(res, f"se_right{block}"))
            for name in ("se_diff", "t_stat", "p_value"):
                assert np.isnan(getattr(res, f"{name}{block}"))

    def test_bandwidth_exceeds_range_warns(self):
        rng = np.random.default_rng(59)
        x = rng.uniform(-1.0, 1.0, 500)
        with pytest.warns(UserWarning, match="greater than the range"):
            with warnings.catch_warnings():
                warnings.simplefilter("always")
                RDDensityTest(h=5.0).fit(pd.DataFrame({"x": x}), running="x")

    def test_small_effective_sample_warns(self):
        rng = np.random.default_rng(61)
        x = rng.normal(size=2000)
        with pytest.warns(UserWarning, match="Fewer than 20 effective"):
            with warnings.catch_warnings():
                warnings.simplefilter("always")
                RDDensityTest(h=0.02, masspoints="off").fit(pd.DataFrame({"x": x}), running="x")

    def test_masspoints_warnings_and_off_suppression(self):
        rng = np.random.default_rng(67)
        x = np.round(rng.normal(size=1500), 1)
        df = pd.DataFrame({"x": x})
        with pytest.warns(UserWarning, match="mass-point adjusted"):
            with warnings.catch_warnings():
                warnings.simplefilter("always")
                r_adj = RDDensityTest(masspoints="adjust").fit(df, running="x")
        with pytest.warns(UserWarning, match="WITHOUT mass-point adjustment"):
            with warnings.catch_warnings():
                warnings.simplefilter("always")
                r_check = RDDensityTest(masspoints="check").fit(df, running="x")
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            r_off = RDDensityTest(masspoints="off").fit(df, running="x")
        assert not any("mass" in str(w.message).lower() for w in caught)
        # check == off numerically (no adjustment), adjust differs
        assert r_check.f_diff == r_off.f_diff
        assert r_adj.masspoints_adjusted and not r_check.masspoints_adjusted
        assert r_adj.f_diff != r_check.f_diff

    def test_degraded_inference_nan_joint(self):
        # negative/zero/non-finite variance -> NaN SEs and joint NaN
        # inference in BOTH blocks; point estimates stand
        from unittest import mock

        rng = np.random.default_rng(71)
        x = rng.normal(size=800)
        import diff_diff.rddensity as mod

        real_fv = mod._rddensity_fv

        for bad in (-1.0, 0.0, np.nan):

            def wrecked(*args, _bad=bad, **kwargs):
                out = real_fv(*args, **kwargs)
                out[:, 1] = _bad if not np.isnan(_bad) else np.nan
                if _bad == -1.0:
                    # mimic R's negativity path: fv itself NaNs negatives,
                    # so inject the raw negative before that cleanup is
                    # equivalent to NaN here - keep the raw value to hit
                    # the sqrt(<0) path
                    out[:, 1] = -1.0
                return out

            with mock.patch.object(mod, "_rddensity_fv", wrecked):
                with warnings.catch_warnings():
                    warnings.simplefilter("ignore")
                    res = RDDensityTest(h=0.8, report_all=True).fit(
                        pd.DataFrame({"x": x}), running="x"
                    )
            assert np.isfinite(res.f_diff)
            assert np.isfinite(res.f_diff_conventional)
            for field in (
                res.se_left,
                res.se_right,
                res.se_diff,
                res.t_stat,
                res.p_value,
                res.se_left_conventional,
                res.se_right_conventional,
                res.se_diff_conventional,
                res.t_stat_conventional,
                res.p_value_conventional,
            ):
                assert np.isnan(field), f"bad={bad}: {field}"


# --------------------------------------------------------------------------- #
# API contracts
# --------------------------------------------------------------------------- #


class TestAPIContracts:

    def test_result_schema(self, fitted):
        res = fitted
        for name, typ in [
            ("t_stat", float),
            ("p_value", float),
            ("f_left", float),
            ("f_right", float),
            ("f_diff", float),
            ("se_left", float),
            ("se_right", float),
            ("se_diff", float),
            ("n", int),
            ("n_left", int),
            ("n_right", int),
            ("n_eff_left", int),
            ("n_eff_right", int),
            ("h_left", float),
            ("h_right", float),
            ("cutoff", float),
            ("p", int),
            ("q", int),
        ]:
            assert isinstance(getattr(res, name), typ), name
        assert isinstance(res.bandwidths, pd.DataFrame)
        assert list(res.bandwidths.index) == ["left", "right", "diff", "sum"]
        assert list(res.bandwidths.columns) == ["bw", "variance", "bias_sq"]
        assert res.bandwidth_method == "estimated"
        assert res.bwselect == "comb"
        for name in ("f_left_conventional", "se_diff_conventional", "t_stat_conventional"):
            assert getattr(res, name) is None  # report_all=False

    def test_manual_h_contract(self):
        rng = np.random.default_rng(79)
        res = _fit_quiet(RDDensityTest(h=0.7, bwselect="diff"), rng.normal(size=900))
        assert res.bandwidths is None
        assert res.bandwidth_method == "manual"
        assert res.bwselect == "diff"  # user's request echoed, not overwritten

    def test_to_dataframe_shapes(self, fitted):
        df = fitted.to_dataframe()
        assert list(df.index) == ["left", "right", "diff"]
        assert list(df.columns) == ["estimate", "se", "t_stat", "p_value"]
        assert np.isnan(df.loc["left", "t_stat"])
        assert df.loc["diff", "t_stat"] == fitted.t_stat

        rng = np.random.default_rng(83)
        res_all = _fit_quiet(RDDensityTest(report_all=True), rng.normal(size=900))
        df_all = res_all.to_dataframe()
        assert list(df_all.index) == [
            "left",
            "right",
            "diff",
            "left_conventional",
            "right_conventional",
            "diff_conventional",
        ]

    def test_summary_behavioral(self, fitted):
        text = fitted.summary()
        assert "Manipulation Test" in text
        assert f"Number of obs:        {fitted.n}" in text
        assert "Robust" in text
        assert "Conventional" not in text  # report_all=False
        assert f"{fitted.t_stat:.4f}" in text
        assert f"{fitted.h_left:.4f}" in text

        rng = np.random.default_rng(89)
        res_all = _fit_quiet(RDDensityTest(report_all=True), rng.normal(size=900))
        assert "Conventional" in res_all.summary()

    def test_summary_q_equals_p_labels_conventional(self):
        # R labels the headline "Robust" even when q == p (the conventional
        # test) and with all=TRUE prints the identical statistic twice; the
        # port labels by the actual procedure and suppresses the duplicate
        # (documented display Deviation from R)
        rng = np.random.default_rng(101)
        x = rng.normal(size=900)
        text = _fit_quiet(RDDensityTest(p=2, q=2, h=0.8), x).summary()
        assert "Conventional" in text
        assert "Robust" not in text
        # report_all + q == p: a single Conventional row, no duplicate
        text_all = _fit_quiet(RDDensityTest(p=2, q=2, h=0.8, report_all=True), x).summary()
        assert text_all.count("Conventional") == 1
        assert "Robust" not in text_all

    def test_set_params_staleness(self):
        est = RDDensityTest()
        est.set_params(p=3)
        rng = np.random.default_rng(97)
        res = _fit_quiet(est, rng.normal(size=1500))
        assert res.p == 3
        assert res.q == 4  # q=None re-resolves against the new p
        assert res.n_local_min == 24  # 20 + p + 1 re-resolves
        assert res.n_unique_min == 24
