"""R-parity golden-fixture tests for ChangesInChanges (CiC) and QDiD vs qte 1.3.1.

Fixture: benchmarks/data/qte_golden.json, generated by
benchmarks/R/generate_qte_golden.R (qte pinned to 1.3.1 and quantreg to 6.1
there and in benchmarks/R/requirements.R). Point fixtures were generated with
se=FALSE and are deterministic; the se_block was generated seeded
(set.seed(42), iters=999, cores=1 - qte's default cores=2 forks and is NOT
reproducible even seeded) and is compared statistically since bootstrap draws
cannot be replicated across languages.

Tolerances:
- POINT_ATOL = 1e-10 for unconditional end-to-end ATT/QTE values (means and
  type-7 interpolation differ from R by ~1 ulp; type-1 selections are
  bit-exact).
- Covariate (xformla) end-to-end values are TIE-SELECTION-BOUNDED, not
  ~1e-10: (i) the QR check loss can have a non-trivial optimal face and the
  two exact solvers (R br simplex, scipy HiGHS) then select different
  vertices with identical loss; (ii) R's Fhat knots are often EXACTLY tied
  across adjacent taus (shared interpolating basis) and predict.rqs orders
  ties by tau index, while Python's ~1e-15-different predictions break the
  ties by value - so a share of conditional ranks legitimately lands a grid
  step away. Both are selections among equally valid solutions. Hence:
  COV_ATT_ATOL / COV_QTE_ATOL are empirical tie-flip bounds: the committed
  fixtures measure worst 9.3e-3 / 8.1e-2 on this platform, and a 30-dataset
  randomized decomposition audit (5 DGP families incl. binary-covariate and
  ties-heavy cells; 2026-07-13) observed same-mechanism deviations up to
  3.5e-2 / 0.40 on adversarial data - the gates carry cross-platform margin
  because a different BLAS can flip DIFFERENT ties on the same fixture data,
  while a real composition bug errs at O(0.5-1). The audit's invariants:
  composition-on-R-coefficients exact 30/30 (worst 1.3e-15), 8910 LP solves
  all coefficient-matching or two-sided loss-equal (worst gap 3.2e-16, zero
  descent-probe failures), all 1586 rank flips attributed to the documented
  tie mechanisms, no directional bias (sign tests p=0.69/0.59). The
  CONVENTIONS are pinned at atol=0 by the qr_cases tests conditioned on R's
  stored coefficients/predictions, and the LP solver is proven exactly
  optimal per tau (equal coefficients OR equal check loss).
- Micro-fixtures: type-1 quantiles at atol=0 (pure order-statistic selection,
  bit-exact cross-language); type-7 at rtol=1e-15 (R's (1-h)*lo + h*hi vs
  numpy's lerp differ in the last ulp).
- SE parity: threshold = 0.40 if n_boot < 100 else 0.15 for the ATT SE and
  0.25 per-quantile (tail-quantile bootstrap SEs are noisier at any replicate
  count; both sides estimate the same scheme-identical bootstrap SD).
"""

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from diff_diff import ChangesInChanges, QDiD
from diff_diff.changes_in_changes import (
    _QR_TAU_GRID,
    _design_matrix,
    _fhat_eval,
    _qhat_eval,
    _quantile_type1,
    _quantile_type7,
    _rq_fit,
)

FIXTURE_PATH = Path(__file__).parent.parent / "benchmarks" / "data" / "qte_golden.json"

POINT_ATOL = 1e-10
COV_ATT_ATOL = 0.04
COV_QTE_ATOL = 0.25
QTE_VERSION = "1.3.1"
QUANTREG_VERSION = "6.1"


def _load_fixture():
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"Golden fixture {FIXTURE_PATH} missing - regenerate via "
            f"`Rscript benchmarks/R/generate_qte_golden.R`."
        )
    with open(FIXTURE_PATH) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def fixture():
    return _load_fixture()


@pytest.fixture(scope="module")
def probs(fixture):
    # Use the R-stored probs doubles: R's seq() and np.arange() can differ in
    # trailing ulps, and the quantile index arithmetic is sensitive to them.
    return np.asarray(fixture["metadata"]["probs"], dtype=float)


def _scenario_df(scenario):
    return pd.DataFrame({k: scenario["data"][k] for k in ("id", "period", "treat", "y")})


def _fit(df, method, mode, probs, n_bootstrap=0, seed=None, covariates=None):
    cls = ChangesInChanges if method == "cic" else QDiD
    est = cls(
        quantiles=probs,
        n_bootstrap=n_bootstrap,
        panel=(mode == "panel"),
        seed=seed,
    )
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return est.fit(
            df,
            outcome="y",
            treatment="treat",
            time="period",
            unit="id" if mode == "panel" else None,
            covariates=covariates,
        )


def _as_list(x):
    """jsonlite auto_unbox collapses single-element vectors to scalars."""
    return x if isinstance(x, list) else [x]


def test_metadata_versions_match(fixture):
    """The committed fixture must match the pinned qte AND quantreg versions
    (the covariate fixtures embed quantreg's rq/predict.rqs behavior)."""
    assert fixture["metadata"]["qte_version"] == QTE_VERSION
    assert fixture["metadata"]["quantreg_version"] == QUANTREG_VERSION


def test_metadata_cov_gates_match(fixture):
    """The fixture's self-described covariate gates stay in sync with this file."""
    assert fixture["metadata"]["cov_att_atol"] == COV_ATT_ATOL
    assert fixture["metadata"]["cov_qte_atol"] == COV_QTE_ATOL


def test_qr_tau_grid_is_r_seq_bit_exact(fixture):
    """_QR_TAU_GRID is pinned to R's exact seq(0.01, 0.99, 0.01) doubles.

    Natural numpy constructions differ at 15-25 of the 99 indices by one ulp,
    the Fhat rank values are drawn FROM this grid, and the Qhat knots sit ON
    it - exact-knot searchsorted lookups are ulp-sensitive (same lesson as
    _DEFAULT_QUANTILES).
    """
    np.testing.assert_array_equal(
        _QR_TAU_GRID, np.asarray(fixture["metadata"]["qr_taus"], dtype=float)
    )


def test_default_grid_is_r_seq_bit_exact(fixture, probs):
    """_DEFAULT_QUANTILES is pinned to R's exact seq(0.05, 0.95, 0.05) doubles.

    np.arange(0.05, 0.96, 0.05) differs from R at 5 of 19 indices by one ulp,
    and type-1 selection is ulp-sensitive on n*p integer boundaries - so the
    default is hardcoded and locked here against the R-stored fixture probs
    (local review P1).
    """
    from diff_diff.changes_in_changes import _DEFAULT_QUANTILES

    np.testing.assert_array_equal(_DEFAULT_QUANTILES, probs)


def test_default_grid_parity_end_to_end(fixture, probs):
    """quantiles=None reproduces the golden qte-default results exactly."""
    scenario = fixture["scenarios"].get("smalln_2x2_n60")
    if scenario is None:
        pytest.skip("smalln_2x2_n60 missing from fixture")
    df = _scenario_df(scenario)
    est = ChangesInChanges(n_bootstrap=0)  # default grid
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        res = est.fit(df, outcome="y", treatment="treat", time="period")
    np.testing.assert_allclose(
        res.quantile_effects["qte"].to_numpy(),
        np.asarray(scenario["results"]["cic_rcs"]["qte"], dtype=float),
        atol=POINT_ATOL,
        rtol=0,
    )


SCENARIOS = ["normal_2x2_n500", "lognormal_2x2_n300", "smalln_2x2_n60", "lalonde_psid"]
RESULT_KEYS = ["cic_panel", "cic_rcs", "qdid_panel", "qdid_rcs"]


@pytest.mark.parametrize("scenario_name", SCENARIOS)
@pytest.mark.parametrize("result_key", RESULT_KEYS)
def test_point_parity(fixture, probs, scenario_name, result_key):
    scenario = fixture["scenarios"].get(scenario_name)
    if scenario is None:
        pytest.skip(f"Scenario {scenario_name} missing from fixture")
    golden = scenario["results"][result_key]
    method, mode = result_key.rsplit("_", 1)

    res = _fit(_scenario_df(scenario), method, mode, probs)

    np.testing.assert_allclose(res.att, golden["ate"], atol=POINT_ATOL, rtol=0)
    np.testing.assert_allclose(
        res.quantile_effects["qte"].to_numpy(),
        np.asarray(golden["qte"], dtype=float),
        atol=POINT_ATOL,
        rtol=0,
    )


SCENARIOS_COV = ["cov1_2x2_n300", "cov2_2x2_n240"]
RESULT_KEYS_COV = ["cic_cov_panel", "cic_cov_rcs", "qdid_cov_panel", "qdid_cov_rcs"]


@pytest.mark.parametrize("scenario_name", SCENARIOS_COV)
@pytest.mark.parametrize("result_key", RESULT_KEYS_COV)
def test_covariate_point_parity(fixture, probs, scenario_name, result_key):
    """End-to-end covariate parity at the tie-selection bounds (see header)."""
    scenario = fixture["scenarios"].get(scenario_name)
    if scenario is None:
        pytest.skip(f"Scenario {scenario_name} missing from fixture")
    golden = scenario["results"][result_key]
    method, _, mode = result_key.split("_")
    covariates = _as_list(scenario["covariates"])
    df = pd.DataFrame({k: scenario["data"][k] for k in scenario["data"]})

    res = _fit(df, method, mode, probs, covariates=covariates)

    np.testing.assert_allclose(res.att, golden["ate"], atol=COV_ATT_ATOL, rtol=0)
    qte_diff = np.abs(
        res.quantile_effects["qte"].to_numpy() - np.asarray(golden["qte"], dtype=float)
    )
    np.testing.assert_allclose(qte_diff, 0.0, atol=COV_QTE_ATOL, rtol=0)
    # Sharpness floor: tie-selection only perturbs the handful of quantiles
    # whose rank lookup lands in a knot-tie group / degenerate-vertex region -
    # the REST must agree with R at machine precision. Measured tight counts
    # (this platform): CiC 17 and 15 of 19; QDiD 6 and 3 of 19 (own-cell ranks
    # are structurally knot-exact, so QDiD flips more; the randomized audit
    # confirms QDiD flips heavily on adversarial data). Floors sit well below
    # measured so a different BLAS/HiGHS build flipping different ties cannot
    # fail them, while a real composition bug (all 19 off) still does.
    min_tight = 10 if method == "cic" else 1
    n_tight = int(np.sum(qte_diff < 1e-8))
    assert n_tight >= min_tight, (
        f"{scenario_name}/{result_key}: only {n_tight}/19 quantiles within 1e-8 of R "
        f"(sharpness floor {min_tight}) - deviations are broader than tie-selection."
    )
    assert res.covariates == covariates
    assert np.isnan(res.q_lower) and np.isnan(res.q_upper)


class TestQRCases:
    """Convention anchors for the covariate branch, conditioned on R's stored
    intermediates so tie-selection cannot blur them (see the header docstring):
    the Fhat/Qhat step-function lookups and both estimators' compositions must
    be BIT-EXACT given R's stored prediction matrices, the dot products must
    match R's to the last ulp given R's coefficients, and the LP solver must
    be exactly optimal at every tau.
    """

    @staticmethod
    def _cells(case):
        covs = _as_list(case["covariates"])
        out = {}
        for ck, blk in case["cells"].items():
            out[ck] = {
                "y": np.asarray(blk["y"], dtype=float),
                "X": np.column_stack([np.asarray(blk[c], dtype=float) for c in covs]),
            }
        return out

    def test_predictions_match_given_r_coefficients(self, fixture):
        # Isolates dot-product arithmetic from step-function conventions.
        # Last-ulp tolerance rather than exact equality: 2-3-term dot products
        # are observed bit-identical to R on this platform, but BLAS/FMA
        # reassociation can differ by an ulp elsewhere (assert_allclose
        # convention for float linalg). The step-function convention tests
        # below stay exact - they consume R's STORED prediction matrices, so
        # no floating-point arithmetic sits between fixture and assertion.
        for name, case in fixture["qr_cases"].items():
            cells = self._cells(case)
            x10d = _design_matrix(cells["c10"]["X"])
            for cell_key, pred_key in (
                ("c00", "preds00_at_x10"),
                ("c01", "preds01_at_x10"),
                ("c10", "preds10_at_x10"),
            ):
                coef_r = np.asarray(case[f"coef{cell_key[1:]}"], dtype=float)
                np.testing.assert_allclose(
                    x10d @ coef_r,
                    np.asarray(case[pred_key], dtype=float),
                    rtol=1e-15,
                    atol=1e-300,
                    err_msg=f"prediction mismatch in '{name}' cell {cell_key}",
                )

    def test_fhat_qhat_conventions_bit_exact_given_r_predictions(self, fixture):
        # The predict.rqs Fhat/Qhat step-function ports and both compositions,
        # conditioned on R's prediction matrices: atol=0.
        for name, case in fixture["qr_cases"].items():
            cells = self._cells(case)
            y10 = cells["c10"]["y"]
            preds = {
                k: np.asarray(case[k], dtype=float)
                for k in ("preds00_at_x10", "preds01_at_x10", "preds10_at_x10")
            }
            ranks_cic = _fhat_eval(preds["preds00_at_x10"], _QR_TAU_GRID, y10)
            np.testing.assert_array_equal(
                ranks_cic,
                np.asarray(case["cic_ranks"], dtype=float),
                err_msg=f"CiC ranks mismatch in '{name}'",
            )
            y0t_cic = _qhat_eval(preds["preds01_at_x10"], _QR_TAU_GRID, ranks_cic)
            np.testing.assert_array_equal(
                y0t_cic,
                np.asarray(case["cic_y0t"], dtype=float),
                err_msg=f"CiC imputations mismatch in '{name}'",
            )
            ranks_qdid = _fhat_eval(preds["preds10_at_x10"], _QR_TAU_GRID, y10)
            np.testing.assert_array_equal(
                ranks_qdid,
                np.asarray(case["qdid_ranks"], dtype=float),
                err_msg=f"QDiD ranks mismatch in '{name}'",
            )
            y0t_qdid = (
                y10
                + _qhat_eval(preds["preds01_at_x10"], _QR_TAU_GRID, ranks_qdid)
                - _qhat_eval(preds["preds00_at_x10"], _QR_TAU_GRID, ranks_qdid)
            )
            np.testing.assert_array_equal(
                y0t_qdid,
                np.asarray(case["qdid_y0t"], dtype=float),
                err_msg=f"QDiD imputations mismatch in '{name}'",
            )

    def test_micro_end_to_end_consistent_with_stored_qte_outputs(self, fixture):
        # Guards against qte's internals diverging from raw predict.rqs usage:
        # composing R's STORED imputations into ATT/QTE with the module's
        # quantile helpers must reproduce the stored qte::CiC()/QDiD() outputs
        # (R-vs-R consistency - no solver or tie-selection freedom involved,
        # so the tolerance is arithmetic-tight).
        for name, case in fixture["qr_cases"].items():
            cells = self._cells(case)
            y11_sorted = np.sort(cells["c11"]["y"])
            y0t_cic = np.asarray(case["cic_y0t"], dtype=float)
            att_cic = float(np.mean(cells["c11"]["y"]) - np.mean(y0t_cic))
            probs = np.asarray(fixture["metadata"]["probs"], dtype=float)
            qte_cic = _quantile_type1(y11_sorted, probs) - _quantile_type1(np.sort(y0t_cic), probs)
            np.testing.assert_allclose(att_cic, case["cic_ate"], atol=1e-12, rtol=0)
            np.testing.assert_allclose(
                qte_cic,
                np.asarray(case["cic_qte"], dtype=float),
                atol=1e-12,
                rtol=0,
                err_msg=f"CiC micro end-to-end inconsistency in '{name}'",
            )
            y0t_qdid = np.asarray(case["qdid_y0t"], dtype=float)
            att_qdid = float(np.mean(cells["c11"]["y"]) - np.mean(y0t_qdid))
            qte_qdid = _quantile_type7(y11_sorted, probs) - _quantile_type1(
                np.sort(y0t_qdid), probs
            )
            np.testing.assert_allclose(att_qdid, case["qdid_ate"], atol=1e-12, rtol=0)
            np.testing.assert_allclose(
                qte_qdid,
                np.asarray(case["qdid_qte"], dtype=float),
                atol=1e-12,
                rtol=0,
                err_msg=f"QDiD micro end-to-end inconsistency in '{name}'",
            )

    def test_rq_fit_exactly_optimal_per_tau(self, fixture):
        # Two-sided optimality criterion: at every tau, either the
        # coefficients match R's (unique-vertex case, ~1e-14 observed) or the
        # check losses match to relative 1e-10 (non-trivial optimal face -
        # structural for qr2's binary covariate - where both solvers return
        # exact but different vertices).
        for name, case in fixture["qr_cases"].items():
            cells = self._cells(case)
            for cell_key in ("c00", "c01", "c10"):
                y = cells[cell_key]["y"]
                x_design = _design_matrix(cells[cell_key]["X"])
                coef_r = np.asarray(case[f"coef{cell_key[1:]}"], dtype=float)  # (k+1) x 99
                coef_py = _rq_fit(y, cells[cell_key]["X"], _QR_TAU_GRID)
                assert coef_py is not None, f"LP failed in '{name}' cell {cell_key}"
                for j, tau in enumerate(_QR_TAU_GRID):
                    if np.max(np.abs(coef_py[j] - coef_r[:, j])) < 1e-8:
                        continue
                    resid_r = y - x_design @ coef_r[:, j]
                    resid_py = y - x_design @ coef_py[j]
                    loss_r = np.sum(np.where(resid_r >= 0, tau * resid_r, (tau - 1) * resid_r))
                    loss_py = np.sum(np.where(resid_py >= 0, tau * resid_py, (tau - 1) * resid_py))
                    assert abs(loss_py - loss_r) <= 1e-10 * max(abs(loss_r), 1.0), (
                        f"'{name}' cell {cell_key} tau={tau:.4f}: coefficients differ "
                        f"AND losses differ (R {loss_r!r} vs Py {loss_py!r}) - the "
                        "solver is suboptimal, not merely tie-breaking."
                    )


def test_lalonde_ties_warning(fixture, probs):
    """lalonde re78 zeros trigger the discreteness warning; points still match."""
    scenario = fixture["scenarios"].get("lalonde_psid")
    if scenario is None:
        pytest.skip("lalonde_psid missing from fixture")
    df = _scenario_df(scenario)
    est = ChangesInChanges(quantiles=probs, n_bootstrap=0)
    with pytest.warns(UserWarning, match="ties"):
        res = est.fit(df, outcome="y", treatment="treat", time="period")
    np.testing.assert_allclose(
        res.att, scenario["results"]["cic_rcs"]["ate"], atol=POINT_ATOL, rtol=0
    )


class TestQuantileMicroFixtures:
    """Raw R quantile outputs on adversarial probability grids."""

    def test_type1_bit_exact(self, fixture):
        for name, case in fixture["quantile_cases"].items():
            x = np.sort(np.asarray(case["x"], dtype=float))
            p = np.asarray(case["probs"], dtype=float)
            np.testing.assert_array_equal(
                _quantile_type1(x, p),
                np.asarray(case["type1"], dtype=float),
                err_msg=f"type-1 mismatch in micro-fixture '{name}'",
            )

    def test_type7_last_ulp(self, fixture):
        for name, case in fixture["quantile_cases"].items():
            x = np.sort(np.asarray(case["x"], dtype=float))
            p = np.asarray(case["probs"], dtype=float)
            np.testing.assert_allclose(
                _quantile_type7(x, p),
                np.asarray(case["type7"], dtype=float),
                rtol=1e-15,
                atol=1e-300,
                err_msg=f"type-7 mismatch in micro-fixture '{name}'",
            )


class TestSEStatisticalParity:
    """Scheme-identical bootstrap SEs agree statistically (never bit-exactly:
    qte's bootstrap is unseeded through its public API, so the R draws cannot
    be replicated; both sides estimate the SD of the same resampling scheme)."""

    @pytest.mark.parametrize("block_key", ["cic_panel", "cic_rcs", "qdid_panel", "qdid_rcs"])
    def test_se_parity(self, fixture, probs, ci_params, block_key):
        block = fixture["se_block"].get(block_key)
        if block is None:
            pytest.skip(f"se_block {block_key} missing from fixture")
        scenario = fixture["scenarios"]["normal_2x2_n500"]
        method, mode = block_key.rsplit("_", 1)

        n_boot = ci_params.bootstrap(499, min_n=199)
        res = _fit(_scenario_df(scenario), method, mode, probs, n_bootstrap=n_boot, seed=42)

        # ATT SE: repo convention threshold.
        att_threshold = 0.40 if n_boot < 100 else 0.15
        r_ate_se = float(block["ate_se"])
        rel = abs(res.se - r_ate_se) / r_ate_se
        assert rel < att_threshold, (
            f"{block_key}: ATT SE rel diff {rel:.3f} vs R "
            f"({res.se:.5f} vs {r_ate_se:.5f}, n_boot={n_boot})"
        )

        # Per-quantile SEs: looser bound - tail-quantile bootstrap SEs are
        # noisier than the ATT SE at any replicate count.
        qte_threshold = 0.40 if n_boot < 100 else 0.25
        r_qte_se = np.asarray(block["qte_se"], dtype=float)
        py_qte_se = res.quantile_effects["se"].to_numpy()
        rel_q = np.abs(py_qte_se - r_qte_se) / r_qte_se
        assert np.nanmax(rel_q) < qte_threshold, (
            f"{block_key}: worst per-quantile SE rel diff {np.nanmax(rel_q):.3f} "
            f"(n_boot={n_boot})"
        )

    @pytest.mark.slow
    @pytest.mark.parametrize("block_key", ["cic_cov_panel", "qdid_cov_rcs"])
    def test_se_parity_covariates(self, fixture, probs, ci_params, block_key):
        """Covariate-path bootstrap SE parity (slow: every replicate refits
        2-3 x 99 quantile-regression LPs, so ~199 replicates take ~1-2 min
        regardless of the Rust backend - hence the smaller min_n than the
        documented min_n=199 convention, with the <100-replicate 0.40
        threshold absorbing the extra noise). Vertex/knot tie-selection
        differences (see header) contribute variance far below these
        statistical thresholds.
        """
        block = fixture["se_block"].get(block_key)
        if block is None:
            pytest.skip(f"se_block {block_key} missing from fixture")
        scenario = fixture["scenarios"][block["scenario"]]
        covariates = _as_list(block["covariates"])
        method, _, mode = block_key.split("_")
        df = pd.DataFrame({k: scenario["data"][k] for k in scenario["data"]})

        n_boot = ci_params.bootstrap(199, min_n=99)
        res = _fit(df, method, mode, probs, n_bootstrap=n_boot, seed=42, covariates=covariates)

        att_threshold = 0.40 if n_boot < 100 else 0.15
        r_ate_se = float(block["ate_se"])
        rel = abs(res.se - r_ate_se) / r_ate_se
        assert rel < att_threshold, (
            f"{block_key}: ATT SE rel diff {rel:.3f} vs R "
            f"({res.se:.5f} vs {r_ate_se:.5f}, n_boot={n_boot})"
        )

        qte_threshold = 0.40 if n_boot < 100 else 0.25
        r_qte_se = np.asarray(block["qte_se"], dtype=float)
        py_qte_se = res.quantile_effects["se"].to_numpy()
        rel_q = np.abs(py_qte_se - r_qte_se) / r_qte_se
        assert np.nanmax(rel_q) < qte_threshold, (
            f"{block_key}: worst per-quantile SE rel diff {np.nanmax(rel_q):.3f} "
            f"(n_boot={n_boot})"
        )

    def test_sup_t_crit_loose_parity(self, fixture, probs, ci_params):
        """The sup-t critical value is a bootstrap quantile - compare loosely."""
        block = fixture["se_block"].get("cic_panel")
        if block is None:
            pytest.skip("se_block cic_panel missing from fixture")
        scenario = fixture["scenarios"]["normal_2x2_n500"]
        n_boot = ci_params.bootstrap(499, min_n=199)
        res = _fit(_scenario_df(scenario), "cic", "panel", probs, n_bootstrap=n_boot, seed=42)
        r_c = float(block["sup_t_crit"])
        assert np.isfinite(res.sup_t_crit)
        rel = abs(res.sup_t_crit - r_c) / r_c
        assert (
            rel < 0.40
        ), f"sup-t critical value rel diff {rel:.3f} vs R ({res.sup_t_crit:.3f} vs {r_c:.3f})"
