"""R-parity golden-fixture tests for ChangesInChanges (CiC) and QDiD vs qte 1.3.1.

Fixture: benchmarks/data/qte_golden.json, generated by
benchmarks/R/generate_qte_golden.R (qte pinned to 1.3.1 there and in
benchmarks/R/requirements.R). Point fixtures were generated with se=FALSE and
are deterministic; the se_block was generated seeded (set.seed(42), iters=999)
and is compared statistically since bootstrap draws cannot be replicated
across languages.

Tolerances:
- POINT_ATOL = 1e-10 for end-to-end ATT/QTE values (means and type-7
  interpolation differ from R by ~1 ulp; type-1 selections are bit-exact).
- Micro-fixtures: type-1 quantiles at atol=0 (pure order-statistic selection,
  bit-exact cross-language); type-7 at rtol=1e-15 (R's (1-h)*lo + h*hi vs
  numpy's lerp differ in the last ulp).
- SE parity: threshold = 0.40 if n_boot < 100 else 0.15 for the ATT SE and
  0.25 per-quantile (tail-quantile bootstrap SEs are noisier at any replicate
  count; both sides estimate the same scheme-identical bootstrap SD).
"""

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from diff_diff import ChangesInChanges, QDiD
from diff_diff.changes_in_changes import _quantile_type1, _quantile_type7

FIXTURE_PATH = Path(__file__).parent.parent / "benchmarks" / "data" / "qte_golden.json"

POINT_ATOL = 1e-10
QTE_VERSION = "1.3.1"


def _load_fixture():
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"Golden fixture {FIXTURE_PATH} missing - regenerate via "
            f"`Rscript benchmarks/R/generate_qte_golden.R`."
        )
    with open(FIXTURE_PATH) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def fixture():
    return _load_fixture()


@pytest.fixture(scope="module")
def probs(fixture):
    # Use the R-stored probs doubles: R's seq() and np.arange() can differ in
    # trailing ulps, and the quantile index arithmetic is sensitive to them.
    return np.asarray(fixture["metadata"]["probs"], dtype=float)


def _scenario_df(scenario):
    return pd.DataFrame({k: scenario["data"][k] for k in ("id", "period", "treat", "y")})


def _fit(df, method, mode, probs, n_bootstrap=0, seed=None):
    cls = ChangesInChanges if method == "cic" else QDiD
    est = cls(
        quantiles=probs,
        n_bootstrap=n_bootstrap,
        panel=(mode == "panel"),
        seed=seed,
    )
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return est.fit(
            df,
            outcome="y",
            treatment="treat",
            time="period",
            unit="id" if mode == "panel" else None,
        )


def test_metadata_versions_match(fixture):
    """The committed fixture must have been generated against the pinned qte."""
    assert fixture["metadata"]["qte_version"] == QTE_VERSION


def test_default_grid_is_r_seq_bit_exact(fixture, probs):
    """_DEFAULT_QUANTILES is pinned to R's exact seq(0.05, 0.95, 0.05) doubles.

    np.arange(0.05, 0.96, 0.05) differs from R at 5 of 19 indices by one ulp,
    and type-1 selection is ulp-sensitive on n*p integer boundaries - so the
    default is hardcoded and locked here against the R-stored fixture probs
    (local review P1).
    """
    from diff_diff.changes_in_changes import _DEFAULT_QUANTILES

    np.testing.assert_array_equal(_DEFAULT_QUANTILES, probs)


def test_default_grid_parity_end_to_end(fixture, probs):
    """quantiles=None reproduces the golden qte-default results exactly."""
    scenario = fixture["scenarios"].get("smalln_2x2_n60")
    if scenario is None:
        pytest.skip("smalln_2x2_n60 missing from fixture")
    df = _scenario_df(scenario)
    est = ChangesInChanges(n_bootstrap=0)  # default grid
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        res = est.fit(df, outcome="y", treatment="treat", time="period")
    np.testing.assert_allclose(
        res.quantile_effects["qte"].to_numpy(),
        np.asarray(scenario["results"]["cic_rcs"]["qte"], dtype=float),
        atol=POINT_ATOL,
        rtol=0,
    )


SCENARIOS = ["normal_2x2_n500", "lognormal_2x2_n300", "smalln_2x2_n60", "lalonde_psid"]
RESULT_KEYS = ["cic_panel", "cic_rcs", "qdid_panel", "qdid_rcs"]


@pytest.mark.parametrize("scenario_name", SCENARIOS)
@pytest.mark.parametrize("result_key", RESULT_KEYS)
def test_point_parity(fixture, probs, scenario_name, result_key):
    scenario = fixture["scenarios"].get(scenario_name)
    if scenario is None:
        pytest.skip(f"Scenario {scenario_name} missing from fixture")
    golden = scenario["results"][result_key]
    method, mode = result_key.rsplit("_", 1)

    res = _fit(_scenario_df(scenario), method, mode, probs)

    np.testing.assert_allclose(res.att, golden["ate"], atol=POINT_ATOL, rtol=0)
    np.testing.assert_allclose(
        res.quantile_effects["qte"].to_numpy(),
        np.asarray(golden["qte"], dtype=float),
        atol=POINT_ATOL,
        rtol=0,
    )


def test_lalonde_ties_warning(fixture, probs):
    """lalonde re78 zeros trigger the discreteness warning; points still match."""
    scenario = fixture["scenarios"].get("lalonde_psid")
    if scenario is None:
        pytest.skip("lalonde_psid missing from fixture")
    df = _scenario_df(scenario)
    est = ChangesInChanges(quantiles=probs, n_bootstrap=0)
    with pytest.warns(UserWarning, match="ties"):
        res = est.fit(df, outcome="y", treatment="treat", time="period")
    np.testing.assert_allclose(
        res.att, scenario["results"]["cic_rcs"]["ate"], atol=POINT_ATOL, rtol=0
    )


class TestQuantileMicroFixtures:
    """Raw R quantile outputs on adversarial probability grids."""

    def test_type1_bit_exact(self, fixture):
        for name, case in fixture["quantile_cases"].items():
            x = np.sort(np.asarray(case["x"], dtype=float))
            p = np.asarray(case["probs"], dtype=float)
            np.testing.assert_array_equal(
                _quantile_type1(x, p),
                np.asarray(case["type1"], dtype=float),
                err_msg=f"type-1 mismatch in micro-fixture '{name}'",
            )

    def test_type7_last_ulp(self, fixture):
        for name, case in fixture["quantile_cases"].items():
            x = np.sort(np.asarray(case["x"], dtype=float))
            p = np.asarray(case["probs"], dtype=float)
            np.testing.assert_allclose(
                _quantile_type7(x, p),
                np.asarray(case["type7"], dtype=float),
                rtol=1e-15,
                atol=1e-300,
                err_msg=f"type-7 mismatch in micro-fixture '{name}'",
            )


class TestSEStatisticalParity:
    """Scheme-identical bootstrap SEs agree statistically (never bit-exactly:
    qte's bootstrap is unseeded through its public API, so the R draws cannot
    be replicated; both sides estimate the SD of the same resampling scheme)."""

    @pytest.mark.parametrize("block_key", ["cic_panel", "cic_rcs", "qdid_panel", "qdid_rcs"])
    def test_se_parity(self, fixture, probs, ci_params, block_key):
        block = fixture["se_block"].get(block_key)
        if block is None:
            pytest.skip(f"se_block {block_key} missing from fixture")
        scenario = fixture["scenarios"]["normal_2x2_n500"]
        method, mode = block_key.rsplit("_", 1)

        n_boot = ci_params.bootstrap(499, min_n=199)
        res = _fit(_scenario_df(scenario), method, mode, probs, n_bootstrap=n_boot, seed=42)

        # ATT SE: repo convention threshold.
        att_threshold = 0.40 if n_boot < 100 else 0.15
        r_ate_se = float(block["ate_se"])
        rel = abs(res.se - r_ate_se) / r_ate_se
        assert rel < att_threshold, (
            f"{block_key}: ATT SE rel diff {rel:.3f} vs R "
            f"({res.se:.5f} vs {r_ate_se:.5f}, n_boot={n_boot})"
        )

        # Per-quantile SEs: looser bound - tail-quantile bootstrap SEs are
        # noisier than the ATT SE at any replicate count.
        qte_threshold = 0.40 if n_boot < 100 else 0.25
        r_qte_se = np.asarray(block["qte_se"], dtype=float)
        py_qte_se = res.quantile_effects["se"].to_numpy()
        rel_q = np.abs(py_qte_se - r_qte_se) / r_qte_se
        assert np.nanmax(rel_q) < qte_threshold, (
            f"{block_key}: worst per-quantile SE rel diff {np.nanmax(rel_q):.3f} "
            f"(n_boot={n_boot})"
        )

    def test_sup_t_crit_loose_parity(self, fixture, probs, ci_params):
        """The sup-t critical value is a bootstrap quantile - compare loosely."""
        block = fixture["se_block"].get("cic_panel")
        if block is None:
            pytest.skip("se_block cic_panel missing from fixture")
        scenario = fixture["scenarios"]["normal_2x2_n500"]
        n_boot = ci_params.bootstrap(499, min_n=199)
        res = _fit(_scenario_df(scenario), "cic", "panel", probs, n_bootstrap=n_boot, seed=42)
        r_c = float(block["sup_t_crit"])
        assert np.isfinite(res.sup_t_crit)
        rel = abs(res.sup_t_crit - r_c) / r_c
        assert (
            rel < 0.40
        ), f"sup-t critical value rel diff {rel:.3f} vs R ({res.sup_t_crit:.3f} vs {r_c:.3f})"
