#!/usr/bin/env python3
"""Generate LinkedIn carousel PDF for the v3.5.3 -> v3.7.0 speed & memory arc.

Architecture forked from ``generate_lpdid_carousel.py`` (magazine sidebar with
amber progress tick, lavender -> white gradient, split-color logo, pyproject-
derived footer version). Light HOUSE style throughout (no dark slide). Data
treatment is a MIX: two matplotlib charts (CS wheel-to-wheel; SDID vs R) and
big typographic before -> after stat rows everywhere else. This deck adds a
build-time overflow guard (``_fit_assert``) on the text helpers (centered
text, callout/card/grid copy; ``_stat_row`` carries its own inline guard):
a string wider than its box raises at generation time instead of silently
clipping. Short fixed labels (cover bars, pip badges) are width-measured
for centering and excluded from the guard.

Narrative spine (upgrade story; user-directed 2026-07-11):

1.  Cover        -- "Same estimates. A fraction of the time." + shrinking bars
2.  Problem      -- panel scale hits two walls (time AND memory); the ~0.9 TB
                    dummy-matrix arithmetic nobody should ever compute
3.  TWFE speed   -- one demeaning-engine rebuild, three stat rows
4.  TWFE memory  -- 15.3 -> 7.8 GB solver high-water; the matrix never built
5.  CS rewrite   -- O(n_units) influence functions: 6.3x + RSS + tiling
6.  The upgrade  -- CHART: wheel-to-wheel CS, released 3.5.3 vs 3.7.0
7.  SDID         -- CHART: Rust backend vs R synthdid, re-benchmarked
8.  Guarantees   -- the gates behind the numbers, by provenance class:
                    published benchmarks gate vs R (fail-closed); internal
                    rewrites verify against reference outputs
9.  What you get -- 2x2 card grid; nothing to change
10. CTA          -- pip install --upgrade + GitHub

Claim discipline (every printed number -> its source; verify on regeneration):
- TWFE firm panel 2.4M rows 93 s -> 20 s (4.6x): docs/performance-plan.md
  fe_absorption table row 8 (92.957 -> 46.127 numpy -> 20.341 Rust). The
  pyfixest cell for THIS scenario is a flagged noisy proxy (cv 20.3%, no
  sunab()) and is deliberately NOT printed.
- Geo absorb 5M rows 2.6 s -> 0.45 s (5.8x), ahead of pyfixest 0.62 s:
  same table row 10 (2.630 / 0.453 vs 0.623, cv 7.8% -- clean cell).
- Scanner TWFE 3.25M rows 1.5 s -> 0.61 s, "parity with pyfixest" (no
  decimals printed for pyfixest: its cell is cv 12.3%, noisy): row 9.
- ~0.9 TB dummy matrix: labeled arithmetic illustration
  (3,255,000 rows x 35,000 store dummies x 8 bytes = 911 GB dense).
- Demeaning 64-87% of fit time / 2,948 transform calls: performance-plan.md
  "FE-absorption baseline" section.
- Solver marshalling 15.3 -> 7.8 GB: performance-plan.md (15.32 -> 7.81 GB,
  alloc-profile build, 2.4M-row clustered solve); CHANGELOG 3.6.2.
- Demean engine parity "atol 1e-12": performance-plan.md Rust demean_map
  paragraph (assert_allclose(atol=1e-12) vs the numpy engine).
- CS 2M rows 1.32 -> 0.21 s (6.3x), RSS 960 -> 582 MB; bootstrap tiling
  11.6 -> 2.4 GB: performance-plan.md CS table + CHANGELOG 3.6.0. Points
  bit-identical, aggregated SEs <= 5e-16 relative: same section.
- Wheel-to-wheel CS 0.242 -> 0.048 s (360k rows), 1.335 -> 0.274 s (2M rows),
  identical estimates: benchmarks/refresh_2026_07/results/version_story.md
  (released PyPI wheels, medians, fresh subprocesses, warm-up excluded).
- SDID Rust 25.2 s vs R 467 s at the 5k scale (18.5x); 18-55x across scales;
  matched 200-replication placebo variance; id-aligned unit/time weights
  hard-gated at < 1e-8 vs R (docs/benchmarks.rst contract), observed max
  diff 3.5e-12 (unit weights ~5e-13; the small-scale time weights set the
  3.45e-12 max): refresh_results.json ``max_abs_diff`` entries. SDID is
  framed as "re-benchmarked" (its Frank-Wolfe kernels predate this arc).
- Slide 8 gate cards state hard gates in titles, observed results in the
  descriptions: headline ATT gate is abs < 1e-4 or rel < 1%
  (run_refresh.py ``att_atol=1e-4``; benchmarks.rst protocol) -- worded as
  "fail-closed" with no number since 1e-8 only gates pure-vs-rust agreement
  and SDID's deterministic ATT; effect surfaces hard-gated at 1e-6 with
  observed max ~5e-11 (refresh_results.json ``max_att_diff``); SDID weights
  hard-gated at 1e-8 with observed max 3.5e-12. "Reproducible end to end"
  scopes the one-command claim to the gated benchmark TABLES
  (gen_benchmark_tables.py regenerates the docs tables verbatim; hard gate
  failures block publication, PR #672/#673) -- performance-plan-sourced
  numbers are traced via this docstring, not regenerated by a command.
- Hardware framing: Apple M4 Max, medians, committed artifacts (slide 9
  footnote). Footer version derived from pyproject.toml -- never hard-coded.

Latin-1 discipline: fpdf built-in fonts only; all rendered strings use ASCII
substitutes (``->``, ``x``, ``--``). Charts (matplotlib) may use unicode.

Run with::

    python carousel/generate_perf_carousel.py

Produces ``carousel/diff-diff-perf-carousel.pdf``. Requires ``fpdf2``,
``Pillow``, ``matplotlib`` (carousel-only dependencies).
"""

import os
import re
import tempfile
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from fpdf import FPDF  # noqa: E402
from PIL import Image as PILImage  # noqa: E402

# Page dimensions (4:5 portrait -- same as every house deck)
WIDTH = 270  # mm
HEIGHT = 337.5  # mm

# Footer version derived from pyproject.toml (regex, not tomllib: >=3.9).
_PYPROJECT = Path(__file__).parent.parent / "pyproject.toml"
_m = re.search(r'^version\s*=\s*"([^"]+)"', _PYPROJECT.read_text(encoding="utf-8"), re.MULTILINE)
if _m is None:
    raise RuntimeError(f"could not parse project version from {_PYPROJECT}")
VERSION_LABEL = "v" + _m.group(1)

TOTAL_SLIDES = 10

# House "Horizon" palette (identical to the LPDiD deck)
VIOLET = (109, 40, 217)
VIOLET_DARK = (91, 33, 182)
VIOLET_LIGHT = (196, 181, 253)
CYAN = (8, 145, 178)
AMBER = (245, 158, 11)
LAVENDER = (245, 243, 255)
SHADOW = (203, 213, 225)
NAVY = (15, 23, 42)
GRAY = (100, 116, 139)
LIGHT_GRAY = (148, 163, 184)
WHITE = (255, 255, 255)

VIOLET_HEX = "#6d28d9"
VIOLET_LIGHT_HEX = "#c4b5fd"
AMBER_HEX = "#f59e0b"
NAVY_HEX = "#0f172a"
GRAY_HEX = "#64748b"
LIGHT_GRAY_HEX = "#94a3b8"


class PerfCarouselPDF(FPDF):
    def __init__(self):
        super().__init__(orientation="P", unit="mm", format=(WIDTH, HEIGHT))
        self.set_auto_page_break(False)
        self._temp_files = []

    def cleanup(self):
        for f in self._temp_files:
            try:
                os.unlink(f)
            except OSError:
                pass

    # ------------------------------------------------------------------
    # Build-time overflow guard: silent clipping is not allowed in this
    # deck. Any single-line string wider than its box fails generation.
    # ------------------------------------------------------------------

    def _fit_assert(self, text, family, style, size: float, max_w, what=""):
        self.set_font(family, style, size)
        w = self.get_string_width(text)
        if w > max_w:
            raise ValueError(
                f"overflow ({what or 'string'}): {w:.1f}mm > {max_w:.1f}mm "
                f"at {family}-{style or 'R'} {size}pt: {text!r}"
            )
        return w

    # ------------------------------------------------------------------
    # Sidebar / background / footer (house pattern)
    # ------------------------------------------------------------------

    def _draw_vertical_sidebar(self, slide_number, total=TOTAL_SLIDES):
        bar_x = 14
        bar_y_top = 45
        bar_y_bottom = 275
        self.set_draw_color(*VIOLET)
        self.set_line_width(0.6)
        self.line(bar_x, bar_y_top, bar_x, bar_y_bottom)
        ratio = (slide_number - 1) / (total - 1) if total > 1 else 0.0
        tick_y = bar_y_top + ratio * (bar_y_bottom - bar_y_top)
        self.set_draw_color(*AMBER)
        self.set_line_width(1.2)
        self.line(bar_x - 4, tick_y, bar_x + 7, tick_y)

    def light_gradient_background(self):
        steps = 50
        r0, g0, b0 = LAVENDER
        for i in range(steps):
            ratio = i / steps
            self.set_fill_color(
                int(r0 + (255 - r0) * ratio),
                int(g0 + (255 - g0) * ratio),
                int(b0 + (255 - b0) * ratio),
            )
            self.rect(0, i * HEIGHT / steps, WIDTH, HEIGHT / steps + 1, "F")

    def add_footer(self):
        self.set_font("Helvetica", "B", 12)
        dd_text = "diff-diff "
        dd_w = self.get_string_width(dd_text)
        v_w = self.get_string_width(VERSION_LABEL)
        start_x = (WIDTH - dd_w - v_w) / 2
        self.set_xy(start_x, HEIGHT - 18)
        self.set_text_color(*GRAY)
        self.cell(dd_w, 10, dd_text)
        self.set_text_color(*VIOLET)
        self.cell(v_w, 10, VERSION_LABEL)

    # ------------------------------------------------------------------
    # Text helpers
    # ------------------------------------------------------------------

    def centered_text(
        self, y, text, size: float = 28, bold=True, color=NAVY, italic=False, max_w=None
    ):
        style = ("B" if bold else "") + ("I" if italic else "")
        self._fit_assert(text, "Helvetica", style, size, max_w or (WIDTH - 36), "centered_text")
        self.set_xy(0, y)
        self.set_font("Helvetica", style, size)
        self.set_text_color(*color)
        self.cell(WIDTH, size * 0.5, text, align="C")

    def _kicker(self, y, text, color=AMBER):
        spaced = " ".join(text.upper())
        self.set_font("Helvetica", "B", 13)
        tw = self.get_string_width(spaced)
        mid_y = y + 3
        rule, gap = 20, 8
        self.set_draw_color(*color)
        self.set_line_width(0.7)
        self.line(WIDTH / 2 - tw / 2 - gap - rule, mid_y, WIDTH / 2 - tw / 2 - gap, mid_y)
        self.line(WIDTH / 2 + tw / 2 + gap, mid_y, WIDTH / 2 + tw / 2 + gap + rule, mid_y)
        self.set_xy(0, y)
        self.set_text_color(*color)
        self.cell(WIDTH, 6, spaced, align="C")

    def draw_split_logo(self, y, size=18):
        self.set_xy(0, y)
        self.set_font("Helvetica", "B", size)
        self.set_text_color(*NAVY)
        self.cell(WIDTH / 2 - 5, 10, "diff", align="R")
        self.set_text_color(*VIOLET)
        self.cell(10, 10, "-", align="C")
        self.set_text_color(*NAVY)
        self.cell(WIDTH / 2 - 5, 10, "diff", align="L")

    # ------------------------------------------------------------------
    # Shadowed cards (house pattern)
    # ------------------------------------------------------------------

    def _shadow_rect(self, x, y, w, h):
        self.set_fill_color(*SHADOW)
        self.rect(x + 1.4, y + 1.4, w, h, "F")

    def _card_stack(
        self, items, start_y, box_h=42, accent=VIOLET, margin=30, title_size=16, desc_size=13
    ):
        box_w = WIDTH - margin * 2
        gap = 6
        bar_w = 5
        inner_w = box_w - bar_w - 24
        for i, (title, desc) in enumerate(items):
            self._fit_assert(title, "Helvetica", "B", title_size, inner_w, "card title")
            self._fit_assert(desc, "Helvetica", "", desc_size, inner_w, "card desc")
            by = start_y + i * (box_h + gap)
            self._shadow_rect(margin, by, box_w, box_h)
            self.set_fill_color(*WHITE)
            self.set_draw_color(220, 220, 220)
            self.set_line_width(0.5)
            self.rect(margin, by, box_w, box_h, "DF")
            self.set_fill_color(*accent)
            self.rect(margin, by, bar_w, box_h, "F")
            self.set_xy(margin + bar_w + 12, by + 8)
            self.set_font("Helvetica", "B", title_size)
            self.set_text_color(*NAVY)
            self.cell(inner_w, 10, title)
            self.set_xy(margin + bar_w + 12, by + 26)
            self.set_font("Helvetica", "", desc_size)
            self.set_text_color(*GRAY)
            self.cell(inner_w, 10, desc)
        return start_y + len(items) * (box_h + gap)

    # ------------------------------------------------------------------
    # NEW: big-type before -> after stat row (native fpdf, no matplotlib)
    # ------------------------------------------------------------------

    def _stat_row(self, y, before, after, label, num_size: float = 36, label_size: float = 14):
        """Centered ``before -> after`` in display type, one-line label below.

        before: NAVY bold; arrow: AMBER bold; after: VIOLET bold.
        Returns the y coordinate below the label.
        """
        arrow = "  ->  "
        self.set_font("Helvetica", "B", num_size)
        bw = self.get_string_width(before)
        aw = self.get_string_width(arrow)
        fw = self.get_string_width(after)
        total = bw + aw + fw
        if total > WIDTH - 44:
            raise ValueError(f"stat row overflow: {before} -> {after} ({total:.0f}mm)")
        x = (WIDTH - total) / 2
        row_h = num_size * 0.5
        self.set_xy(x, y)
        self.set_text_color(*NAVY)
        self.cell(bw, row_h, before)
        self.set_text_color(*AMBER)
        self.cell(aw, row_h, arrow)
        self.set_text_color(*VIOLET)
        self.cell(fw, row_h, after)
        label_y = y + row_h + 2
        self.centered_text(label_y, label, size=label_size, bold=False, color=GRAY)
        return label_y + label_size * 0.5 + 2

    # ------------------------------------------------------------------
    # NEW: bordered tinted callout box (v26 pattern)
    # ------------------------------------------------------------------

    def _callout_box(self, y, lines, box_h, accent=VIOLET, margin=34):
        """lines = [(text, size, bold, color)] stacked and centered in a box."""
        box_w = WIDTH - margin * 2
        self._shadow_rect(margin, y, box_w, box_h)
        self.set_fill_color(*LAVENDER)
        self.set_draw_color(*accent)
        self.set_line_width(0.8)
        self.rect(margin, y, box_w, box_h, "DF")
        n = len(lines)
        pad = 8
        inner_h = box_h - 2 * pad
        slot = inner_h / n
        for i, (text, size, bold, color) in enumerate(lines):
            style = "B" if bold else ""
            self._fit_assert(text, "Helvetica", style, size, box_w - 16, "callout line")
            self.set_xy(margin, y + pad + i * slot + (slot - size * 0.5) / 2)
            self.set_font("Helvetica", style, size)
            self.set_text_color(*color)
            self.cell(box_w, size * 0.5, text, align="C")
        return y + box_h

    # ------------------------------------------------------------------
    # Matplotlib figure saver (house pattern)
    # ------------------------------------------------------------------

    def _save_fig(self, fig, dpi=200, transparent=False, facecolor="white"):
        fd, path = tempfile.mkstemp(suffix=".png")
        os.close(fd)
        fig.savefig(
            path,
            dpi=dpi,
            bbox_inches="tight",
            pad_inches=0.1,
            transparent=transparent,
            facecolor=None if transparent else facecolor,
        )
        plt.close(fig)
        with PILImage.open(path) as img:
            pw, ph = img.size
        self._temp_files.append(path)
        return path, pw, ph

    # ------------------------------------------------------------------
    # Chart 1: CS wheel-to-wheel (released 3.5.3 vs 3.7.0)
    # ------------------------------------------------------------------

    def _render_upgrade_bars(self):
        fig, ax = plt.subplots(figsize=(10, 4.4))
        # (group label, old seconds, new seconds, speedup label)
        rows = [
            ("CallawaySantAnna\n2,000,000 rows", 1.335, 0.274, "4.9x"),
            ("CallawaySantAnna\n360,000 rows", 0.242, 0.048, "5.0x"),
        ]
        bar_h = 0.32
        for gi, (label, old, new, speed) in enumerate(rows):
            y_old = gi + bar_h / 2 + 0.03
            y_new = gi - bar_h / 2 - 0.03
            ax.barh(y_old, old, height=bar_h, color=VIOLET_LIGHT_HEX, edgecolor="none")
            ax.barh(y_new, new, height=bar_h, color=VIOLET_HEX, edgecolor="none")
            ax.text(old + 0.02, y_old, f"{old:.3f} s", va="center", fontsize=13, color=GRAY_HEX)
            ax.text(
                new + 0.02,
                y_new,
                f"{new:.3f} s",
                va="center",
                fontsize=13,
                color=NAVY_HEX,
                fontweight="bold",
            )
            ax.text(
                1.60,
                gi,
                speed,
                va="center",
                fontsize=18,
                color=AMBER_HEX,
                fontweight="bold",
            )
        ax.set_yticks([0, 1])
        ax.set_yticklabels([r[0] for r in rows], fontsize=14, color=NAVY_HEX)
        ax.tick_params(axis="y", length=0)
        ax.set_facecolor("none")
        ax.set_xlim(0, 1.78)
        ax.set_xlabel("fit time, seconds (median)", fontsize=13, color=GRAY_HEX)
        ax.tick_params(axis="x", labelsize=12, colors=GRAY_HEX)
        for spine in ("top", "right", "left"):
            ax.spines[spine].set_visible(False)
        ax.spines["bottom"].set_color(LIGHT_GRAY_HEX)
        # Legend: released wheels
        import matplotlib.patches as mpatches

        old_patch = mpatches.Patch(color=VIOLET_LIGHT_HEX, label="v3.5.3 wheel")
        new_patch = mpatches.Patch(color=VIOLET_HEX, label="v3.7.0 wheel")
        ax.legend(handles=[old_patch, new_patch], loc="upper right", fontsize=12, frameon=False)
        fig.tight_layout()
        return self._save_fig(fig, transparent=True)

    # ------------------------------------------------------------------
    # Chart 2: SDID Rust backend vs R synthdid (5k scale)
    # ------------------------------------------------------------------

    def _render_sdid_bars(self):
        fig, ax = plt.subplots(figsize=(10, 3.2))
        bars = [
            ("diff-diff (Rust backend)", 25.2, VIOLET_HEX),
            ("R synthdid", 467.0, LIGHT_GRAY_HEX),
        ]
        for i, (label, val, color) in enumerate(bars):
            ax.barh(i, val, height=0.52, color=color, edgecolor="none")
        ax.text(25.2 + 8, 0, "25.2 s", va="center", fontsize=14, color=NAVY_HEX, fontweight="bold")
        ax.text(
            467.0 - 10,
            1,
            "467 s  (~7.8 min)",
            va="center",
            ha="right",
            fontsize=14,
            color="white",
            fontweight="bold",
        )
        ax.text(
            250, 0.02, "18.5x faster", fontsize=17, color=AMBER_HEX, fontweight="bold", va="center"
        )
        ax.set_yticks([0, 1])
        ax.set_yticklabels([b[0] for b in bars], fontsize=14, color=NAVY_HEX)
        ax.tick_params(axis="y", length=0)
        ax.set_facecolor("none")
        ax.set_xlim(0, 500)
        ax.set_xlabel(
            "Synthetic DiD fit + placebo variance, 5k-unit scale (seconds)",
            fontsize=13,
            color=GRAY_HEX,
        )
        ax.tick_params(axis="x", labelsize=12, colors=GRAY_HEX)
        for spine in ("top", "right", "left"):
            ax.spines[spine].set_visible(False)
        ax.spines["bottom"].set_color(LIGHT_GRAY_HEX)
        fig.tight_layout()
        return self._save_fig(fig, transparent=True)

    # ==================================================================
    # Slides
    # ==================================================================

    def slide_01_cover(self):
        self.add_page()
        self.light_gradient_background()
        self._draw_vertical_sidebar(1)
        self.draw_split_logo(34, size=40)

        self.centered_text(92, "Same estimates.", size=44, color=NAVY)
        self.centered_text(122, "A fraction of the time.", size=44, color=VIOLET)

        # Shrinking-bars motif (native fpdf)
        bar_x = 62
        bar_max_w = 146
        bar_h = 13
        y0 = 180
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*GRAY)
        self.set_xy(bar_x - 34, y0 - 1)
        self.cell(30, bar_h, "v3.5.3", align="R")
        self.set_fill_color(*VIOLET_LIGHT)
        self.rect(bar_x, y0, bar_max_w, bar_h, "F")

        y1 = y0 + bar_h + 9
        self.set_xy(bar_x - 34, y1 - 1)
        self.set_text_color(*GRAY)
        self.cell(30, bar_h, "v3.7.0", align="R")
        self.set_fill_color(*VIOLET)
        self.rect(bar_x, y1, bar_max_w / 4.9, bar_h, "F")
        self.set_font("Helvetica", "B", 19)
        self.set_text_color(*AMBER)
        self.set_xy(bar_x + bar_max_w / 4.9 + 6, y1 - 1.5)
        self.cell(40, bar_h + 2, "~5x")

        self.centered_text(
            248,
            "The v3.5.3 -> v3.7.0 speed & memory arc.",
            size=16,
            bold=False,
            color=GRAY,
        )
        self.centered_text(
            266,
            "Two-way fixed effects  -  Callaway-Sant'Anna  -  Synthetic DiD",
            size=13,
            bold=False,
            color=LIGHT_GRAY,
        )
        self.add_footer()

    def slide_02_problem(self):
        self.add_page()
        self.light_gradient_background()
        self._draw_vertical_sidebar(2)
        self._kicker(34, "The Problem")
        self.centered_text(52, "Panel scale hits two walls.", size=37, color=NAVY)
        self.centered_text(80, "Time. And memory.", size=37, color=VIOLET)

        self._callout_box(
            118,
            [
                ("35,000 store dummies  x  3,255,000 rows", 20, True, NAVY),
                ("=  a ~0.9 TB dense design matrix", 24, True, VIOLET),
            ],
            box_h=52,
        )
        self.centered_text(
            196,
            "Fixed-effects absorption never builds that matrix --",
            size=15,
            bold=False,
            color=NAVY,
        )
        self.centered_text(
            212,
            "but demeaning becomes the hot path: 64-87% of a large-panel fit,",
            size=15,
            bold=False,
            color=NAVY,
        )
        self.centered_text(
            228,
            "2,948 pandas groupby-transform calls in a single fit.",
            size=15,
            bold=False,
            color=NAVY,
        )
        self.centered_text(258, "So we rebuilt the engine.", size=20, color=VIOLET)
        self.add_footer()

    def slide_03_twfe_speed(self):
        self.add_page()
        self.light_gradient_background()
        self._draw_vertical_sidebar(3)
        self._kicker(34, "Two-Way Fixed Effects")
        self.centered_text(52, "One engine. Three rebuilds.", size=37, color=NAVY)
        self.centered_text(
            76,
            "pandas transform  ->  factorize-once bincount MAP  ->  Rust kernel",
            size=13.5,
            bold=False,
            color=GRAY,
        )

        y = self._stat_row(104, "93 s", "20 s", "Firm-panel event study  -  2.4M rows  -  4.6x")
        y = self._stat_row(y + 14, "2.6 s", "0.45 s", "Geo experiment  -  5M rows  -  5.8x")
        self.centered_text(
            y + 1,
            "now ahead of pyfixest (0.62 s) on this scenario",
            size=12.5,
            bold=False,
            italic=True,
            color=LIGHT_GRAY,
        )
        y = self._stat_row(
            y + 22, "1.5 s", "0.61 s", "Scanner store-week TWFE  -  3.25M rows  -  2.5x"
        )
        self.centered_text(
            y + 1,
            "at parity with pyfixest",
            size=12.5,
            bold=False,
            italic=True,
            color=LIGHT_GRAY,
        )
        self.centered_text(
            272,
            "One demeaning engine under TWFE, absorbed DiD, and Sun-Abraham.",
            size=13,
            bold=False,
            color=GRAY,
        )
        self.add_footer()

    def slide_04_twfe_memory(self):
        self.add_page()
        self.light_gradient_background()
        self._draw_vertical_sidebar(4)
        self._kicker(34, "Memory")
        self.centered_text(52, "Half the high-water mark.", size=37, color=NAVY)

        y = self._stat_row(
            104,
            "15.3 GB",
            "7.8 GB",
            "Peak allocation  -  2.4M-row clustered solve",
            num_size=44,
            label_size=15,
        )
        self.centered_text(
            y + 2,
            "the waste was marshalling, not math -- one owned copy instead of two",
            size=12.5,
            bold=False,
            italic=True,
            color=LIGHT_GRAY,
        )
        y = self._stat_row(
            y + 30,
            "~0.9 TB",
            "0 bytes",
            "The dummy design matrix we never materialize",
            num_size=44,
            label_size=15,
        )

        self.centered_text(
            262,
            "Same estimates: the rebuilt engine matches the reference",
            size=14,
            bold=False,
            color=GRAY,
        )
        self.centered_text(
            276,
            "demeaner to atol 1e-12 on every path.",
            size=14,
            bold=False,
            color=GRAY,
        )
        self.add_footer()

    def slide_05_cs(self):
        self.add_page()
        self.light_gradient_background()
        self._draw_vertical_sidebar(5)
        self._kicker(34, "Callaway-Sant'Anna")
        self.centered_text(52, "The O(n_units) rewrite.", size=37, color=NAVY)
        self.centered_text(
            76,
            "per-cohort DataFrame scans  ->  closed-form influence functions",
            size=13.5,
            bold=False,
            color=GRAY,
        )

        y = self._stat_row(104, "1.32 s", "0.21 s", "Analytical fit  -  2M rows  -  6.3x")
        y = self._stat_row(y + 14, "960 MB", "582 MB", "Peak RSS on that same fit")
        y = self._stat_row(
            y + 14, "11.6 GB", "2.4 GB", "Multiplier bootstrap at scale  -  now tiled"
        )

        self.centered_text(
            258,
            "Point estimates bit-identical.",
            size=15,
            bold=False,
            color=NAVY,
        )
        self.centered_text(
            274,
            "Aggregated SEs within 5e-16 relative of the original path.",
            size=13,
            bold=False,
            color=GRAY,
        )
        self.add_footer()

    def slide_06_upgrade(self):
        self.add_page()
        self.light_gradient_background()
        self._draw_vertical_sidebar(6)
        self._kicker(34, "The Upgrade")
        self.centered_text(52, "Wheel to wheel.", size=37, color=NAVY)
        self.centered_text(
            76,
            "Released PyPI wheels, same data, same machine, fresh processes.",
            size=13.5,
            bold=False,
            color=GRAY,
        )

        path, pw, ph = self._render_upgrade_bars()
        plot_w = WIDTH * 0.84
        plot_h = plot_w * (ph / pw)
        self.image(path, (WIDTH - plot_w) / 2, 98, plot_w)

        cap_y = 98 + plot_h + 14
        self.centered_text(
            cap_y, "Identical estimates. The upgrade is the migration.", size=16, color=NAVY
        )
        self.set_font("Courier", "B", 14)
        pip_text = "pip install --upgrade diff-diff"
        pw_pip = self.get_string_width(pip_text)
        self.set_xy((WIDTH - pw_pip) / 2, cap_y + 16)
        self.set_text_color(*VIOLET)
        self.cell(pw_pip, 8, pip_text)
        self.add_footer()

    def slide_07_sdid(self):
        self.add_page()
        self.light_gradient_background()
        self._draw_vertical_sidebar(7)
        self._kicker(34, "Synthetic DiD")
        self.centered_text(52, "The Rust backend,", size=37, color=NAVY)
        self.centered_text(80, "re-benchmarked.", size=37, color=VIOLET)

        path, pw, ph = self._render_sdid_bars()
        plot_w = WIDTH * 0.84
        plot_h = plot_w * (ph / pw)
        self.image(path, (WIDTH - plot_w) / 2, 110, plot_w)

        cap_y = 110 + plot_h + 16
        self.centered_text(
            cap_y,
            "18-55x faster than R synthdid across benchmark scales,",
            size=15,
            bold=False,
            color=NAVY,
        )
        self.centered_text(
            cap_y + 16,
            "at matched 200-replication placebo variance.",
            size=15,
            bold=False,
            color=NAVY,
        )
        self.centered_text(
            cap_y + 36,
            "Same Frank-Wolfe optimizer: id-aligned weights reproduce R (max diff 3.5e-12).",
            size=12.5,
            bold=False,
            italic=True,
            color=LIGHT_GRAY,
        )
        self.add_footer()

    def slide_08_guarantees(self):
        self.add_page()
        self.light_gradient_background()
        self._draw_vertical_sidebar(8)
        self._kicker(34, "Gated")
        self.centered_text(52, "Speed that can't drift.", size=40, color=NAVY)
        self.centered_text(
            78,
            "Published benchmarks pass fail-closed parity gates vs R.",
            size=13.5,
            bold=False,
            color=GRAY,
        )
        self.centered_text(
            90,
            "Internal rewrites verify against reference outputs -- same estimates.",
            size=13.5,
            bold=False,
            color=GRAY,
        )

        self._card_stack(
            [
                (
                    "ATT parity: fail-closed",
                    "Every published benchmark gated against R -- a hard failure blocks publication",
                ),
                (
                    "Effect surfaces: < 1e-6",
                    "Per-(g,t), event-study, and group aggregations -- observed max ~5e-11",
                ),
                (
                    "SDID weights: < 1e-8",
                    "Unit and time weights id-aligned to R's ordering -- observed max 3.5e-12",
                ),
                (
                    "Reproducible end to end",
                    "Committed artifacts trace every number -- one command rebuilds the benchmark tables",
                ),
            ],
            start_y=104,
            box_h=40,
        )
        self.add_footer()

    def slide_09_practice(self):
        self.add_page()
        self.light_gradient_background()
        self._draw_vertical_sidebar(9)
        self._kicker(34, "In Practice")
        self.centered_text(52, "Nothing to change.", size=40, color=CYAN)

        margin = 26
        grid_gap = 9
        card_w = (WIDTH - 2 * margin - grid_gap) / 2
        card_h = 56
        start_y = 96
        cards = [
            (
                "Rust bundled in wheels",
                "pip wheels ship the backend --\nno toolchain, used automatically",
            ),
            (
                "Same sklearn-style API",
                "fit() unchanged -- zero code\nchanges to pick up the speed",
            ),
            (
                "Memory tiling at scale",
                "bootstrap + solver paths sized\nfor multi-million-row panels",
            ),
            (
                "R parity, maintained",
                "benchmarks gate against R --\nrewrites verified vs reference",
            ),
        ]
        for i, (title, desc) in enumerate(cards):
            row, col = divmod(i, 2)
            cx = margin + col * (card_w + grid_gap)
            cy = start_y + row * (card_h + grid_gap)
            self._shadow_rect(cx, cy, card_w, card_h)
            self.set_fill_color(*WHITE)
            self.set_draw_color(*VIOLET)
            self.set_line_width(0.7)
            self.rect(cx, cy, card_w, card_h, "DF")
            self._fit_assert(title, "Helvetica", "B", 16, card_w - 16, "grid title")
            self.set_xy(cx + 10, cy + 8)
            self.set_font("Helvetica", "B", 16)
            self.set_text_color(*CYAN)
            self.cell(card_w - 20, 8, title)
            for li, line in enumerate(desc.split("\n")):
                self._fit_assert(line, "Helvetica", "", 12.5, card_w - 16, "grid desc")
                self.set_xy(cx + 10, cy + 24 + li * 11)
                self.set_font("Helvetica", "", 12.5)
                self.set_text_color(*GRAY)
                self.cell(card_w - 20, 8, line)

        end_y = start_y + 2 * (card_h + grid_gap) + 10
        self.centered_text(
            end_y + 8,
            "All numbers: Apple M4 Max, medians of repeated runs,",
            size=12.5,
            bold=False,
            italic=True,
            color=LIGHT_GRAY,
        )
        self.centered_text(
            end_y + 21,
            "committed benchmark artifacts in the repo.",
            size=12.5,
            bold=False,
            italic=True,
            color=LIGHT_GRAY,
        )
        self.add_footer()

    def slide_10_cta(self):
        self.add_page()
        self.light_gradient_background()
        self._draw_vertical_sidebar(10)

        self.centered_text(70, "Faster by default.", size=24, bold=False, italic=True, color=GRAY)
        self.centered_text(104, VERSION_LABEL + ".", size=54, color=VIOLET)

        badge_w, badge_h = 232, 44
        badge_x = (WIDTH - badge_w) / 2
        badge_y = 156
        self._shadow_rect(badge_x, badge_y, badge_w, badge_h)
        self.set_fill_color(*VIOLET)
        self.rect(badge_x, badge_y, badge_w, badge_h, "F")
        self.set_font("Courier", "B", 17)
        self.set_text_color(*WHITE)
        cmd = "$ pip install --upgrade diff-diff"
        cw = self.get_string_width(cmd)
        self.set_xy((WIDTH - cw) / 2, badge_y + badge_h / 2 - 4)
        self.cell(cw, 8, cmd)

        self.centered_text(222, "github.com/igerber/diff-diff", size=17, color=VIOLET)
        self.draw_split_logo(256, size=28)
        self.centered_text(
            284, "Difference-in-Differences for Python", size=14, bold=False, color=GRAY
        )
        self.add_footer()


def main():
    pdf = PerfCarouselPDF()
    try:
        pdf.slide_01_cover()
        pdf.slide_02_problem()
        pdf.slide_03_twfe_speed()
        pdf.slide_04_twfe_memory()
        pdf.slide_05_cs()
        pdf.slide_06_upgrade()
        pdf.slide_07_sdid()
        pdf.slide_08_guarantees()
        pdf.slide_09_practice()
        pdf.slide_10_cta()
        output_path = Path(__file__).parent / "diff-diff-perf-carousel.pdf"
        pdf.output(str(output_path))
        print(f"wrote {output_path}")
    finally:
        pdf.cleanup()


if __name__ == "__main__":
    main()
